uploading assignments
Pawan1005/MI-11-MEAN pull request #175
Opened 2021-04-16 09:59 UTC by mubeen2710

all assignments of mubeen till the date

2021-04-19 06:14 UTC, Richa199 approved these changes

2021-04-19 06:26 UTC, Jestinxavier approved these changes

2021-04-23 09:22 UTC, Pawan1005 requested changes
need to add html tag in every files 
indentation need to be done

2021-04-24 12:50 UTC, Pawan1005 requested changes

2021-04-24 12:50 UTC, Pawan1005 commented on mubeen/html/assign3/mubeenA3_1.html
> +</html>
need indentation
add new line at the end of file

2021-04-24 12:50 UTC, Pawan1005 commented on mubeen/html/assign3/mubeenA3_2home.html
> +</html>
need indentation
add new line at the end of file

2021-04-24 12:50 UTC, Pawan1005 commented on mubeen/html/assign4/q1.html
> +</html>
need indentation
add new line at the end of file

2021-04-24 12:50 UTC, Pawan1005 commented on mubeen/html/assign4/q2.html
> +</html>
need indentation

2021-04-24 13:55 UTC, Pawan1005 approved these changes

2021-04-24 13:58 UTC, merged