Added My Files And Folder
Pawan1005/MI-11-MEAN pull request #176
Opened 2021-04-16 10:12 UTC by vinod2406

2021-04-16 17:04 UTC, vishnukopnar approved these changes

2021-04-18 12:04 UTC, Pranjali1999 approved these changes

2021-04-19 04:33 UTC, akash19972306 approved these changes

2021-04-19 08:42 UTC, vishnukopnar approved these changes

2021-04-21 10:27 UTC, shivling123 commented on vinod/html/ASSIN2/assingment2.html
> +
format code properly remove extraspace

2021-04-21 10:37 UTC, shivling123 requested changes

2021-04-21 10:37 UTC, shivling123 commented on vinod/html/ASSIN3/assingment3.q2.html
> +    <center> <a href="assingment3.q2.html"> Home </a> | <a href="link.html"> MI-MEAN </a> | <a href="link1.html">
format it properly

2021-04-21 10:37 UTC, shivling123 commented on vinod/html/ASSIN3/assingment3.q2.html
> +    </div></div></div>
indentation not proper
close div tag on new line

2021-04-21 10:37 UTC, shivling123 commented on vinod/html/ASSIN4/assingment4.q2.html
> +
remove extra space format code properly

2021-04-21 10:37 UTC, shivling123 commented on vinod/html/ASSIN4/assingment4.q2.html
> +
remove extra space

2021-04-21 10:37 UTC, shivling123 commented on vinod/html/assignment1/assingment1.q2.html
> +However,for learing HTML we recommend a simple text editor like Notpad(pc) or TextEdit(Mac).
add closing tag body ..etc

2021-04-21 10:37 UTC, shivling123 commented on vinod/html/assignment1/assingment1.q3.html
> +HTML is standaed markup language for web page.
containt should be inside tag

2021-04-21 10:39 UTC, shivling123 requested changes
make changes in code as per required

2021-04-22 07:41 UTC, shivling123 commented on vinod/html/ASSIN3/assingment3.q2.html
>          }
check opening of style tag

2021-04-22 07:45 UTC, shivling123 approved these changes

2021-04-22 07:46 UTC, shivling123 approved these changes

2021-04-22 07:48 UTC, shivling123 approved these changes

2021-04-22 07:50 UTC, shivling123 approved these changes

2021-04-22 07:55 UTC, shivling123 commented on vinod/html/ASSIN3/assingment3.q2.html
>      </div>
where is opening div tag

2021-04-22 08:00 UTC, shivling123 approved these changes

2021-04-22 08:01 UTC, shivling123 approved these changes

2021-04-22 08:06 UTC, shivling123 approved these changes

2021-04-22 08:11 UTC, shivling123 commented on vinod/html/ASSIN2/assingment2.html
> +  This artical is about the company.<br>
add this containt  inside proper tag tag

2021-04-22 08:14 UTC, shivling123 commented on vinod/html/ASSIN2/assingment2.html
> +    Google intial public offering(IPO)took place five year later,on 19th August 2004.<br>
add this containt inside tag

2021-04-23 13:24 UTC, avinash0070 commented
need proper title ask with sourabh kanwade 
in title mention it which file or folder you added
and
assign yourself
do this changes

2021-04-23 13:38 UTC, avinash0070 requested changes

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/ASSIN2/assingment2.html
> +
remove all extra lines 
need proper code indentation 
use 4 space in code 
use prettier setting in vs code ask with your mentor

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/ASSIN2/assingment2.html
> +</html>
add new line

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/ASSIN3/assingment 3.q1.html
> +<!DOCTYPE html>
remove all extra lines
need proper code indentation
use 4 space in code

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/ASSIN3/assingment 3.q1.html
> +</html>
add extra line

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/ASSIN3/assingment3.q2.html
> +    </html>
add new line

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/ASSIN3/assingment3.q2.html
> +<!DOCTYPE html>
remove all extra lines
need proper code indentation
use 4 space in code

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/ASSIN3/link.html
> +<!DOCTYPE html>
remove all extra lines
need proper code indentation
use 4 space in code

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/ASSIN3/link.html
> +            <li>sanket</li>
where ol is closed

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/ASSIN3/link.html
> +</html>
add new line

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/ASSIN3/link1.html
> +</html>
add extra line

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/ASSIN3/link1.html
> +<!DOCTYPE html>
remove all extra lines
need proper code indentation
use 4 space in code

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/ASSIN4/assingment4.q1.html
> +    <caption style="color:purple;">
check this line <caption style="color:purple;"> is that work in under Style tag

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/ASSIN4/assingment4.q1.html
> +<!DOCTYPE html>
remove all extra lines
need proper code indentation
use 4 space in code

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/ASSIN4/assingment4.q1.html
> +</html>
Add new line

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/ASSIN4/assingment4.q2.html
> +<!DOCTYPE html>
remove all extra lines
need proper code indentation
use 4 space in code

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/ASSIN4/assingment4.q2.html
> +</html>
Add new line

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/ASSIN4/assingment4.q3.html
> +<!DOCTYPE html>
remove all extra lines
need proper code indentation
use 4 space in code

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/ASSIN4/assingment4.q3.html
> +</html>
add new line at the end of the code

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/assignment1/assingment1.Q1.html
> +</html>>
add new line

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/assignment1/assingment1.Q1.html
> +
remove extra line

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/assignment1/assingment1.q2.html
> +<!DOCTYPE html>
remove all extra lines
need proper code indentation
use 4 space in code

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/assignment1/assingment1.q2.html
> +</html>
Add new line

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/assignment1/assingment1.q3.html
> +<!DOCTYPE html>
remove all extra lines
need proper code indentation
use 4 space in code

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/assignment1/assingment1.q3.html
> +</html>
Add new line

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/assignment1/assinngmen Q4.html
> +<!DOCTYPE html>
remove all extra lines
need proper code indentation
use 4 space in code

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/assignment1/assinngmen Q4.html
> +</html>
Add new line

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/assignment1/assinngmen1. Q4.html
> +<!DOCTYPE html>
remove all extra lines
need proper code indentation
use 4 space in code

2021-04-23 13:38 UTC, avinash0070 commented on vinod/html/assignment1/assinngmen1. Q4.html
> +</html>
Add new line

2021-04-24 10:24 UTC, avinash0070 commented
resolve all the comment u done.....otherwise i'm not tracking you with your changes

2021-04-24 11:05 UTC, avinash0070 approved these changes

2021-04-24 11:07 UTC, merged