Uploaded Successfully
Pawan1005/MI-11-MEAN pull request #181
Opened 2021-04-16 11:19 UTC by Ashwin2812

2021-04-16 12:02 UTC, urmilagagare approved these changes

2021-04-16 13:13 UTC, vijaya1811 approved these changes

2021-04-16 14:44 UTC, shubhamdalal49 approved these changes

2021-04-18 13:07 UTC, nileshp1122 approved these changes

2021-04-18 14:00 UTC, NikitaShivhare1 approved these changes

2021-04-20 11:53 UTC, vijaya1811 approved these changes

2021-04-21 07:03 UTC, jyoti-ing approved these changes

2021-04-21 09:48 UTC, KomalShinde813 requested changes

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/01_Assignment/Ashwin_Ass1.html
> +</html>
extra line required at end of the file

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/01_Assignment/Ashwin_Ass3.html
> +                    <h3>HTML Editor</h3>
check indentation

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/01_Assignment/Ashwin_Ass3.html
> +</html>
extra line required at end of the file

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/01_Assignment/Ashwin_Ass2.html
> +</html>
extra line required at end of the file

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/01_Assignment/Ashwin_Ass2.html
> +        <h3>Introduction</h3>
incomplete program please check question again

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/01_Assignment/Ashwin_Ass4.html
> +</html>
extra line required at end of the file

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/02_Assignment/AshwinAss2.html
> +                <pre><em>This article is about the company.</em></pre>
check indentation

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/03_Assignment/Ashwin_contactus.html
> +
remove extra line

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/03_Assignment/Ashwin_contactus.html
> +<head>
check iindentation

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/03_Assignment/Ashwin_contactus.html
> +<body style="text-align: center; background:  rgb(71, 99, 22);">
check indentation

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/03_Assignment/Ashwin_contactus.html
> +<body style="text-align: center; background:  rgb(71, 99, 22);">
remove extra space which is present after : in style

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/03_Assignment/Ashwin_contactus.html
> +</html>
extra line required at end of the file

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/03_Assignment/Ashwin_mean.html
> +<head>
check indentation

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/03_Assignment/Ashwin_mean.html
> +
remove extra line

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/03_Assignment/Ashwin_mean.html
> +
remove extra line

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/03_Assignment/Ashwin_mean.html
> +<body style="text-align: center; background-color: darkcyan; color: white;">
check indentation

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/03_Assignment/Ashwin_mean.html
> +
remove extra line

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/03_Assignment/Ashwin_mean.html
> +
remove extra lines

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/03_Assignment/Ashwin_mean.html
> +</html>
extra line required at end of the file

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/03_Assignment/Ashwin_simple_webpage.html
> +
remove extra line

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/03_Assignment/Ashwin_simple_webpage.html
> +        }
one line space required after this

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/03_Assignment/Ashwin_simple_webpage.html
> +        .same{
space required before {

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/03_Assignment/Ashwin_simple_webpage.html
> +<body style="background-color: rgb(71, 99, 22); text-align: center;">
check indentation

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/03_Assignment/Ashwin_simple_webpage.html
> +
remove extra lines

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/03_Assignment/Ashwin_simple_webpage.html
> +</html>
extra line required at end of the file

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/04_Assignment/Ashwin_01.html
> +    <title>Document</title>
chnage title, title should be related to program. make this change everywhere

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/04_Assignment/Ashwin_01.html
> +<body>
check indentation

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/04_Assignment/Ashwin_01.html
> +    <table class="center" border="1" style="padding: 10px;color: gainsboro; background-color: dimgrey; height: 350px; width: 500px; text-align: center; margin-bottom: auto; margin-right: auto;">
space required after each style property

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/04_Assignment/Ashwin_01.html
> +</html>
extra line required at end of the file

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/04_Assignment/Ashwin_02.html
> +<head>
check indentation

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/04_Assignment/Ashwin_02.html
> +    <title>Document</title>
change title

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/04_Assignment/Ashwin_02.html
> +<body>
check indentation

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/04_Assignment/Ashwin_02.html
> +                <!-- <td></td> -->
remove commented code

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/04_Assignment/Ashwin_02.html
> +
remove extra line

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/04_Assignment/Ashwin_02.html
> +</html>
extra line required at end of the file

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/04_Assignment/Ashwin_03.html
> +<head>
check indentation

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/04_Assignment/Ashwin_03.html
> +    <title>Document</title>
change title

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/04_Assignment/Ashwin_03.html
> +<body>
check indentation

2021-04-21 09:48 UTC, KomalShinde813 commented on Ashwin/HTML/04_Assignment/Ashwin_03.html
> +</html>
extra line required at end of the file

2021-04-22 13:26 UTC, closed without merging