Uploading Assignments
Pawan1005/MI-11-MEAN pull request #182
Opened 2021-04-16 12:06 UTC by Oshin-250197

2021-04-16 15:14 UTC, roshnidurugwar approved these changes

2021-04-16 17:15 UTC, arshad05786 approved these changes

2021-04-18 12:18 UTC, SamikshaWani approved these changes

2021-04-18 13:39 UTC, roshnidurugwar approved these changes

2021-04-19 05:32 UTC, yogesh141293 approved these changes

2021-04-24 12:43 UTC, Pawan1005 requested changes
need indentation
add new line at the end of file

2021-04-24 12:43 UTC, Pawan1005 commented on Oshin/html/Assignment1/Question1.html
> +</html>
need indentation
add new line at the end of file

2021-04-24 12:43 UTC, Pawan1005 commented on Oshin1/html/Assignment1/Question1.html
> +</html>
need indentation
add new line at the end of file

2021-04-24 12:43 UTC, Pawan1005 commented on Oshin1/html/Assignment1/Question2.html
> +</html>
need indentation  
add new line at the end of file

2021-04-24 12:43 UTC, Pawan1005 commented on Oshin1/html/Assignment1/Question3.html
> +</html>
need indentation
add new line at the end of file

2021-04-24 12:43 UTC, Pawan1005 commented on Oshin1/html/Assignment1/Question4.html
> +</html>
need indentation
add new line at the end of file

2021-04-24 12:43 UTC, Pawan1005 commented on Oshin1/html/Assignment2/Assign2.html
> +</html>
need indentation
add new line at the end of file

2021-04-24 12:43 UTC, Pawan1005 commented on Oshin1/html/Assignment2/Assign2.html
> +<head>
opening head tag is missing

2021-04-24 12:43 UTC, Pawan1005 commented on Oshin1/html/Assignment3/Question1.html
> +</html>
need indentation
add new line at the end of file

2021-04-24 12:43 UTC, Pawan1005 commented on Oshin1/html/Assignment3/Secondquestion/MI-MEANpage.html
> +
remove extra line

2021-04-24 12:43 UTC, Pawan1005 commented on Oshin1/html/Assignment3/Secondquestion/MI-MEANpage.html
> +</html>
add new line at the end of file

2021-04-24 12:43 UTC, Pawan1005 commented on Oshin1/html/Assignment3/Secondquestion/contactpage.html
> +    </body>
closing HTML tag is missing 
add new line at the end of file

2021-04-24 12:43 UTC, Pawan1005 commented on Oshin1/html/Assignment3/Secondquestion/homepage.html
> +  </html>
need indentation
add new line at the end of file

2021-04-24 12:43 UTC, Pawan1005 commented on Oshin1/html/Assignment4/Question1.html
> +</html>
need indentation
add new line at the end of file

2021-04-24 12:43 UTC, Pawan1005 commented on Oshin1/html/Assignment4/Question2.html
> +</html>
need indentation
add new line at the end of file

2021-04-24 12:43 UTC, Pawan1005 commented on Oshin1/html/Assignment4/Question3.html
> +</html>
add new line at the end of file

2021-04-27 05:40 UTC, Pawan1005 approved these changes

2021-04-27 05:40 UTC, Pawan1005 commented on Oshin1/html/Assignment3/Secondquestion/Homepage.html
> +</html>
indentation

2021-04-28 08:40 UTC, SnehalAhir approved these changes

2021-04-28 11:15 UTC, Pawan1005 approved these changes

2021-04-28 11:21 UTC, merged