folder upload
Pawan1005/MI-11-MEAN pull request #183
Opened 2021-04-16 12:24 UTC by Bhavika222

2021-04-16 12:25 UTC, Akash-ing approved these changes

2021-04-18 12:02 UTC, Pranjali1999 approved these changes

2021-04-19 04:35 UTC, vinod2406 approved these changes
ok

2021-04-19 05:40 UTC, akash19972306 approved these changes

2021-04-20 09:22 UTC, Priyankashelke2411 requested changes
Give proper indentation and remove extra line spaces

2021-04-20 09:30 UTC, Priyankashelke2411 requested changes
write a complete code

2021-04-22 09:33 UTC, Priyankashelke2411 requested changes
yes done changes but remove extra lines and give proper indentations

2021-04-24 10:06 UTC, JafarPathan commented on Bhavika/html/Assignment2/Assig2.html
> +</html>
check indentation

2021-04-24 10:07 UTC, JafarPathan commented on Bhavika/html/Assignment3/Bhavika A3_2main.html
> +</html>
add newline at end of file

2021-04-24 10:08 UTC, JafarPathan commented on Bhavika/html/Assignment3/Bhavika A3_2mi-9.html
> +
check this indentation and spaces 
add newline at end of file

2021-04-24 10:12 UTC, JafarPathan reviewed
do changes in all files 
1. use 4 spaces for indentation

2021-04-24 12:29 UTC, JafarPathan commented on Bhavika/html/Assignment3/Bhavika A3_2mi-9.html
> +
do indentation 
add extra line at end of file

2021-04-24 12:30 UTC, JafarPathan commented on Bhavika/html/Assignment2/Assig2.html
> +</html>
do indentation

2021-04-24 12:31 UTC, JafarPathan commented on Bhavika/html/Assignment1/form3.html
> +</html>
do indentation

2021-04-24 12:31 UTC, JafarPathan commented on Bhavika/html/Assignment1/form2.html
> +</html>
do indentation

2021-04-24 12:31 UTC, JafarPathan commented on Bhavika/html/Assignment1/form.html
> +</html>
do indentation

2021-04-24 16:19 UTC, JafarPathan approved these changes

2021-04-24 17:58 UTC, merged