Folder_Uploaded
Pawan1005/MI-11-MEAN pull request #187
Opened 2021-04-16 14:19 UTC by Pranjali1999

2021-04-16 14:24 UTC, Akash-ing approved these changes

2021-04-16 14:25 UTC, Bhavika222 approved these changes

2021-04-16 17:04 UTC, vishnukopnar approved these changes

2021-04-19 04:32 UTC, vinod2406 approved these changes

2021-04-19 04:33 UTC, akash19972306 approved these changes

2021-04-20 02:57 UTC, Pawan1005 requested changes
add new line at the end of file 
and remove extra spaces

2021-04-20 02:57 UTC, Pawan1005 commented on Pranjali/HTML/Assi1/Assi4.html
> +
remove extra lines

2021-04-20 02:57 UTC, Pawan1005 commented on Pranjali/HTML/Assi2/Assignment.html
> +
remove extra line

2021-04-20 02:57 UTC, Pawan1005 commented on Pranjali/HTML/Assi2/Assignment.html
> +
remove extra line

2021-04-20 02:57 UTC, Pawan1005 commented on Pranjali/HTML/Assi2/Assignment.html
> +
remove extra line

2021-04-20 02:57 UTC, Pawan1005 commented on Pranjali/HTML/Assi3/assi3_2.html
> +</html>
add new line here

2021-04-20 02:57 UTC, Pawan1005 commented on Pranjali/HTML/Assi3/assi3_3.html
> +</html>
add new line

2021-04-21 10:01 UTC, preetipie22 requested changes
Please make the changes

2021-04-21 10:01 UTC, preetipie22 commented on Pranjali/HTML/Assi3/assi3_1.html
> +
remove extra lines in other codes as well

2021-04-21 10:01 UTC, preetipie22 commented on Pranjali/HTML/Assi3/assi3_1.html
> +        <div1>
Hey, @Pranjali1999  there is no tag `<div1>` , instead use `<div>`. Use id if you want to distinguish them

2021-04-21 10:01 UTC, preetipie22 commented on Pranjali/HTML/Assi3/assi3_1.html
> +        <ol class="d"><num>1.</num>MI-MEAN
there is no such tag like `<num>`

2021-04-21 10:01 UTC, preetipie22 commented on Pranjali/HTML/Assi3/assi3_1.html
> +            .P1 {
class names are case-sensitive

2021-04-21 10:01 UTC, preetipie22 commented on Pranjali/HTML/Assi3/assi3_1.html
> +            ul.a{
you can give the type in html code as well

2021-04-21 10:01 UTC, preetipie22 commented on Pranjali/HTML/Assi3/assi3_2.html
> +            <p2>
there is no tag like `<p2>`, `<div>`, use class or id instead. Check this for other codes as well

2021-04-21 10:01 UTC, preetipie22 commented on Pranjali/HTML/Assi1/Assi4.html
> +        <title>INTRODUCT/title>
`<title>` tag is not closed

2021-04-21 10:01 UTC, preetipie22 commented on Pranjali/HTML/Assi3/assi3_1.html
> +        <h1><p class="p1">Ambersoft</p></h1>
class names are case sensitive

2021-04-21 10:01 UTC, preetipie22 commented on Pranjali/HTML/Assi4/assi4_2.html
> +                <th>      </th>
no need to give space in other places as well

2021-04-21 10:01 UTC, preetipie22 commented on Pranjali/HTML/Assi4/assi4_2.html
> +        <h2 style="color: rgb(155, 67, 155);"><center>Jan's Spring Term Afternoon Schedule</center></h2>
`<center>` is not supported in  HTML5

2021-04-24 10:27 UTC, avinash0070 commented
Pranjali1999 if you done with your all changes the resolve all comments

2021-04-24 10:28 UTC, avinash0070 commented
Need proper title for this pull request
and also assign yourself
done all changes

2021-04-25 13:05 UTC, avinash0070 requested changes

2021-04-25 13:05 UTC, avinash0070 commented on Pranjali/HTML/Assi2/Assignment.html
> +            }
add new line

2021-04-25 13:05 UTC, avinash0070 commented on Pranjali/HTML/Assi2/Assignment.html
> +            }
add new line

2021-04-25 13:05 UTC, avinash0070 commented on Pranjali/HTML/Assi2/Assignment.html
> +            }
add new line

2021-04-25 13:05 UTC, avinash0070 commented on Pranjali/HTML/Assi2/Assignment.html
> +            }
add new line

2021-04-25 13:05 UTC, avinash0070 commented on Pranjali/HTML/Assi2/Assignment.html
> +            }
add new line

2021-04-25 13:05 UTC, avinash0070 commented on Pranjali/HTML/Assi3/assi3_2.html
> +<!DOCTYPE html>
add new line at the end of all css property

2021-04-25 13:05 UTC, avinash0070 commented on Pranjali/HTML/Assi3/assi3_3.html
> +<!DOCTYPE html>
add new line at the end of all css property

2021-04-25 13:05 UTC, avinash0070 commented on Pranjali/HTML/Assi3/assi3_4.html
> +            h1 {
add new line at the end of all css property

2021-04-25 13:05 UTC, avinash0070 commented on Pranjali/HTML/Assi4/assi4_1.html
> +        <style>
add new line at the end of all css property

2021-04-26 05:25 UTC, avinash0070 commented
Change in title not in commit message 
 do this changes

2021-04-26 06:35 UTC, preetipie22 requested changes

2021-04-26 06:35 UTC, preetipie22 commented on Pranjali/HTML/Assi2/Assignment.html
> +                At that time Larry Page, Sergey Brin, and Eric Schmidt agreed to work together at Google for 30 <u>20</u><br />
You should not use <u> to underline text for presentation purposes, or to denote titles of books.
Instead use `<ins>`

2021-04-26 06:35 UTC, preetipie22 commented on Pranjali/HTML/Assi3/assi3_1.html
> +            .P1 {
class names are case sensitive .p1

2021-04-26 06:57 UTC, avinash0070 approved these changes

2021-04-26 08:36 UTC, merged