Akki work
Pawan1005/MI-11-MEAN pull request #188
Opened 2021-04-16 14:54 UTC by Akash-ing

2021-04-16 17:03 UTC, vishnukopnar approved these changes

2021-04-18 12:01 UTC, Pranjali1999 approved these changes

2021-04-19 04:32 UTC, akash19972306 approved these changes

2021-04-19 04:33 UTC, vinod2406 approved these changes
ok

2021-04-19 05:36 UTC, Bhavika222 approved these changes

2021-04-19 05:44 UTC, Bhavika222 approved these changes

2021-04-20 12:30 UTC, shivnanda6272 requested changes

2021-04-20 12:30 UTC, shivnanda6272 commented on Akash/html/assign 2/Assign1.html
> +</html>
add new line

2021-04-20 12:30 UTC, shivnanda6272 commented on Akash/html/assign 2/assign2.html
> +    <h1><center>Google</center></h1>
we don't use center as a tag.older version

2021-04-20 12:32 UTC, shivnanda6272 requested changes

2021-04-20 12:32 UTC, shivnanda6272 commented on Akash/html/assign 4/assig2.html
> +        <h2 style="color: rgb(155, 67, 155);"><center>Jan's Spring Term Afternoon Schedule</center></h2>
don't use center as a tag.

2021-04-20 12:33 UTC, shivnanda6272 approved these changes

2021-04-21 10:07 UTC, shivling123 commented on Akash/html/assign 2/Assign2.html
> +TML</h1>
indentation not proper

2021-04-21 10:09 UTC, shivling123 commented on Akash/html/assign 2/assign2.html
> +         <title>HTML Assign</title> -->
remove arrow infron of title

2021-04-21 10:10 UTC, shivling123 commented on Akash/html/assign 2/assign4.html
> +    </head><body>
body ag should be on next line

2021-04-21 10:12 UTC, shivling123 requested changes
make change proper

2021-04-26 07:56 UTC, SnehaMakade commented on Akash/html/assign 2/Assign2.html
> +        <h1>HTML
h1 should be in a single line

2021-04-26 07:56 UTC, SnehaMakade commented on Akash/html/assign 2/Assign2.html
>          <h3>
<H3> SHOULD BE in a sigle line

2021-04-26 07:57 UTC, SnehaMakade commented on Akash/html/assign 2/Assign2.html
>          </h3>
try to close the tags on the same line itself.make this change in each file

2021-04-26 08:00 UTC, SnehaMakade commented on Akash/html/assign 2/assign2.html
>              div{background-color: palevioletred;}
it shouldbe like div  {
                             background-color: palevioletred;
                         }
make this change in each file.

2021-04-26 08:02 UTC, SnehaMakade commented on Akash/html/assign 2/assign2.html
>        <h2>From the grage to the Googleplex</h2>
always add aspace after colon and comma so make this change everwhere

2021-04-26 08:04 UTC, SnehaMakade commented on Akash/html/assign 2/assign2.html
remove extra lines

2021-04-26 08:05 UTC, SnehaMakade commented on Akash/html/assign 2/assign2.html
>  </html>
add a new end line in each file

2021-04-26 08:05 UTC, SnehaMakade commented on Akash/html/assign 2/assign4.html
>          <p>I am akash ingle.i am from chikhali,Dist buldana.<br>
add a space after comma

2021-04-26 08:06 UTC, SnehaMakade commented on Akash/html/assign 2/assign4.html
>  </html>
add a new end line

2021-04-26 08:09 UTC, SnehaMakade commented on Akash/html/assign 4/assig2.html
> +        <h2 style="color: rgb(155, 67, 155);text-align: center;">Jan's Spring Term Afternoon Schedule</h2>
remove extra lines in this file and a space after colon and before opening bracket there should be a space so add tht and add a space after semicolon

2021-04-26 08:09 UTC, SnehaMakade commented on Akash/html/assign 4/assig2.html
>          <table style="width:100%;">
add aspace after colon

2021-04-26 08:10 UTC, SnehaMakade commented on Akash/html/assign 4/assig2.html
>              <tr class="a">
there is no class inside style tag oa name a so if this class is not in use then remove it

2021-04-26 08:13 UTC, SnehaMakade commented on Akash/html/assign 5/assign1.html
> +            body{
add a space before opening bracket

2021-04-26 08:13 UTC, SnehaMakade commented on Akash/html/assign 5/assign1.html
> +
remove all extra lines

2021-04-26 08:13 UTC, SnehaMakade commented on Akash/html/assign 5/assign1.html
> +        <h1>
make  a h1 in a single line

2021-04-26 08:14 UTC, SnehaMakade commented on Akash/html/assign 5/assign1.html
> +
remove all extra lines

2021-04-26 08:15 UTC, SnehaMakade commented on Akash/html/assign 5/assign1.html
> +</html>
add a new end line in all files and remove extra lines in all files

2021-04-26 08:15 UTC, SnehaMakade requested changes
do changes as per comments given

2021-04-26 18:02 UTC, SnehaMakade commented on Akash/html/assign 2/Assign2.html
> +        <title>
write title tag in a single line

2021-04-26 18:03 UTC, SnehaMakade commented on Akash/html/assign 2/Assign2.html
> +        <p>
include p tag in a same line.

2021-04-26 18:05 UTC, SnehaMakade commented on Akash/html/assign 2/Assign2.html
> +
check is there any trailing spaces present in line no. 19 as its showing the error of no new line at end of file

2021-04-26 18:06 UTC, SnehaMakade commented on Akash/html/assign 2/assign2.html
> +            <i><b>Larry page</b></i
check indentation </i> should be in a single line

2021-04-26 18:07 UTC, SnehaMakade commented on Akash/html/assign 2/assign2.html
> +            there,was assigned to show him around.
always add a space after comma

2021-04-26 18:08 UTC, SnehaMakade commented on Akash/html/assign 2/assign2.html
> +                <i><b>Larry page</b></i
do proper closing of i tag

2021-04-26 18:09 UTC, SnehaMakade commented on Akash/html/assign 2/assign2.html
> +                    href="https://www.World Wide web/"
check indentation

2021-04-26 18:10 UTC, SnehaMakade commented on Akash/html/assign 2/assign2.html
> +                They called this search engine mark <i><marki>Backrub</marki></i>
check for the tag u have used it should be < mark> only

2021-04-26 18:10 UTC, SnehaMakade commented on Akash/html/assign 3/Assign9.html
> +
where is doctype ? add that

2021-04-26 18:11 UTC, SnehaMakade commented on Akash/html/assign 3/Assign9.html
> +            h1{text-align: center;}
there should be space before opening bracket like h1 {} not like h1{}

2021-04-26 18:11 UTC, SnehaMakade commented on Akash/html/assign 3/Assign9.html
> +
remove extra lines

2021-04-26 18:11 UTC, SnehaMakade commented on Akash/html/assign 3/Assign9.html
> +
remove all extra lines

2021-04-26 18:12 UTC, SnehaMakade commented on Akash/html/assign 3/assign10.html
> +<html>
add a doctype.

2021-04-26 18:13 UTC, SnehaMakade commented on Akash/html/assign 3/assign10.html
> +	<title></title>
if there is no title then remove this tag or else add a title .

2021-04-26 18:13 UTC, SnehaMakade commented on Akash/html/assign 3/assign10.html
> +<body style="background-color: pink;">
check indentation

2021-04-26 18:13 UTC, SnehaMakade commented on Akash/html/assign 3/assign8.html
> +
remove extra line

2021-04-26 18:14 UTC, SnehaMakade commented on Akash/html/assign 3/assign8.html
> +        <h4>
include h4in a single line

2021-04-26 18:14 UTC, SnehaMakade commented on Akash/html/assign 3/assign8.html
> +
remove extra line

2021-04-26 18:14 UTC, SnehaMakade commented on Akash/html/assign 3/style.css
> +#left{
always add a space before opening bracket and a line between each block

2021-04-26 18:15 UTC, SnehaMakade commented on Akash/html/assign 4/assig2.html
> +            table,
include table and th in a single line

2021-04-26 18:15 UTC, SnehaMakade commented on Akash/html/assign 4/assig2.html
> +            th,
include th td in a single line

2021-04-26 18:16 UTC, SnehaMakade commented on Akash/html/assign 4/assig2.html
> +
remove all extra lines

2021-04-26 18:16 UTC, SnehaMakade commented on Akash/html/assign 4/assign1.html
> +            table,
include table th and td in a single line

2021-04-26 18:16 UTC, SnehaMakade commented on Akash/html/assign 4/assign3.html
> +            table,
include all tags in a single line

2021-04-26 18:17 UTC, SnehaMakade commented on Akash/html/assign 4/assign3.html
> +
remove all extra lines

2021-04-26 18:17 UTC, SnehaMakade commented on Akash/html/assign 5/assign1.html
> +
remove extra line

2021-04-26 18:17 UTC, SnehaMakade requested changes
do the changes as per comments given

2021-04-27 07:08 UTC, vishnukopnar approved these changes

2021-04-27 07:26 UTC, SnehaMakade commented on Akash/html/assign 2/assign2.html
> +
why not removed this extra line?

2021-04-27 07:26 UTC, SnehaMakade commented on Akash/html/assign 2/assign2.html
> +<head>
indentation is not proper

2021-04-27 07:26 UTC, SnehaMakade commented on Akash/html/assign 2/assign2.html
> +<body>
do proper indentation

2021-04-27 07:27 UTC, SnehaMakade commented on Akash/html/assign 2/assign2.html
> +</html>
add a new end line

2021-04-27 07:28 UTC, SnehaMakade commented on Akash/html/assign 3/assign10.html
> +<head>
indentation is not proper

2021-04-27 07:29 UTC, SnehaMakade commented on Akash/html/assign 3/assign7.html
> +        <h1><p class="p1">Ambersoft</p></h1>
why to use p tag inside h1 tag instead use h1 tag only

2021-04-27 07:29 UTC, SnehaMakade commented on Akash/html/assign 3/assign7.html
> +    </head><body>
what kind of indentation is this? do proper indentation

2021-04-27 07:30 UTC, SnehaMakade commented on Akash/html/assign 3/assign7.html
> +            <ul>​
indentation?

2021-04-27 07:30 UTC, SnehaMakade commented on Akash/html/assign 3/assign7.html
> +
remove all extra lines

2021-04-27 07:31 UTC, SnehaMakade commented on Akash/html/assign 4/assign1.html
> +            table,th, td {
add space after comma

2021-04-27 07:32 UTC, SnehaMakade commented on Akash/html/assign 4/assign1.html
> +            ><center><b>A test table with merged cells</b></center></margin
dont uise center tag instead use text-align: center property

2021-04-27 07:32 UTC, SnehaMakade commented on Akash/html/assign 4/assign3.html
> +            table,th,td {
add space after comma

2021-04-27 07:32 UTC, SnehaMakade commented on Akash/html/assign 4/assign3.html
> +
remove extra line and add space after comma

2021-04-27 07:33 UTC, SnehaMakade commented on Akash/html/assign 5/assign1.html
> +                <li>
include <li> tag in a single line only

2021-04-27 07:33 UTC, SnehaMakade requested changes
do changes as per comments given

2021-04-27 11:31 UTC, SnehaMakade commented on Akash/html/assign 3/assign10.html
> +	    <h2>Ambersoft</h2>
indentation is not proper

2021-04-27 11:32 UTC, SnehaMakade commented on Akash/html/assign 4/assig2.html
> +            th,
havent done this change why? write it as table, td {}

2021-04-27 11:33 UTC, SnehaMakade commented on Akash/html/assign 4/assign1.html
> +            table,
do this change

2021-04-27 11:33 UTC, SnehaMakade requested changes
do the changes as per comments given

2021-04-27 17:02 UTC, SnehaMakade commented on Akash/html/assign 3/assign8.html
> +<html>
no doctype is present add that

2021-04-27 17:04 UTC, SnehaMakade commented on Akash/html/assign 4/assig2.html
> +                            }
this bracket should be below tables tmeansclosing bracket should be on the same line

2021-04-27 17:06 UTC, SnehaMakade commented on Akash/html/assign 4/assign3.html
> +            table,
why changes not done in this file

2021-04-27 17:07 UTC, SnehaMakade commented on Akash/html/assign 4/assign3.html
> +            th,
do proper changes

2021-04-27 17:07 UTC, SnehaMakade requested changes
do proper changes

2021-04-29 06:02 UTC, SnehaMakade commented on Akash/html/assign 4/assign3.html
> +            table,
this too also should be in a single line like table, th, td { watever style u want to write} in this way

2021-04-29 06:24 UTC, SnehaMakade approved these changes

2021-04-29 06:51 UTC, merged