Vishnu 45
Pawan1005/MI-11-MEAN pull request #191
Opened 2021-04-16 16:59 UTC by vishnukopnar

2021-04-18 11:59 UTC, Pranjali1999 approved these changes

2021-04-19 04:31 UTC, akash19972306 approved these changes

2021-04-19 05:34 UTC, Bhavika222 approved these changes

2021-04-19 05:35 UTC, Bhavika222 approved these changes

2021-04-19 08:36 UTC, Akash-ing approved these changes

2021-04-20 12:21 UTC, shivnanda6272 approved these changes

2021-04-21 11:05 UTC, shivnanda6272 requested changes
Please make the changes

2021-04-21 11:05 UTC, shivnanda6272 commented on Vishnu/HTML/Assignment2/Assignment2.html
> +</html>
add new line

2021-04-21 11:05 UTC, shivnanda6272 commented on Vishnu/HTML/Assignment3/ass2_contact.html
> +</html>
Add new end line after in all files

2021-04-21 11:05 UTC, shivnanda6272 commented on Vishnu_45/html/Assignment2/Assignment2.html
> +
remove all extra spaces

2021-04-21 13:50 UTC, vishnukopnar commented on Vishnu/HTML/Assignment2/Assignment2.html
> +</html>
Yes sir, I'll do that

2021-04-21 13:50 UTC, vishnukopnar commented on Vishnu/HTML/Assignment3/ass2_contact.html
> +</html>
yes sir

2021-04-21 13:50 UTC, vishnukopnar commented on Vishnu_45/html/Assignment2/Assignment2.html
> +
yes sir

2021-04-21 14:01 UTC, vishnukopnar commented on Vishnu/HTML/Assignment2/Assignment2.html
> +</html>
Sir, I have to push updated files on github, is it right?

2021-04-22 04:10 UTC, shivnanda6272 approved these changes

2021-04-22 04:13 UTC, shivnanda6272 approved these changes

2021-04-24 09:55 UTC, avinash0070 commented
Change the title
give proper name 
this title is not acceptable

2021-04-24 10:18 UTC, avinash0070 requested changes

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment1/Assign1.html
> +<!DOCTYPE html>
need proper indentation

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment1/Assign1.html
> +
remove extra line

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment1/Assign1.html
> +
remove extra line

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment1/Assign2.html
> +<!DOCTYPE html>
Need proper indentation
remove all extra line

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment1/Assign3.html
> +<!DOCTYPE html>
Need proper indentation
remove all extra line

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment1/Assign3.html
> +
remove this line

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment2/Assignment2.html
> +<!DOCTYPE html>
remove all extra lines

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment2/Assignment2.html
> +</html>
Add new line

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment3/ass1.html
> +            }
add new line here

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment3/ass1.html
> +            }
add new line here

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment3/ass1.html
> +</html>
add new line

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment3/ass1.html
> +<!DOCTYPE html>
remove all extra lines

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment3/ass2_contact.html
> +<!DOCTYPE html>
why are you use <!DOCTYPE html> 2 times

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment3/ass2_contact.html
> +</html>
add new line

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment3/ass2_home.html
> +<!DOCTYPE html>
need proper indentation 
use new lines in css code

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment3/ass2_home.html
> +</html>
add new lines at the end of the code

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment3/ass2_mean.html
> +            }
add new line

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment3/ass2_mean.html
> +            }
add new line

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment3/ass2_mean.html
> +<!DOCTYPE html>
need proper code indentation and remove all extra lines

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment3/ass2_mean.html
> +</html>
Add new line

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment4/Assign_1.html
> +<!DOCTYPE html>
need 4 spaces and proper code indentation

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment4/Assign_1.html
> +</html>
new line added

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment4/Assign_2.html
> +</html>
add new line

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment4/Assign_2.html
> +<!DOCTYPE html>
need 4 spaces and proper code indentation

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment4/Assign_3.html
> +<!DOCTYPE html>
need 4 spaces and proper code indentation

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment4/Assign_3.html
> +      }
add new line in css code

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment4/Assign_3.html
> +
remove extra line

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu/HTML/Assignment4/Assign_3.html
> +
remove extra line

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu_45/html/Assignment1/Assign2.html
> +<!DOCTYPE html>
need proper code indentation

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu_45/html/Assignment1/Assign3.html
> +<!DOCTYPE html>
need proper code indentation

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu_45/html/Assignment2/Assignment2.html
> +</html>
add new line

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu_45/html/Assignment3/ass1.html
> +<!DOCTYPE html>
need 4 spaces in code indentation
remove extra lines

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu_45/html/Assignment5/style.css
> +}
add new line 
change all with at the end of css property ends

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu_45/html/Assignment5/index.html
> +<html>
need proper indentation

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu_45/html/Assignment4/Assign_3.html
> +<!DOCTYPE html>
need proper indentation
add new line
change all with at the end of css property ends

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu_45/html/Assignment4/Assign_2.html
> +<!DOCTYPE html>
need proper code indentation
remove all extra lines
add new line
change all with at the end of css property ends

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu_45/html/Assignment4/Assign_1.html
> +<!DOCTYPE html>
need proper code indentation

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu_45/html/Assignment3/ass2_mean.html
> +<!DOCTYPE html>
need proper code indentation
add new line
change all with at the end of css property ends

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu_45/html/Assignment3/ass2_home.html
> +<!DOCTYPE html>
need proper code indentation
remove all extra lines
add new line
change all with at the end of css property ends

2021-04-24 10:18 UTC, avinash0070 commented on Vishnu_45/html/Assignment3/ass2_contact.html
> +<!DOCTYPE html>
need proper code indentation
remove all extra lines
add new line
change all with at the end of css property ends
remove  !DOCTYPE html

2021-04-24 10:19 UTC, avinash0070 commented
resolve all changes if they are done

2021-04-26 07:48 UTC, avinash0070 commented
resolve all the comments 
change title as well 
mention which file you added n your pull request

2021-04-27 09:17 UTC, avinash0070 commented
do changes as soon as possible

2021-04-30 07:22 UTC, avinash0070 approved these changes

2021-04-30 08:18 UTC, merged

2021-04-30 08:19 UTC, vishnukopnar commented
successfully merged