Folder Added
Pawan1005/MI-11-MEAN pull request #193
Opened 2021-04-17 05:41 UTC by SamikshaWani

2021-04-17 11:21 UTC, Oshin-250197 approved these changes

2021-04-18 13:37 UTC, roshnidurugwar approved these changes

2021-04-18 13:53 UTC, arshad05786 approved these changes

2021-04-19 05:09 UTC, yogesh141293 approved these changes

2021-04-19 17:56 UTC, SnehalAhir approved these changes

2021-04-20 12:52 UTC, yogesh141293 approved these changes

2021-04-21 10:01 UTC, preetipie22 requested changes
Please make the changes according

2021-04-21 10:01 UTC, preetipie22 commented on Samiksha/html/Assignment1/Assignment no 1.html
> +    <hr size="1" width="100% color="black">
Hey @SamikshaWani , `"100%"` double quotes should be closed

2021-04-21 10:01 UTC, preetipie22 commented on Samiksha/html/Assignment2/Assign1.html
> +At that time Larry Page, Sergey Brin, and Eric Schmidt agreed to work together at Google for <del>30</del> <u>20</u> <br>
The `<ins>` tag defines a text that has been inserted into a document. Browsers will usually underline inserted text.
So, use `<ins>` instead of `<u>`

2021-04-21 10:01 UTC, preetipie22 commented on Samiksha/html/Assignment3/Assign3_2_Contact.html
> +    <center><h1>Ambersoft</h1></center>
`<center>` is not any tag, instead use styling

2021-04-21 10:01 UTC, preetipie22 commented on Samiksha/html/Assignment3/Assign3_2_Home.html
> +<img src="Employee.jpg" alt="Employee" style="float: left; width: 42px height: 42px;;">
```suggestion
<img src="Employee.jpg" alt="Employee" style="float: left; width: 42px; height: 42px;">
```

2021-04-21 10:01 UTC, preetipie22 commented on Samiksha/html/Assignment3/Assign3_2_Home.html
> +
remove extra lines

2021-04-21 10:01 UTC, preetipie22 commented on Samiksha/html/Assignment3/Assignment3_2main.html
> +    <center><h1>Ambersoft</h1></center>
https://www.w3schools.com/tags/tag_center.asp

2021-04-21 10:01 UTC, preetipie22 commented on Samiksha/html/Assignment4/Assign4_1.html
> +            <td>1.7</th>
`<td>` is not closed

2021-04-21 10:01 UTC, preetipie22 commented on Samiksha/html/Assignment4/Assign4_3.html
> +        </tr>
extra `<tr>` tag

2021-04-22 05:53 UTC, preetipie22 requested changes
Please unnecessary lines in all codes

2021-04-22 05:53 UTC, preetipie22 commented on Samiksha/html/Assignment1/Assignment no 1.html
> +<<<<<<< HEAD
you should use single opening tag

2021-04-22 05:53 UTC, preetipie22 commented on Samiksha/html/Assignment1/Assignment no 1.html
> +>>>>>>> 84232bb5105d425924556eabcefbf339be0ceb5b
unnecessary line `>>>>>>> 84232bb5105d425924556eabcefbf339be0ceb5b` in other codes too

2021-04-22 05:53 UTC, preetipie22 commented on Samiksha/html/Assignment2/Assign1.html
> +</html>
`</html>` should be closed once

2021-04-22 05:53 UTC, preetipie22 commented on Samiksha/html/Assignment3/Assignment3_2main.html
> +>>>>>>> 84232bb5105d425924556eabcefbf339be0ceb5b
remove it from here

2021-04-22 11:55 UTC, SnehaMakade commented on Samiksha/html/Assignment1/Assignment no 1.html
> +   <h1> HTML Editor </h1>
remove extra space everwhere in all files

2021-04-22 11:55 UTC, SnehaMakade commented on Samiksha/html/Assignment1/Assignment no 1.html
> +   <p>
write this in single line

2021-04-22 11:56 UTC, SnehaMakade commented on Samiksha/html/Assignment1/Assignment no 1.html
>     <h1>
dont braek the h1 tag in 3 lines, make it a single line

2021-04-22 11:57 UTC, SnehaMakade commented on Samiksha/html/Assignment1/Assignment no 1.html
> +    <p> Web Pages can be created and modified by using proffessional HTML editors. <br>
why there is same code agian and agin in ur files, remove duplicate code

2021-04-22 11:57 UTC, SnehaMakade commented on Samiksha/html/Assignment1/Assignment no 1.html
> +   <p> Web Pages can be created and modified by using proffessional HTML editors. <br>
remove duplicate code

2021-04-22 11:58 UTC, SnehaMakade commented on Samiksha/html/Assignment1/Assignment no 1.html
>     <h1> About me </h1>
remove extra space

2021-04-22 11:59 UTC, SnehaMakade commented on Samiksha/html/Assignment2/Assign1.html
> +   <body style="background-color:Orange;">
indentation is not proper why used body tag inside <head tag>?

2021-04-22 12:00 UTC, SnehaMakade commented on Samiksha/html/Assignment2/Assign1.html
> +     .a{
give proper class name, change the name of class

2021-04-22 12:00 UTC, SnehaMakade commented on Samiksha/html/Assignment2/Assign1.html
>   <h1>  From the garage to the Googleplex </h1>
remove extra space

2021-04-22 12:01 UTC, SnehaMakade commented on Samiksha/html/Assignment2/Assign1.html
>  <p> By some accounts, they disagreed about nearly everything during that first meeting, but by the following
remove dulicate code

2021-04-22 12:02 UTC, SnehaMakade commented on Samiksha/html/Assignment2/Assign1.html
>  individual pages on the <b style="color:blue"> World Wide Web</b> .<br> </p>
always add after colon

2021-04-22 12:03 UTC, SnehaMakade commented on Samiksha/html/Assignment2/Assign1.html
>   </body>
indentation is not proper there should be always four tab space between parent and children tag.

2021-04-22 12:03 UTC, SnehaMakade commented on Samiksha/html/Assignment2/Assign1.html
> + </html>
add new end line in all  files.

2021-04-22 12:06 UTC, SnehaMakade commented on Samiksha/html/Assignment3/Assign3_2_Home.html
>  <h1>Ambersoft</h1>
all tags under body tag should be four space after, so do proper indentation.

2021-04-22 12:07 UTC, SnehaMakade commented on Samiksha/html/Assignment3/Assign3_2_Home.html
> +<a href="Assign3_2_Home.html">Home</a> |
indentation is not proper and remove extra operator after </a>

2021-04-22 12:08 UTC, SnehaMakade commented on Samiksha/html/Assignment3/Assign3_2_MI-MEAN.html
> +    <a href="Assign3_2_Home.html">Home</a> |
do proper indentation

2021-04-22 12:09 UTC, SnehaMakade commented on Samiksha/html/Assignment3/Assignment3_2main.html
> +    </div>
check indentation

2021-04-22 12:10 UTC, SnehaMakade commented on Samiksha/html/Assignment4/Assign4_1.html
>               border-collapse: collapse;
there should be always space after comma so add that after comma.

2021-04-22 12:11 UTC, SnehaMakade commented on Samiksha/html/Assignment4/Assign4_1.html
>          </tr>
correct the indentation

2021-04-22 12:12 UTC, SnehaMakade requested changes
do changes as per comments given to each file and remove duplicate code, do proper indentation inall files.

2021-04-26 07:30 UTC, SnehaMakade commented on Samiksha/html/Assignment1/Assignment no 1.html
> +  </head>
check indentation

2021-04-26 07:31 UTC, SnehaMakade commented on Samiksha/html/Assignment2/Assign1.html
> +                   text-align: center;
only 4 tab space is okay so check indentation

2021-04-26 07:32 UTC, SnehaMakade commented on Samiksha/html/Assignment2/Assign1.html
> +        <h1 class="google"> Google </h1>
remove extra spaces

2021-04-26 07:37 UTC, SnehaMakade commented on Samiksha/html/Assignment3/Assign3_2_Contact.html
> +        <p><b>Contact No</b>:547211255<br>
add aspace after colon

2021-04-26 07:38 UTC, SnehaMakade commented on Samiksha/html/Assignment3/Assign3_2_Home.html
> +        <img src ="Employee.jpg" alt="Employye" style="float: right; width: 42px height: 42px">
remove extra space after src

2021-04-26 07:42 UTC, SnehaMakade commented on Samiksha/html/Assignment3/Assignment3_2main.html
> +              div {
check the indentation

2021-04-26 07:45 UTC, SnehaMakade commented on Samiksha/html/Assignment4/Assign4_3.html
> +            table,th,td {
add space after comma

2021-04-26 07:45 UTC, SnehaMakade commented on Samiksha/html/Assignment4/Assign4_3.html
> +                border:1px solid black;
add space after colon

2021-04-26 07:46 UTC, SnehaMakade commented on Samiksha/html/Assignment4/Assig4_2.html
> +            table,th,td {
add space after colon

2021-04-26 07:46 UTC, SnehaMakade commented on Samiksha/html/Assignment4/Assign4_1.html
> +            table,th,td {
add space after comma

2021-04-26 07:48 UTC, SnehaMakade commented on Samiksha/html/Assignment1/Assign1_2.html
> +        However, for learning HTML we recommend a simple text editor like Notepad(PC) orTextEdit(Mac).</p>
add a space after or

2021-04-26 07:48 UTC, SnehaMakade requested changes
do changes as per comments given and change the pr name give proper names according to assignments

2021-04-26 09:04 UTC, SnehaMakade approved these changes

2021-04-26 09:33 UTC, merged