Folder Added:HTML Assignment
Pawan1005/MI-11-MEAN pull request #195
Opened 2021-04-17 10:26 UTC by pritikekan

2021-04-17 11:52 UTC, anuja1603 approved these changes

2021-04-19 09:36 UTC, pooja-nagare approved these changes

2021-04-19 14:36 UTC, shivani-pawbake approved these changes

2021-04-20 05:57 UTC, Amit727619 approved these changes

2021-04-21 08:45 UTC, jyoti-ing approved these changes

2021-04-21 10:16 UTC, JafarPathan commented on priti/HTML/Assign. 2/Que1.html
> +
removed extra lines

2021-04-21 10:16 UTC, JafarPathan commented on priti/HTML/Assign. 2/Que1.html
> +                <p>  They called this search engine <cite>Backrub.</cite></p>
check indentation

2021-04-21 10:17 UTC, JafarPathan commented on priti/HTML/Assign. 2/Que1.html
> +
remove extra line

2021-04-21 10:17 UTC, JafarPathan commented on priti/HTML/Assign.1/Assign1.html
> +
remove line

2021-04-21 10:18 UTC, JafarPathan commented on priti/HTML/Assign.1/Assign1.html
> +</html>
add extra line at end

2021-04-21 10:18 UTC, JafarPathan commented on priti/HTML/Assign.1/Assign4.html
> +        <p><b>MY name is priti. I am 22yrs old from nashik</p>
check tags

2021-04-21 10:20 UTC, JafarPathan commented on priti/HTML/Assign.3/pritiA3_2contact.html
> +      us.Contact us.Contact us.Contact us.Contact us.
.......?

2021-04-21 10:28 UTC, JafarPathan reviewed
Check indentation in all file use 4 spaces for indentation
add extra line at the end of files 
try to implement only one type of css

2021-04-22 06:34 UTC, jyoti-ing requested changes
remove extra lines
ques1.html

2021-04-22 15:22 UTC, JafarPathan approved these changes

2021-04-22 15:32 UTC, merged