upload all assignment
Pawan1005/MI-11-MEAN pull request #197
Opened 2021-04-17 14:03 UTC by Prashant698

2021-04-17 14:15 UTC, Phantom-Code requested changes

2021-04-17 14:15 UTC, Phantom-Code commented on prashant/HTML/Assignment4/table2.html
> +
Remove Extra Space

2021-04-17 14:15 UTC, Phantom-Code commented on prashant/HTML/Assignment4/table2.html
> +
Remove extra space

2021-04-17 14:15 UTC, Phantom-Code commented on prashant/HTML/Assignment3/mean.html
> +            <a href="/home/prashantsahu/MI-11-MEAN/prashant/HTML/Assignment3/contact.html">Contact</a>
You have give absolute path to href so this will only work on your machine. To work for others give relative path .

2021-04-17 14:15 UTC, Phantom-Code commented on prashant/HTML/Assignment3/home.html
> +            <a href="/home/prashantsahu/MI-11-MEAN/prashant/HTML/Assignment3/contact.html">Contact</a>
Use relative parh

2021-04-17 14:15 UTC, Phantom-Code commented on prashant/HTML/Assignment3/contact.html
> +            <a href="/home/prashantsahu/MI-11-MEAN/prashant/HTML/Assignment3/contact.html">Contact</a>
Use Relative path

2021-04-20 06:55 UTC, Phantom-Code commented on prashant/HTML/Assignment3/contact.html
> +            <a href="/home/prashantsahu/MI-11-MEAN/prashant/HTML/Assignment3/contact.html">Contact</a>
.

2021-04-20 07:14 UTC, dayanandviveki approved these changes
No Changes Required

2021-04-20 08:11 UTC, Prashant698 commented on prashant/HTML/Assignment3/contact.html
> +            <a href="/home/prashantsahu/MI-11-MEAN/prashant/HTML/Assignment3/contact.html">Contact</a>
> Use Relative path

not required

2021-04-20 08:14 UTC, Prashant698 commented on prashant/HTML/Assignment3/home.html
> +            <a href="/home/prashantsahu/MI-11-MEAN/prashant/HTML/Assignment3/contact.html">Contact</a>
not

2021-04-20 08:14 UTC, Prashant698 commented on prashant/HTML/Assignment3/home.html
> +            <a href="/home/prashantsahu/MI-11-MEAN/prashant/HTML/Assignment3/contact.html">Contact</a>
> Use relative parh

not required to change path

2021-04-20 08:31 UTC, Phantom-Code approved these changes

2021-04-20 08:50 UTC, kalyani1942 requested changes

2021-04-20 08:50 UTC, kalyani1942 commented on prashant/HTML/Assignment4/table2.html
> +
Remove space

2021-04-20 08:50 UTC, kalyani1942 commented on prashant/HTML/Assignment4/table2.html
> +
Remove Space

2021-04-20 08:50 UTC, kalyani1942 commented on prashant/HTML/Assignment4/table2.html
> +
Remove Space

2021-04-21 03:21 UTC, somesh6797 requested changes
Remove unnecessary spaces

2021-04-21 04:14 UTC, dayanandviveki approved these changes
No changes Required

2021-04-21 08:00 UTC, kalyani1942 approved these changes

2021-04-22 06:25 UTC, somesh6797 approved these changes

2021-04-23 09:05 UTC, Pawan1005 requested changes
need to correct indentation 
for files assignment 1 
assignment 2
for assignment 3 remove some extra lines from files

2021-04-23 09:05 UTC, Pawan1005 commented on prashant/HTML/Assignment1/ASSIn1.html
> +
remove extra line

2021-04-23 09:05 UTC, Pawan1005 commented on prashant/HTML/Assignment1/ASSIn2.html
> +
remove extra line

2021-04-23 09:05 UTC, Pawan1005 commented on prashant/HTML/Assignment2/Assignment2.html
> +</html>
add new line

2021-04-23 10:14 UTC, Pawan1005 approved these changes

2021-04-23 10:34 UTC, merged