Urmila
Pawan1005/MI-11-MEAN pull request #199
Opened 2021-04-17 16:52 UTC by urmilagagare

2021-04-18 06:08 UTC, Ashwin2812 approved these changes

2021-04-18 06:53 UTC, shubhamdalal49 requested changes

2021-04-18 06:53 UTC, shubhamdalal49 commented on urmila/HTML/assignment4-Q2.html
> +
remove this extra space

2021-04-18 06:53 UTC, shubhamdalal49 commented on urmila/HTML/assignment4-Q2.html
> +        <th>2:00</th>
check the format of your document

2021-04-18 06:53 UTC, shubhamdalal49 commented on urmila/HTML/assignment8A.html
> +</head>
remove this extra head

2021-04-18 14:00 UTC, NikitaShivhare1 approved these changes

2021-04-18 15:33 UTC, nileshp1122 approved these changes

2021-04-19 04:54 UTC, vijaya1811 approved these changes

2021-04-19 10:47 UTC, merged