uploaded:Assignment
Pawan1005/MI-11-MEAN pull request #205
Opened 2021-04-18 13:43 UTC by shivani-pawbake

2021-04-19 09:36 UTC, pritikekan approved these changes

2021-04-19 09:45 UTC, shubhamdalal49 approved these changes

2021-04-19 13:32 UTC, Amit727619 approved these changes

2021-04-19 18:10 UTC, anuja1603 approved these changes

2021-04-20 08:32 UTC, pooja-nagare approved these changes

2021-04-20 12:09 UTC, shivnanda6272 commented on Shivani/HTML/assign2/que.html
> +<h2 style="color:green;"><center>Thank You!!</center></h2></div>
we don't use <center>as a tag, it is older version

2021-04-20 12:10 UTC, shivnanda6272 commented on Shivani/HTML/assign2/que.html
> +<h2 style="color:green;"><center>Thank You!!</center></h2></div>
we don't use center as a tag.it is older version.

2021-04-20 12:12 UTC, shivnanda6272 commented on Shivani/HTML/assign3/2/Mean.html
> +</html>
add new line

2021-04-20 12:15 UTC, shivnanda6272 requested changes
changes request

2021-04-21 07:23 UTC, shubhamdalal49 approved these changes

2021-04-21 07:24 UTC, shubhamdalal49 approved these changes

2021-04-21 07:31 UTC, Amit727619 approved these changes

2021-04-21 09:03 UTC, shivnanda6272 approved these changes

2021-04-21 09:04 UTC, shivnanda6272 approved these changes

2021-04-22 05:21 UTC, shivnanda6272 approved these changes

2021-04-22 05:24 UTC, shivnanda6272 approved these changes

2021-04-22 12:22 UTC, merged