Uploaded In Assignment
Pawan1005/MI-11-MEAN pull request #206
Opened 2021-04-18 14:22 UTC by NikitaShivhare1

2021-04-18 15:14 UTC, nileshp1122 approved these changes

2021-04-18 16:32 UTC, Ashwin2812 approved these changes

2021-04-19 06:21 UTC, urmilagagare approved these changes

2021-04-19 06:21 UTC, shubhamdalal49 approved these changes

2021-04-21 09:02 UTC, nikita0699 approved these changes

2021-04-21 10:19 UTC, KomalShinde813 requested changes

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_1/Assignment1.html
> +
remove extra line

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_1/Assignment1.html
> +</html>
extra line required at end of the file

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_1/Assignment2.html
> +            <title>ASSIGNMENT2</title>
check indentation remove extra space only 4 spaces required

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_1/Assignment2.html
> +        Howerver, For Learning HTML we Recommanded A Simple TextEditor like Notepad(Pc) or TextEdit(MAC)
check indentation

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_1/Assignment2.html
> +</HTML>
extra line required at end of the file

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_1/Assignment3.html
> +            <title>ASSIGNMENT3</title>
remove extra space

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_1/Assignment3.html
> +</HTML>
extra line required at end of the file

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_1/Assignment4.html
> +            <title>ASSIGNMENT4</title>
check indentation

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_1/Assignment4.html
> +
remove extra line

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_1/Assignment4.html
> +</HTML>
extra line required at end of the file

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_2/Assignment_2.html
> +                <pre><em>This article is about the company.</em></pre>
check indentation

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_2/Assignment_2.html
> +</html>
extra line required at end of the file

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_2/Assignment_2.html
> +                    <bold style="font-size: 32px;color: green">Thank You !!!</bold>
space required after each style property

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_3/NikitaA3_1.html
> +    <title>Document</title>
change title

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_3/NikitaA3_1.html
> +<head>
check indentation

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_3/NikitaA3_1.html
> +                <ol style="list-style: lower-roman;">
check indentation only 4 space required from parent tag

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_3/NikitaA3_1.html
> +
remove extra line

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_3/NikitaA3_1.html
> +               <ol style="list-style: lower-roman; ">
check indentation only 4 space required from parent tag

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_3/NikitaA3_1.html
> +                <li style="list-style-type:circle;">Anu</li>
space required after : in style

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_3/NikitaA3_1.html
> +                <li style="list-style-type:circle;">Dipti</li>
space required after : in style

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_3/NikitaA3_1.html
> +                <li style="list-style-type:circle;">Triveni</li>
space required after : in style

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_3/NikitaA3_1.html
> +                <li style="list-style-type:circle;">Kalyani</li>
space required after : in style

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_3/NikitaA3_1.html
> +
remove extra lines

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_3/NikitaA3_1.html
> +</html>
extra line required at the end of file

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_3/NikitaA3_2.html
> +<head>
check indentation

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_3/NikitaA3_2.html
> +    body{
space required before {

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_3/NikitaA3_2.html
> +    a:link{
space required before {

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_3/NikitaA3_2.html
> +    a:visited{
space required before {

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_3/NikitaA3_2.html
> +<body>
check indentation

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_3/NikitaA3_2.html
> +        <a href="MI-MEAN.html" >MI-MEAN </a> |
remove extra space

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_3/NikitaA3_2.html
> +</html>
extra line required at the end of file

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_1.html
> +
remove extra line

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_1.html
> +            background-color:rosybrown;
space required

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_1.html
> +            background-color:rosybrown;
space required

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_1.html
> +            padding :14px;
remove space before : and add after :

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_1.html
> +
remove extra lines

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_1.html
> +        <table style="width: 70%;">
check indentation only 4 spaces allowed from parent tag

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_1.html
> +            <caption>A test table with merged cells</caption>
check indentation

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_1.html
> +
remove extra line

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_2.html
> +<head>
check indentation

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_2.html
> +        table, th, td{
space required before {

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_2.html
> +        .a{
space required before {

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_2.html
> +        .b{
space required before {

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_2.html
> +        .c{
space required before {

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_2.html
> +<body style="margin: 50px 50px;">
check indentation

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_2.html
> +        <caption style="color:mediumpurple;"><h1>Jan's Spring Term Afternoon Schedule</h1></caption>
space required in style

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_2.html
> +
where is closing tags

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_3.html
> +<head>
check indentation

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_3.html
> +    <title>Document</title>
change title

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_3.html
> +        th, td{
space required before {

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_3.html
> +        .a{
space required before {

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_3.html
> +        .b{
space required before {

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_3.html
> +        .c{
space required before {

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_3.html
> +        .d{
space required before {

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_3.html
> +
remove extra line

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_3.html
> +
remove extra line

2021-04-21 10:19 UTC, KomalShinde813 commented on Nikita/Assignment_4/NikitaA4_3.html
> +
remove extra line

2021-04-23 06:57 UTC, merged