modified Assignment 1,2,3,4
Pawan1005/MI-11-MEAN pull request #210
Opened 2021-04-19 14:30 UTC by Jestinxavier

2021-04-20 06:55 UTC, mubeen2710 approved these changes

2021-04-21 06:11 UTC, Richa199 approved these changes

2021-04-24 11:25 UTC, Pawan1005 requested changes

2021-04-24 11:25 UTC, Pawan1005 commented on Jestin/HTML/Assignment4/ass4q2.html
> +    </body>
add new line at the end of file

2021-04-24 11:25 UTC, Pawan1005 commented on Jestin/HTML/Assignment4/ass4q3.html
> +    </body>
add new line at the end of file

2021-04-24 11:25 UTC, Pawan1005 commented on Jestin/HTML/Assignment3/new (copy).html
> +</html>
add new line at the end of file

2021-04-24 11:25 UTC, Pawan1005 commented on Jestin/HTML/Assignment4/ass4q1.html
>  </html>
add new line at the end of file

2021-04-24 12:36 UTC, Pawan1005 requested changes

2021-04-24 12:36 UTC, Pawan1005 commented on Jestin/HTML/Assignment4/ass4q1.html
>  </html>
add new line

2021-04-24 12:36 UTC, Pawan1005 commented on Jestin/HTML/Assignment4/ass4q2.html
>  </html>
add new line at the end of file

2021-04-24 12:36 UTC, Pawan1005 commented on Jestin/HTML/Assignment4/ass4q3.html
>  </html>
add new line at the end of file

2021-04-25 04:06 UTC, Pawan1005 requested changes

2021-04-25 04:06 UTC, Pawan1005 commented on Jestin/HTML/Assignment3/assig q1.html
> +    <body>
head tag is missing

2021-04-25 04:06 UTC, Pawan1005 commented on Jestin/HTML/Assignment3/mi11.html
> +
remove extra lines

2021-04-25 04:06 UTC, Pawan1005 commented on Jestin/HTML/Assignment3/new (copy).html
> +
remove extra lines

2021-04-25 04:06 UTC, Pawan1005 commented on Jestin/HTML/Assignment4/ass4q2.html
> +            <table style="width: 100%;" border="20" cellpadding="23">
to much space

2021-04-25 07:59 UTC, Pawan1005 approved these changes

2021-04-25 08:11 UTC, merged