Assignment 1,2,3,4 added
Pawan1005/MI-11-MEAN pull request #211
Opened 2021-04-19 18:42 UTC by yogesh545

Indentation applied

2021-04-21 06:10 UTC, Richa199 approved these changes

2021-04-21 11:16 UTC, Jestinxavier approved these changes

2021-04-22 17:04 UTC, mubeen2710 approved these changes

2021-04-26 06:44 UTC, KomalShinde813 requested changes

2021-04-26 06:44 UTC, KomalShinde813 commented on yogesh_khande/html/asgn1/Intro1.html
> +    <title>Question1</title>
change title, title should be related to program

2021-04-26 06:44 UTC, KomalShinde813 commented on yogesh_khande/html/asgn1/Intro2.html
> +    <title>Question2</title>
change title, title should be related to program

2021-04-26 06:44 UTC, KomalShinde813 commented on yogesh_khande/html/asgn1/Intro3.html
> +    <title>assignment3</title>
change title, title should be related to program

2021-04-26 06:44 UTC, KomalShinde813 commented on yogesh_khande/html/asgn1/Myinfo.html
> +    <title>assignment4</title>
change title, title should be related to program

2021-04-26 06:44 UTC, KomalShinde813 commented on yogesh_khande/html/assignment3/Home.html
> +      <div class="contaner" style="display:flex;">
space required after : in style

2021-04-26 06:44 UTC, KomalShinde813 commented on yogesh_khande/html/assignment3/Home.html
> +      <img src="https://t4.ftcdn.net/jpg/02/71/22/77/360_F_271227781_gt3nHI7H3CgUENSbM3V14x2QhPB04Glb.jpg"  style="float: left" width="70%" margin:50px padding-left:50px>
space required after : in style

2021-04-26 06:44 UTC, KomalShinde813 commented on yogesh_khande/html/assignment3/Home.html
> +      <img src="https://t4.ftcdn.net/jpg/02/71/22/77/360_F_271227781_gt3nHI7H3CgUENSbM3V14x2QhPB04Glb.jpg"  style="float: left" width="70%" margin:50px padding-left:50px>
remove extra space which is present before style

2021-04-26 06:44 UTC, KomalShinde813 commented on yogesh_khande/html/assignment3/Home.html
> +      style="float: right;"width=70% margin:50px>
space required after : and each attribute in style

2021-04-26 06:44 UTC, KomalShinde813 commented on yogesh_khande/html/assignment3/Home.html
> +        <h1>MI-11-MEAN</h1>
indentation is not proper

2021-04-26 06:44 UTC, KomalShinde813 commented on yogesh_khande/html/assignment3/Home.html
> +        <strong>
check indentation properly

2021-04-26 06:44 UTC, KomalShinde813 commented on yogesh_khande/html/assignment3/Home.html
> +        style="float: left;" width="25%" margin:50px>
space required after : in style

2021-04-26 06:44 UTC, KomalShinde813 commented on yogesh_khande/html/assignment3/Home.html
>  </html>
extra line required at the end of file

2021-04-26 06:44 UTC, KomalShinde813 commented on yogesh_khande/html/assignment4/Table1.html
>      <title>Question1</title>
change title, title should be related to program

2021-04-26 06:44 UTC, KomalShinde813 commented on yogesh_khande/html/assignment4/Table2.html
> +    <title>table2</title>
change title

2021-04-26 06:44 UTC, KomalShinde813 commented on yogesh_khande/html/assignment4/Table2.html
> +          >Jan's spring term afternoon schedule</strong
closing tag should be at above line and </strong> at below this line

2021-04-26 09:16 UTC, KomalShinde813 requested changes

2021-04-26 09:16 UTC, KomalShinde813 commented on yogesh_khande/html/assignment3/Home.html
> +      <img src="https://t4.ftcdn.net/jpg/02/71/22/77/360_F_271227781_gt3nHI7H3CgUENSbM3V14x2QhPB04Glb.jpg"  style="float: left" width="70%" margin:50px padding-left:50px>
need to this change  space required after : in style

2021-04-26 09:16 UTC, KomalShinde813 commented on yogesh_khande/html/assignment3/Home.html
> +      margin:50px>
space required after : in style

2021-04-26 09:16 UTC, KomalShinde813 commented on yogesh_khande/html/assignment3/Home.html
> +        margin:50px>
space required after : in style

2021-04-26 09:16 UTC, KomalShinde813 commented on yogesh_khande/html/assignment3/Home.html
> +       </strong>
check indentation

2021-04-26 09:16 UTC, KomalShinde813 commented on yogesh_khande/html/assignment3/Home.html
> +       <center><h1 id="MI-11-MEAN">MI-11-MEAN</h1></center>
check indentation

2021-04-27 08:38 UTC, KomalShinde813 approved these changes

2021-04-27 08:40 UTC, merged