Urmila12
Pawan1005/MI-11-MEAN pull request #213
Opened 2021-04-20 07:58 UTC by urmilagagare

2021-04-20 08:30 UTC, nileshp1122 approved these changes

2021-04-20 08:58 UTC, shubhamdalal49 approved these changes

2021-04-20 10:49 UTC, vijaya1811 approved these changes

2021-04-21 08:00 UTC, Ashwin2812 approved these changes

2021-04-21 13:02 UTC, Pawan1005 requested changes
check as per comments

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment1/Q1.html
> +
indentation mistake

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment1/Q3.html
> +  <head>
make sure to use correct tags in file

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment1/Q3.html
> +  <head>
indentation mistaks

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment1/Q4.html
> +
remove extra lines and make sure to make proper indentation in your files

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment2/Q1.html
> +</html>
add new line at the end of file and same indentation mistake

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment3/Q1.html
> +    <body>
head tag end missing

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment3/Q1.html
> +</body>
ending html tag is missing and indentation is wrong

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment3/Q2.html
> +  <head>
html tag is missing

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment3/Q2.html
> +</style>
2 style closing

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment3/Q2.html
> +    <br />
no need to give that slash

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment3/Q2.html
> +  <br />
remove slash

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment3/Q2.html
> +</html> <!<!DOCTYPE html>
what is 2 nd html file in same file

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment3/Q2.html
> +  <head>
2nd html tag is missing

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment3/Q2.html
> +</head>
2 head tags

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment3/Q2.html
> +<!DOCTYPE html>
3rd html page make 3 different pages

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment3/Q2.html
> +
indentation missing

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment4/Q1.html
> +</html>
indentation missing 
add new line at the end of file

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment4/Q2.html
> +            border-top: transparent;
give proper names to class

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment4/Q2.html
> +</body>
2 body tag closing 
make proper indentation

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment4/Q2.html
> +</html>
add new line at the end of file

2021-04-21 13:02 UTC, Pawan1005 commented on urmila/HTML/Assignment4/Q3.html
> +</html>
give proper class names 
make indentation for head and body tag
add new line at the end of file

2021-04-23 07:14 UTC, merged