Vijaya1
Pawan1005/MI-11-MEAN pull request #216
Opened 2021-04-20 13:23 UTC by vijaya1811

2021-04-20 14:18 UTC, shubhamdalal49 requested changes

2021-04-20 14:18 UTC, shubhamdalal49 commented on vijaya/html/assignment3/contact.html
> +
Remove this extra space

2021-04-20 14:18 UTC, shubhamdalal49 commented on vijaya/html/assignment3/index.html
> +     </p>
correct indentation

2021-04-20 14:18 UTC, shubhamdalal49 commented on vijaya/html/assignment3/mean.html
> +</style>
style tag should be in head tag. please change it and put it in head tag

2021-04-20 14:18 UTC, shubhamdalal49 commented on vijaya/html/assignment3/question1.html
> +</style>
Style tag should be in head tag

2021-04-20 14:18 UTC, shubhamdalal49 commented on vijaya/html/assignment4/question1.html
> +</style>
style should be in  head tag

2021-04-20 14:18 UTC, shubhamdalal49 commented on vijaya/html/assignment4/question1.html
> +</tr>
your code should be in proper format

2021-04-21 05:01 UTC, nileshp1122 commented on vijaya/html/assignment3/contact.html
> +
remove extra space

2021-04-21 05:03 UTC, Ashwin2812 approved these changes

2021-04-21 08:32 UTC, Ashwin2812 approved these changes

2021-04-21 08:40 UTC, nileshp1122 approved these changes

2021-04-21 08:57 UTC, shubhamdalal49 approved these changes

2021-04-21 16:28 UTC, Ashwin2812 approved these changes

2021-04-21 17:59 UTC, urmilagagare approved these changes

2021-04-22 08:01 UTC, merged