Folder Added: HTML Assignments(1,2,3,4)
Pawan1005/MI-11-MEAN pull request #217
Opened 2021-04-21 11:15 UTC by anuja1603

2021-04-21 11:33 UTC, Amit727619 approved these changes

2021-04-21 11:46 UTC, pooja-nagare approved these changes

2021-04-21 12:01 UTC, pritikekan approved these changes

2021-04-21 12:25 UTC, shivani-pawbake approved these changes

2021-04-22 06:14 UTC, Priyankashelke2411 requested changes
Why you added script file in assignments1 please remove it.

2021-04-22 07:48 UTC, anuja1603 commented
> Why you added script file in assignments1 please remove it.

> Please check it. I removed that line.

2021-04-22 09:25 UTC, Priyankashelke2411 approved these changes

2021-04-22 09:41 UTC, Priyankashelke2411 requested changes
remove extra lines

2021-04-22 13:00 UTC, Priyankashelke2411 requested changes

2021-04-22 13:00 UTC, Priyankashelke2411 commented on Anuja/HTML/ASSN1/Que1.html
> +    <script src='main.js'></script>
remove script file

2021-04-23 06:30 UTC, anuja1603 commented on Anuja/HTML/ASSN1/Que1.html
> +    <script src='main.js'></script>
Mam I have removed that.

2021-04-26 07:43 UTC, Priyankashelke2411 approved these changes

2021-04-26 07:43 UTC, Priyankashelke2411 commented on Anuja/HTML/ASSN3/MI-MEAN.html
> +
remove extra line here

2021-04-26 07:43 UTC, Priyankashelke2411 commented on Anuja/HTML/ASSN3/Contact-Us.html
> +
remove extra line

2021-04-26 08:31 UTC, JafarPathan commented on Anuja/HTML/ASSN1/Que1.html
> +</html>
check indentation

2021-04-26 08:31 UTC, JafarPathan commented on Anuja/HTML/ASSN1/Que1.html
> +</html>
add empty newline at end of file

2021-04-26 08:31 UTC, JafarPathan commented on Anuja/HTML/ASSN1/Que2.html
> +</html>
add empty newline at end of file

2021-04-26 08:31 UTC, JafarPathan commented on Anuja/HTML/ASSN1/Que2.html
> +</html>
check indentation

2021-04-26 08:32 UTC, JafarPathan commented on Anuja/HTML/ASSN1/Que3.html
> +</html>
add empty newline at end of file

2021-04-26 08:32 UTC, JafarPathan commented on Anuja/HTML/ASSN1/Que3.html
> +</html>
check indent

2021-04-26 08:32 UTC, JafarPathan commented on Anuja/HTML/ASSN1/Que4.html
> +
remove unwanted lines

2021-04-26 08:33 UTC, JafarPathan commented on Anuja/HTML/ASSN1/Que4.html
> +</html>
check indentation

2021-04-26 08:34 UTC, JafarPathan commented on Anuja/HTML/ASSN2/Que1.html
> +</html>
add empty newline at end of file

2021-04-26 08:34 UTC, JafarPathan commented on Anuja/HTML/ASSN2/Que1.html
> +</html>
check indentation

2021-04-26 08:35 UTC, JafarPathan commented on Anuja/HTML/ASSN3/Contact-Us.html
> +</html>
remove unwanted lines and check indentation

2021-04-26 08:35 UTC, JafarPathan commented on Anuja/HTML/ASSN3/MI-MEAN.html
> +</html>
add empty newline at end of file

2021-04-26 08:36 UTC, JafarPathan commented on Anuja/HTML/ASSN3/MI-MEAN.html
> +</html>
remove unwanted lines and check indentation

2021-04-26 08:36 UTC, JafarPathan commented on Anuja/HTML/ASSN3/Que1.html
> +</html>
add empty newline at end of file

2021-04-26 08:37 UTC, JafarPathan commented on Anuja/HTML/ASSN3/Que1.html
> +</html>
remove unwanted lines and check indentation

2021-04-26 08:38 UTC, JafarPathan commented on Anuja/HTML/ASSN3/Que2.html
> +</html>
check indentation

2021-04-26 08:38 UTC, JafarPathan commented on Anuja/HTML/ASSN4/Que1.html
> +</html>
remove unwanted lines and check indentation

2021-04-26 08:38 UTC, JafarPathan commented on Anuja/HTML/ASSN4/Que1.html
> +</html>
add empty newline at end of file

2021-04-26 08:38 UTC, JafarPathan commented on Anuja/HTML/ASSN4/Que2.html
> +</html>
add empty newline at end of file

2021-04-26 08:39 UTC, JafarPathan commented on Anuja/HTML/ASSN4/Que2.html
> +</html>
remove unwanted lines and check indentation

2021-04-26 08:39 UTC, JafarPathan commented on Anuja/HTML/ASSN4/Que3.html
> +</html>
remove unwanted lines and check indentation

2021-04-26 08:40 UTC, JafarPathan commented on Anuja/HTML/ASSN4/Que3.html
> +</html>
add empty newline at end of file

2021-04-26 11:07 UTC, JafarPathan approved these changes

2021-04-26 12:40 UTC, merged