Changes Done
Pawan1005/MI-11-MEAN pull request #224
Opened 2021-04-23 15:03 UTC by yogesh141293

2021-04-23 16:19 UTC, Oshin-250197 approved these changes

2021-04-24 06:56 UTC, SamikshaWani approved these changes

2021-04-24 13:54 UTC, Pawan1005 requested changes
need indentation
remove extra line  
put style tag in head tag in every file

2021-04-24 13:54 UTC, Pawan1005 commented on Yogesh/HTML/Assig.1/Que1.html
> +</html>
need indentation
add new line at the end of file

2021-04-24 13:54 UTC, Pawan1005 commented on Yogesh/HTML/Assig.1/Que3.html
> +</html>
need indentation
add new line at the end of file

2021-04-24 13:54 UTC, Pawan1005 commented on Yogesh/HTML/Assig.1/Que4.html
> +</style>
this needs to be in head tag

2021-04-24 13:54 UTC, Pawan1005 commented on Yogesh/HTML/Assig.1/Que4.html
> +</html>
need indentation
add new line at the end of file

2021-04-24 13:54 UTC, Pawan1005 commented on Yogesh_Ghodmare/HTML/Assig.1/Que1.html
> +
remove extra line

2021-04-24 13:54 UTC, Pawan1005 commented on Yogesh_Ghodmare/HTML/Assig.1/Que1.html
> +</html>
need indentation

2021-04-24 13:54 UTC, Pawan1005 commented on Yogesh_Ghodmare/HTML/Assig.1/Que2.html
> +</html>
need indentation
remove extra line

2021-04-24 13:54 UTC, Pawan1005 commented on Yogesh_Ghodmare/HTML/Assig.1/Que3.html
> +</html>
need indentation
remove extra line

2021-04-24 13:54 UTC, Pawan1005 commented on Yogesh_Ghodmare/HTML/Assig.1/Que4.html
> +
this needs to be head tag

2021-04-24 13:54 UTC, Pawan1005 commented on Yogesh_Ghodmare/HTML/Assig.1/Que4.html
> +</html>
need indentation
remove extra line

2021-04-24 13:54 UTC, Pawan1005 commented on Yogesh_Ghodmare/HTML/Assig2/.vscode/settings.json
> +}
remove this file

2021-04-24 13:54 UTC, Pawan1005 commented on Yogesh_Ghodmare/HTML/Assig2/Que.1.html
> +
this needs to be in head tag

2021-04-24 13:54 UTC, Pawan1005 commented on Yogesh_Ghodmare/HTML/Assig2/Que.1.html
> +</html>
need indentation
remove extra line

2021-04-27 05:35 UTC, Pawan1005 approved these changes

2021-04-27 05:40 UTC, merged