Vinit work
Pawan1005/MI-11-MEAN pull request #226
Opened 2021-04-23 16:23 UTC by vdongre304

2021-04-24 06:27 UTC, Jestinxavier approved these changes

2021-04-25 11:45 UTC, yogesh545 approved these changes

2021-04-26 06:20 UTC, KomalShinde813 requested changes

2021-04-26 06:20 UTC, KomalShinde813 commented on vinitD/html/asgnmnt1/assign1.html
> +    <title>Document</title>
change title title should be related to program

2021-04-26 06:20 UTC, KomalShinde813 commented on vinitD/html/asgnmnt1/assign2.html
> +    <title>Document</title>
change title title should be related to program

2021-04-26 06:20 UTC, KomalShinde813 commented on vinitD/html/asgnmnt1/assign3.html
> +    <title>Document</title>
change title title should be related to program

2021-04-26 06:20 UTC, KomalShinde813 commented on vinitD/html/asgnmnt1/assign4.html
> +    <title>Document</title>
change title title should be related to program

2021-04-26 06:20 UTC, KomalShinde813 commented on vinitD/html/asgnmnt4/Table2.html
> +          >Jan's spring term afternoon schedule</strong
> tag should close at above line and </strong> should at below line

2021-04-26 06:20 UTC, KomalShinde813 commented on vinitD/html/asgnmnt4/Table2.html
> +
remove this extra line

2021-04-26 07:30 UTC, KomalShinde813 approved these changes

2021-04-26 08:11 UTC, merged