Shubham dalal work
Pawan1005/MI-11-MEAN pull request #228
Opened 2021-04-26 10:07 UTC by shubhamdalal49

2021-04-26 10:28 UTC, Ashwin2812 approved these changes

2021-04-26 11:29 UTC, Pawan1005 requested changes
check tab setting we need 4 space only your files contain 7-8 spaces

2021-04-26 11:29 UTC, Pawan1005 commented on Shubham_Dalal/HTML/ASSIGNMENT1/shubhamforth.html
>          </body>
check indentation

2021-04-26 14:21 UTC, nileshp1122 reviewed
check indentation

2021-04-28 16:32 UTC, nileshp1122 approved these changes

2021-04-28 16:32 UTC, nileshp1122 commented on Shubham_Dalal/HTML/ASSIGNMENT1/shubhamforth.html
> +</html>
check indentation

2021-04-28 16:33 UTC, nileshp1122 approved these changes

2021-04-28 16:34 UTC, nileshp1122 approved these changes

2021-04-29 03:38 UTC, Pawan1005 approved these changes

2021-04-29 05:49 UTC, SnehaMakade commented on Shubham_Dalal/HTML/ASSIGNMENT2/shubham_style.html
> +        <center>
dont use center tag instead use text-align: center property

2021-04-29 05:50 UTC, SnehaMakade commented on Shubham_Dalal/HTML/ASSIGNMENT2/shubham_style.html
> +        <center style="color: slategrey; font-size: 25px">Thankyou!</center>
dont use center tag insted use text-align: center property

2021-04-29 05:50 UTC, SnehaMakade commented on Shubham_Dalal/HTML/ASSIGNMENT3/shubham_contactus.html
> +    <body style="text-align: center; background: rgb(71, 99, 22)">
check indentation regarding spaces

2021-04-29 05:53 UTC, SnehaMakade commented on Shubham_Dalal/HTML/ASSIGNMENT4/Shubham_table1.html
> +            table,
include table, th, tr, td {} like this on same line

2021-04-29 05:53 UTC, SnehaMakade commented on Shubham_Dalal/HTML/ASSIGNMENT4/shubham_table2.html
> +            table,
include all tag names in a single line

2021-04-29 05:54 UTC, SnehaMakade commented on Shubham_Dalal/HTML/ASSIGNMENT4/shubham_table2.html
> +            th,
include th and td in a single line and add space after comma always

2021-04-29 05:54 UTC, SnehaMakade commented on Shubham_Dalal/HTML/ASSIGNMENT4/shubham_table3.html
> +            table,
include all tags in a single line

2021-04-29 05:55 UTC, SnehaMakade commented on Shubham_Dalal/HTML/ASSIGNMENT4/shubham_table3.html
> +            th,
include th, td {} in a single line

2021-04-29 05:55 UTC, SnehaMakade requested changes
do changes as per comments given

2021-04-29 07:40 UTC, SnehaMakade commented on Shubham_Dalal/HTML/ASSIGNMENT4/Shubham_table1.html
> +            tr,
do the change in this file also

2021-04-29 07:41 UTC, SnehaMakade requested changes
do change proper

2021-04-29 08:38 UTC, SnehaMakade approved these changes

2021-04-29 08:43 UTC, merged