File Added : Changes Done
Pawan1005/MI-11-MEAN pull request #231
Opened 2021-04-26 12:14 UTC by kalyani1942

2021-04-26 12:53 UTC, SnehaMakade commented on Kalyani/HTML/Assginment1/Assin.html
>  </html>
add new end line in all files.

2021-04-26 12:54 UTC, SnehaMakade commented on Kalyani/HTML/Assginment1/Assin.html
> +	    </p>
close the <p> tag on the same line

2021-04-26 12:55 UTC, SnehaMakade commented on Kalyani/HTML/Assginment1/Assin2.html
>  </html>
add extra new line always in each file after </html>

2021-04-26 17:46 UTC, SnehaMakade commented on Kalyani/HTML/Assginment1/Assin4.html
> +	        <i><h2 style="color: red">I am Kalyani Deshpande</h2></i><br />I am a Software Enginner.
<i> is inline element and <h2> is block level element u can not include block level elements inside inline element.so do the opposite of what u have done here

2021-04-26 17:49 UTC, SnehaMakade commented on Kalyani/HTML/Assginment1/Assin4.html
> +</html>
add a end line in each file

2021-04-26 17:50 UTC, SnehaMakade commented on Kalyani/HTML/Assginment3/KalyaniA3_1.html
>  </html>
add new end line

2021-04-26 17:51 UTC, SnehaMakade commented on Kalyani/HTML/Assginment3/KalyaniA3_2contact.html
>  </html>
add new end line

2021-04-26 17:52 UTC, SnehaMakade commented on Kalyani/HTML/Assignment2/A2.html
> +        <center>
dont use center tag instead use style text-align: center property on <h1> tag.

2021-04-26 17:53 UTC, SnehaMakade commented on Kalyani/HTML/Assignment2/A2.html
> +        <h2 style="font-size: 40" ;>his article is about the company.</h2>
remove the extra space before semicolon

2021-04-26 17:54 UTC, SnehaMakade commented on Kalyani/HTML/Assignment2/A2.html
> +        <center style="color: slategrey; font-size: 25px">Thankyou!</center>
dont use center tag instead use text-align: center property

2021-04-26 17:55 UTC, SnehaMakade commented on Kalyani/HTML/Assignment4/KalyaniA4_1.html
> +            table,
dont split table th td in different lines write it as like table, th, td {style u want to apply}.

2021-04-26 17:57 UTC, SnehaMakade commented on Kalyani/HTML/Assignment4/KalyaniA4_2.html
> +            table,
include tableth and td in a single line.

2021-04-26 17:57 UTC, SnehaMakade commented on Kalyani/HTML/Assignment4/KalyaniA4_3.html
> +            table,
include all tags in a single line

2021-04-26 17:58 UTC, SnehaMakade commented on Kalyani/HTML/Assignment4/KalyaniA4_3.html
> +            </tr>
remove this extra tr tag

2021-04-26 17:59 UTC, SnehaMakade requested changes
do the changes as per comments given and extra new line at end in each file

2021-04-27 07:48 UTC, SnehaMakade commented on Kalyani/HTML/Assignment4/KalyaniA4_1.html
> +            table,th,td {
add space after comma

2021-04-27 07:48 UTC, SnehaMakade commented on Kalyani/HTML/Assignment4/KalyaniA4_2.html
> +            table,th,td {
add a space after comma

2021-04-27 07:51 UTC, SnehaMakade commented on Kalyani/HTML/Assignment4/KalyaniA4_3.html
> +            table,th,td {
add a space after comma always in all files

2021-04-27 07:52 UTC, SnehaMakade requested changes
do changes as per comments given

2021-04-27 09:54 UTC, SnehaMakade approved these changes

2021-04-27 10:12 UTC, Pawan1005 requested changes

2021-04-27 10:12 UTC, Pawan1005 commented on Kalyani/HTML/Assginment3/KalyaniA3_2main.html
> +    <head>
html tag is missing here

2021-04-27 16:53 UTC, Pawan1005 approved these changes

2021-04-28 08:48 UTC, merged