File Added : Uploaded file changes
Pawan1005/MI-11-MEAN pull request #233
Opened 2021-04-27 08:39 UTC by SnehalAhir

2021-04-27 08:56 UTC, SamikshaWani approved these changes

2021-04-28 09:22 UTC, arshad05786 approved these changes

2021-04-28 11:18 UTC, Pawan1005 approved these changes

2021-04-28 11:25 UTC, KomalShinde813 requested changes

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment 5/aboutself.html
> +            <i><h1 class="heading1">Aboutme</h1></i>
check indentation

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment 5/aboutself.html
> +            <p class="p1">
check indentation

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment 5/aboutself.html
> +</html>
add extra line space after </html>

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment 5/effect.css
> +header{
space required before curly bracket

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment 5/effect.css
> +    height:100%; width:100%;
space required after :

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment 5/effect.css
> +nav{
space required before curly bracket

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment 5/effect.css
> +nav ul{
space required before curly bracket

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment 5/effect.css
> +.divmain{
space required before curly bracket

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment 5/effect.css
> +.pl{
space required before curly bracket

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment 5/effect.css
> +.div2{
space required before curly bracket

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment 5/effect.css
> +}
add one line space at the end of file

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment3/assinment_4.html
> +|
only one line space required at the end of file

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment4/Third.html
> +        <title>Document</title>
change title, title should be related to program

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment4/first.html
> +        <title>Assignment1</title>
change title in every file

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment5/aboutself.html
> +            <i><h1 class="heading1">Aboutme</h1></i>
check indentation

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment5/aboutself.html
> +            <p class="p1">
check indentation

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment5/aboutself.html
> +</html>
add one line space at the end of file

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment5/effect.css
> +header{
space required before curly bracket

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment5/effect.css
> +    height:100%; width:100%;
space required after :

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment5/effect.css
> +nav{
space required before curly bracket

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment5/effect.css
> +nav ul{
space required before curly bracket

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment5/effect.css
> +.divmain{
space required before curly bracket

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment5/effect.css
> +.pl{
space required before curly bracket

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment5/effect.css
> +.div2{
space required before curly bracket

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment5/effect.css
> +}
one line space required at the end of file

2021-04-28 11:25 UTC, KomalShinde813 commented on Snehal/HTML/Assignment5/effect.css
> +    vertical-align:bottom;
space required after :

2021-05-05 07:56 UTC, SamikshaWani commented on Snehal/HTML/Assignment4/Second.html
>                  border-top: 2px solid grey;
give proper name to class not a ,b,c

2021-05-05 09:07 UTC, closed without merging