File Added : Assignment6
Pawan1005/MI-11-MEAN pull request #256
Opened 2021-04-30 13:35 UTC by kalyani1942

2021-04-30 18:57 UTC, somesh6797 approved these changes

2021-05-02 12:13 UTC, somesh6797 approved these changes

2021-05-02 20:14 UTC, dayanandviveki commented on Kalyani/HTML/Assginment1/Assin.html
> +	    <title>AssignmentA1_1</title>
give proper title eg.Heading Tags instred of Assinment KalyaniA1

2021-05-02 20:16 UTC, dayanandviveki commented on Kalyani/HTML/Assginment1/Assin2.html
> +        <title>AssignmentA1_2</title>
Changes in title give topic name of something meaning full wording

2021-05-02 20:18 UTC, dayanandviveki commented on Kalyani/HTML/Assginment1/Assin4.html
> +	        <h2>Introduction</h2>
fot title tag don't need heading tag or h2 tag you can rrmove this tag

2021-05-02 20:20 UTC, dayanandviveki commented on Kalyani/HTML/Assginment3/KalyaniA3_1.html
> +            <h1>Assignment3_1</h1>
Inside title tag no need of heading tag or h1 tag

2021-05-02 20:22 UTC, dayanandviveki commented on Kalyani/HTML/Assignment6/Mi-11-Intern.html
> +
Remove Extra lines

2021-05-02 20:23 UTC, dayanandviveki commented on Kalyani/HTML/Assignment6/Mi-11-Intern.html
> +
chack code formmating  is in proper older

2021-05-02 20:26 UTC, dayanandviveki requested changes
Changes in all assignments title tag inside title tag no need of any heading tags and give proper heading as par assignment given topic and other chages also requred

2021-05-03 08:51 UTC, dayanandviveki approved these changes
No changes required

2021-05-04 07:58 UTC, shivnanda6272 requested changes
do proper indentation

2021-05-04 07:58 UTC, shivnanda6272 commented on Kalyani/HTML/Assignment6/Mi-11-Intern.html
> +</html>
do proper indentation, remove extra lines and add new end line.

2021-05-04 07:58 UTC, shivnanda6272 commented on Kalyani/HTML/Assignment6/Mi-11style.css
> +}
add extra line

2021-05-04 13:32 UTC, SnehaMakade commented on Kalyani/HTML/Assginment1/Assin4.html
> +	    <title>
u dont have to add h2 tag in title write title tag in a single line and remove h2 tag

2021-05-05 11:48 UTC, Pawan1005 requested changes

2021-05-05 11:48 UTC, Pawan1005 commented on Kalyani/HTML/Assignment6/Mi-11-Intern.html
> +                </select>
check indentation

2021-05-05 11:48 UTC, Pawan1005 commented on Kalyani/HTML/Assignment6/Mi-11-Intern.html
> +      </body>
check indentation

2021-05-05 11:48 UTC, Pawan1005 commented on Kalyani/HTML/Assignment5/style.css
> +    }
remove all extra spaces

2021-05-06 08:31 UTC, shivnanda6272 approved these changes

2021-05-07 07:39 UTC, SnehaMakade commented on Kalyani/HTML/Assignment5/style.css
> +    body {
remove extra space in file

2021-05-07 07:39 UTC, SnehaMakade commented on Kalyani/HTML/Assignment5/KalyaniA5_a.html
> +<html lang="en">
check the tab space it should be of four make this change in all files

2021-05-07 07:42 UTC, SnehaMakade requested changes
do changes as per comments given

2021-05-07 11:38 UTC, SnehaMakade commented on Kalyani/HTML/Assignment5/KalyaniA5_a.html
> +          <meta charset="UTF-8">
add four tab space

2021-05-07 11:39 UTC, SnehaMakade requested changes
check tab space in one file

2021-05-07 11:54 UTC, SnehaMakade commented on Kalyani/HTML/Assignment5/KalyaniA5_a.html
> +        <body>
indentation is not proper
and add four tab space only in complete file

2021-05-07 11:54 UTC, SnehaMakade requested changes
check tab space in one file

2021-05-07 12:02 UTC, SnehaMakade commented on Kalyani/HTML/Assignment5/KalyaniA5_a.html
> +			<head>
bad indentation

2021-05-07 12:02 UTC, SnehaMakade requested changes
make a proper indentation

2021-05-10 13:13 UTC, SnehaMakade approved these changes

2021-05-10 13:39 UTC, Pawan1005 requested changes
indentation missing

2021-05-10 13:39 UTC, Pawan1005 commented on Kalyani/HTML/Assignment6/Mi-11-Intern.html
> +        <head>
indentation missing

2021-05-10 13:39 UTC, Pawan1005 commented on Kalyani/HTML/Assignment6/Mi-11-Intern.html
> +        </body>
indentation missing

2021-05-11 04:38 UTC, Pawan1005 approved these changes

2021-05-11 04:39 UTC, merged