Folder Added : Assignment 5 and Assignment 6
Pawan1005/MI-11-MEAN pull request #261
Opened 2021-05-01 08:55 UTC by pritikekan

2021-05-03 06:15 UTC, pooja-nagare commented on priti/HTML/Assign.6/Q1.html
> +        <h1 style="background-color: rgb(185, 211, 238); text-align: right;">MI-9 Intern HTML Assesment</h1>
you are suppose to use external css not inline css

2021-05-03 06:19 UTC, pooja-nagare commented on priti/HTML/Assign.6/Q1.css
> +}
use
border-bottom-left-radius: 8px;
border-top-right-radius: 8px;

2021-05-03 08:47 UTC, Amit727619 approved these changes
good

2021-05-04 03:51 UTC, pooja-nagare approved these changes

2021-05-04 08:14 UTC, shivani-pawbake approved these changes

2021-05-04 10:52 UTC, jyoti-ing requested changes
add space in css file

2021-05-05 15:27 UTC, jyoti-ing approved these changes

2021-05-06 04:54 UTC, Pawan1005 requested changes

2021-05-06 04:54 UTC, Pawan1005 commented on priti/HTML/Assign.5/Q1.html
> +    <h1 style="color:rgb(240, 21, 68);border: 2px solid black;">PRITI KEKAN</h1>
body tag missing

2021-05-06 04:54 UTC, Pawan1005 commented on priti/HTML/Assign.6/Q1.html
> +        <h1  class="a">MI-11 Intern HTML Assesment</h1>
indentation missing

2021-05-06 04:54 UTC, Pawan1005 commented on priti/HTML/Assign.6/Q1.html
> +        <h2 class="a"<i>personal Detail</i></h2>
indentation missing

2021-05-06 04:54 UTC, Pawan1005 commented on priti/HTML/Assign.6/Q1.html
> +            </div>
indentation missing

2021-05-06 04:54 UTC, Pawan1005 commented on priti/HTML/Assign.6/Q1.html
> +            <form>
indentation missing

2021-05-06 04:54 UTC, Pawan1005 commented on priti/HTML/Assign.6/Q1.html
> +     <div>
stay focus 
where is closing of div tag

2021-05-08 07:29 UTC, Pawan1005 requested changes

2021-05-08 07:29 UTC, Pawan1005 commented on priti/HTML/Assign.5/Q1.html
> +    <h1 style="color:rgb(240, 21, 68);border: 2px solid black;">PRITI KEKAN</h1>
indentation missing

2021-05-08 07:29 UTC, Pawan1005 commented on priti/HTML/Assign.6/Q1.html
> +          </div>
indentation missing

2021-05-11 03:28 UTC, Pawan1005 approved these changes

2021-05-11 03:30 UTC, merged