Folder Added : Assignment 5 and Assignment 6
Pawan1005/MI-11-MEAN pull request #262
Opened 2021-05-01 09:51 UTC by Jestinxavier

2021-05-03 05:40 UTC, vdongre304 approved these changes

2021-05-04 11:28 UTC, mubeen2710 approved these changes

2021-05-06 04:57 UTC, Pawan1005 requested changes

2021-05-06 04:57 UTC, Pawan1005 commented on Jestin/HTML/Assignment5/home1.css
> +}
give proper names to class

2021-05-06 04:57 UTC, Pawan1005 commented on Jestin/HTML/Assignment5/home1.html
> +        <div class="a">
give proper names to class

2021-05-06 04:57 UTC, Pawan1005 commented on Jestin/HTML/Assignment5/home1.html
> +</html>
give proper names to class

2021-05-06 04:57 UTC, Pawan1005 commented on Jestin/HTML/Assignment6/Ass5q6.css
> +}
give proper names to class

2021-05-06 04:57 UTC, Pawan1005 commented on Jestin/HTML/Assignment6/Ass5q6.html
> +        </div>
no need of div tag here

2021-05-06 04:57 UTC, Pawan1005 commented on Jestin/HTML/Assignment6/Ass5q6.html
> +            <h4 class="b">personal Details</h4>
give proper names to class

2021-05-06 04:57 UTC, Pawan1005 commented on Jestin/HTML/Assignment6/Ass5q6.html
> +            <h4 class="b">Academic Details</h4>
give proper names to class

2021-05-11 03:38 UTC, Pawan1005 approved these changes

2021-05-11 04:32 UTC, merged