File added: online_book_store_documentation.pdf
Pawan1005/MI-11-MEAN pull request #265
Opened 2021-05-02 18:10 UTC by vijaya1811

2021-05-03 11:49 UTC, shubhamdalal49 approved these changes

2021-05-03 12:02 UTC, nileshp1122 approved these changes

2021-05-05 04:29 UTC, Ashwin2812 approved these changes

2021-05-05 04:32 UTC, urmilagagare approved these changes

2021-05-05 09:30 UTC, shubhamdalal49 requested changes

2021-05-05 09:30 UTC, shubhamdalal49 commented on vijaya/html/assignment6/assign6que2.html
> +                ><br />
check indentation in select tag

2021-05-05 09:56 UTC, shubhamdalal49 approved these changes

2021-05-06 05:02 UTC, Pawan1005 requested changes

2021-05-06 05:02 UTC, Pawan1005 commented on vijaya/html/assignment5/question1.css
> +}
add one space before {

2021-05-11 03:42 UTC, Pawan1005 approved these changes

2021-05-11 03:42 UTC, Pawan1005 commented on vijaya/html/assignment5/question1.css
> + }
add space before {

2021-05-11 03:42 UTC, Pawan1005 requested changes
add space before {

2021-05-12 07:04 UTC, Pawan1005 approved these changes

2021-05-12 14:01 UTC, merged