File addes : assignment 5 and 6 complited
Pawan1005/MI-11-MEAN pull request #266
Opened 2021-05-02 22:42 UTC by dayanandviveki

review my PR

2021-05-03 05:44 UTC, Phantom-Code requested changes
Fix Spelling mistakes in Pull Request title

2021-05-03 08:47 UTC, kalyani1942 requested changes, later dismissed

2021-05-03 08:47 UTC, kalyani1942 commented on Dayanand Viveki/HTML/Assignment5/Biodata.html
> +                <span class="info">
Remove Space

2021-05-03 08:58 UTC, dayanandviveki commented on Dayanand Viveki/HTML/Assignment5/Biodata.html
> +                <span class="info">
changes done

2021-05-03 08:58 UTC, dayanandviveki commented on Dayanand Viveki/HTML/Assignment5/Biodata.html
> +                <span class="info">
changes done

2021-05-03 09:13 UTC, Phantom-Code approved these changes

2021-05-03 15:09 UTC, Pawan1005 requested changes
add new line at the end of CSS files

2021-05-03 16:05 UTC, Prashant698 approved these changes

2021-05-04 05:11 UTC, somesh6797 approved these changes

2021-05-04 05:38 UTC, kalyani1942 approved these changes

2021-05-05 07:24 UTC, somesh6797 requested changes

2021-05-05 07:24 UTC, somesh6797 commented on Dayanand Viveki/HTML/Assignment6/assets/css/style.css
> +
remove this space

2021-05-05 11:45 UTC, Pawan1005 requested changes
add one space before {

2021-05-05 11:45 UTC, Pawan1005 commented on Dayanand Viveki/HTML/Assignment5/assets/css/style.css
> +}
add one space before {

2021-05-05 11:45 UTC, Pawan1005 commented on Dayanand Viveki/HTML/Assignment6/assets/css/style.css
> +}
add one space before {

2021-05-05 12:42 UTC, dayanandviveki commented on Dayanand Viveki/HTML/Assignment5/assets/css/style.css
> +}
ok sir

2021-05-05 13:10 UTC, closed without merging