File Added : Uploading asignment5 and 6
Pawan1005/MI-11-MEAN pull request #267
Opened 2021-05-03 05:52 UTC by arshad05786

2021-05-03 06:00 UTC, yogesh141293 commented on arshad_khan/html/asignment5/asignment5quest.html
> +</html>
Add extra line

2021-05-03 06:00 UTC, yogesh141293 commented on arshad_khan/html/asignment6/firstquest.html
> +</html>
Add Extra Line

2021-05-03 06:03 UTC, yogesh141293 reviewed
Add extra lines in all Assigments

2021-05-03 06:38 UTC, SamikshaWani approved these changes

2021-05-03 15:05 UTC, Oshin-250197 approved these changes

2021-05-03 15:09 UTC, roshnidurugwar approved these changes

2021-05-04 08:04 UTC, yogesh141293 approved these changes

2021-05-05 07:29 UTC, SamikshaWani commented on arshad_khan/html/asignment6/firstquest.html
>                  <label for="lname">Last Name <input type="text" placeholder="Last Name" /> </label><br /><br />
placeholders second word first letter should be small

2021-05-05 07:34 UTC, SamikshaWani commented on arshad_khan/html/asignment6/firstquest.html
>                      >Gender <input type="radio" name="gender" value="male" />Male <input type="radio" name="gender" value="female" />Female
check indentation

2021-05-05 07:34 UTC, SamikshaWani commented on arshad_khan/html/asignment6/firstquest.html
>                      >Age <input type="radio" name="age" value="lessthan18" />Less than 18 <input type="radio" name="age" value="18-25" />18-25
check indentation

2021-05-05 11:57 UTC, Pawan1005 requested changes

2021-05-05 11:57 UTC, Pawan1005 commented on arshad_khan/html/asignment5/asignment5quest.html
> +            </i>
use inside of h1 tag

2021-05-05 11:57 UTC, Pawan1005 commented on arshad_khan/html/asignment5/asignment5quest.html
> +                </i>
use inside of h2 tag

2021-05-08 07:31 UTC, Pawan1005 approved these changes

2021-05-08 08:50 UTC, merged