Assignment5 and assignment6
Pawan1005/MI-11-MEAN pull request #270
Opened 2021-05-03 06:12 UTC by vdongre304

2021-05-03 13:21 UTC, Jestinxavier approved these changes

2021-05-03 13:46 UTC, yogesh545 approved these changes

2021-05-06 08:36 UTC, KomalShinde813 requested changes

2021-05-06 08:36 UTC, KomalShinde813 commented on vinitD/html/asgnmnt6/formcontinue.html
> +            <select>
check indentation for select block

2021-05-06 08:36 UTC, KomalShinde813 commented on vinitD/html/asgnmnt6/formcontinue.html
> +                <tr>
check indentation here

2021-05-06 10:04 UTC, KomalShinde813 requested changes

2021-05-06 10:04 UTC, KomalShinde813 commented on vinitD/html/asgnmnt6/formcontinue.html
> +        <br><br>
this line should be exact below table tag

2021-05-06 10:04 UTC, KomalShinde813 commented on vinitD/html/asgnmnt6/formcontinue.html
> +        <div>
check this indentation according to above comment

2021-05-06 10:04 UTC, KomalShinde813 commented on vinitD/html/asgnmnt6/formcontinue.html
> +        <br><br>
check indentation here also

2021-05-06 12:40 UTC, KomalShinde813 requested changes

2021-05-06 12:40 UTC, KomalShinde813 commented on vinitD/html/asgnmnt6/formcontinue.html
> +        <div>
check indentation from this line div should be exact below of br tag

2021-05-07 06:49 UTC, KomalShinde813 approved these changes

2021-05-07 07:41 UTC, merged