Files added : Assignment 5,6
Pawan1005/MI-11-MEAN pull request #271
Opened 2021-05-03 06:47 UTC by SamikshaWani

2021-05-03 15:04 UTC, Oshin-250197 approved these changes

2021-05-03 15:07 UTC, roshnidurugwar approved these changes

2021-05-04 08:03 UTC, yogesh141293 approved these changes

2021-05-04 10:15 UTC, SnehaMakade commented on Samiksha/html/Assignment4/Assig4_2.html
> +            table,th,td {
add space after comma always

2021-05-04 10:16 UTC, SnehaMakade commented on Samiksha/html/Assignment4/Assign4_1.html
> +            table,th,td {
add space after comma

2021-05-04 10:17 UTC, SnehaMakade commented on Samiksha/html/Assignment4/Assign4_3.html
> +            table,th,td {
add space after comma

2021-05-04 10:17 UTC, SnehaMakade commented on Samiksha/html/Assignment4/Assign4_3.html
> +                border:1px solid black;
add space after colon always

2021-05-04 10:19 UTC, SnehaMakade commented on Samiksha/html/Assignment6/Assign6_1.html
> +            <input type="text" id="fname" name="fname" placeholder="First Name" /><br /><br />
placeholders second words 1st letter should be small make this change in all input boxes

2021-05-04 10:20 UTC, SnehaMakade requested changes
make the changes as per comments given

2021-05-05 09:30 UTC, SnehaMakade approved these changes

2021-05-10 11:18 UTC, merged