Assignment 5 Uploaded
Pawan1005/MI-11-MEAN pull request #272
Opened 2021-05-03 06:58 UTC by Bhavika222

ok

2021-05-03 16:23 UTC, Pranjali1999 requested changes

2021-05-03 16:23 UTC, Pranjali1999 commented on Bhavika/html/Assignment5/5ASS.html
> +    <body>
body is exact below the closing head tag.

2021-05-03 16:23 UTC, Pranjali1999 commented on Bhavika/html/Assignment5/5ASS.html
> +</head>
Head is already closed at line number 40, why did you close again?
& give proper title name.

2021-05-03 16:23 UTC, Pranjali1999 commented on Bhavika/html/Assignment5/5ASS.html
> +                 As a fresher I am interested in learning new things.But I am waiting fo an opportunity to implement them in a pratical way.
All line of paragraph should be starting from same point.

2021-05-03 16:23 UTC, Pranjali1999 commented on Bhavika/html/Assignment6/Ass6.html
> +        <label for="other">other</label><br /><br />
Why did you use the br tag twice?

2021-05-04 10:29 UTC, Priyankashelke2411 requested changes

2021-05-04 10:29 UTC, Priyankashelke2411 commented on Bhavika/html/Assignment5/Assig5.html
> +    <body>
give proper indentations

2021-05-04 11:21 UTC, Bhavika222 commented on Bhavika/html/Assignment5/Assig5.html
> +    <body>
Mam Plz check my new uploaded file.
 https://github.com/Pawan1005/MI-11-MEAN/pull/272/commits/6d81e6bd5a6e8b2b0b6254960918d3c6839075aa

2021-05-04 11:23 UTC, Bhavika222 reviewed
Mam Plz check my updated file.
https://github.com/Pawan1005/MI-11-MEAN/pull/272/commits/6d81e6bd5a6e8b2b0b6254960918d3c6839075aa

2021-05-05 05:17 UTC, Priyankashelke2411 approved these changes

2021-05-05 05:21 UTC, Priyankashelke2411 approved these changes

2021-05-05 06:18 UTC, Akash-ing approved these changes

2021-05-05 06:58 UTC, KomalShinde813 requested changes

2021-05-05 06:58 UTC, KomalShinde813 commented on Bhavika/html/Assignment6/Ass6.html
> +            h1 {
combine this in above h1 tag style

2021-05-05 06:58 UTC, KomalShinde813 commented on Bhavika/html/Assignment6/Ass6.html
> +            h2 {
combine this in above h2 tag style

2021-05-05 06:58 UTC, KomalShinde813 commented on Bhavika/html/Assignment6/Ass6.html
> +        <input type="radio" id="male" name="Gender" value="male" />
check this really working or not may be its selected male as well as other options too

2021-05-05 06:58 UTC, KomalShinde813 commented on Bhavika/html/Assignment6/Ass6.html
> +        <input type="radio" id="less than 18" name="less than 18" value="less than 18" />
name should be same in radio buttons otherwise we can choose multiple options

2021-05-05 06:58 UTC, vishnukopnar approved these changes

2021-05-05 09:17 UTC, Pranjali1999 reviewed
Give proper title name

2021-05-05 11:48 UTC, KomalShinde813 approved these changes

2021-05-05 16:11 UTC, Pranjali1999 approved these changes

2021-05-06 07:55 UTC, merged