New files added : Assignment5 & Assignment6
Pawan1005/MI-11-MEAN pull request #276
Opened 2021-05-03 08:45 UTC by Pranjali1999

2021-05-03 12:33 UTC, akash19972306 requested changes

2021-05-03 12:33 UTC, akash19972306 commented on Pranjali/HTML/Assi5/assi5.html
> +
remove the extra lines from this whole file

2021-05-03 12:33 UTC, akash19972306 commented on Pranjali/HTML/Assi6/assi6.html
> +            <label></label>
why you taken label...and there is nothing in that label remove it

2021-05-03 12:33 UTC, akash19972306 commented on Pranjali/HTML/Assi6/assi6.html
> +
remove extra lines

2021-05-03 12:33 UTC, akash19972306 commented on Pranjali/HTML/Assi6/assi6.html
> +        <h3 class="b" id="corners"><i>Personal Details</i></h3>
use <em> tag instead <i> tag. beacause <i> tag is outdated. and also use <strong> tag instead of <b> tag

2021-05-03 16:14 UTC, akash19972306 approved these changes

2021-05-04 05:50 UTC, vinod2406 approved these changes
ok

2021-05-04 16:12 UTC, vishnukopnar approved these changes

2021-05-05 06:02 UTC, Bhavika222 approved these changes

2021-05-05 06:18 UTC, Akash-ing approved these changes

2021-05-10 13:25 UTC, SnehaMakade commented on Pranjali/HTML/Assi6/assi6.html
> +            <input type="text" id="fname" name="firstname" placeholder="First Name" />
placeholder should be like First name so make this change in all input boxes

2021-05-10 13:25 UTC, SnehaMakade commented on Pranjali/HTML/Assi6/assi6_2.html
> +                    <label for="javascript"> Javascript</label>
remove all extra spaces

2021-05-10 13:26 UTC, SnehaMakade commented on Pranjali/HTML/Assi6/assign6.html
> +            <input type="text" id="fname" name="firstname" placeholder="First Name" />
change placeholder in all input boxes

2021-05-10 13:27 UTC, SnehaMakade requested changes
do changes as per comments given

2021-05-12 13:00 UTC, SnehaMakade commented on Pranjali/HTML/Assi5/assi5.html
> +            h1{
there should be space before paranthesis and class name like h1 {}, make this change everywhere

2021-05-12 13:02 UTC, SnehaMakade commented on Pranjali/HTML/Assi6/assi6.html
> +            <input type="text" id="firstname" name="firstname" placeholder="First Name" />
palceholders second words 1st letter should be small like First name make this change everywhere

2021-05-12 13:03 UTC, SnehaMakade commented on Pranjali/HTML/Assi6/assi6_2.html
> +                    <label for="javascript"> Javascript</label>
remove all extra space

2021-05-12 13:03 UTC, SnehaMakade commented on Pranjali/HTML/Assi6/assign6.html
> +            <input type="text" id="fname" name="firstname" placeholder="First Name" />
not done changes

2021-05-12 16:31 UTC, SnehaMakade requested changes
remove extra spaces and change placeholder names like First name in all input boxes

2021-05-13 06:49 UTC, SnehaMakade approved these changes

2021-05-13 06:58 UTC, merged