File Added : Assignment 5,6
Pawan1005/MI-11-MEAN pull request #278
Opened 2021-05-03 09:12 UTC by Oshin-250197

2021-05-03 10:24 UTC, SamikshaWani approved these changes

2021-05-03 15:03 UTC, roshnidurugwar approved these changes

2021-05-05 07:38 UTC, SamikshaWani commented on Oshin1/html/Assignment5/Home.html
> +                        <div class = "shadow" style="background-color:#b0c4de; background-size: cover; cover;width:96%;padding:7px;">
add space after colan

2021-05-05 07:41 UTC, SamikshaWani commented on Oshin1/html/Assignment6/Question1.html
> +        <input type="text" name="lname" id="last-name" placeholder="Last Name" />
placeholder second word first letter should be small

2021-05-05 12:03 UTC, Pawan1005 requested changes

2021-05-05 12:03 UTC, Pawan1005 commented on Oshin1/html/Assignment5/Home.css
> +li {list-style-type:square;color: blue;font-size: 25px;border: 1px;}
make correct indentation 
add one space before {

2021-05-05 12:03 UTC, Pawan1005 commented on Oshin1/html/Assignment5/Home.css
> +#maindiv div {
where is this ID present in your file

2021-05-05 12:03 UTC, Pawan1005 commented on Oshin1/html/Assignment5/Home.html
> +    <body>
make correct indentation

2021-05-05 12:03 UTC, Pawan1005 commented on Oshin1/html/Assignment5/Resume.html
> +        </div>
remove extra div
and correct indentation

2021-05-05 12:03 UTC, Pawan1005 commented on Oshin1/html/Assignment5/Resume.html
> +            </div>
remove extra div

2021-05-11 03:31 UTC, Pawan1005 approved these changes

2021-05-11 05:24 UTC, merged