File Added : Assignment 5 & 6
Pawan1005/MI-11-MEAN pull request #280
Opened 2021-05-03 09:18 UTC by roshnidurugwar

2021-05-03 15:03 UTC, Oshin-250197 approved these changes

2021-05-03 16:34 UTC, arshad05786 approved these changes

2021-05-04 04:28 UTC, SamikshaWani approved these changes

2021-05-05 05:27 UTC, Priyankashelke2411 requested changes

2021-05-05 05:27 UTC, Priyankashelke2411 commented on Roshni/html/Assignment5/Ass5-Q1.html
> +
remove extra line

2021-05-05 05:27 UTC, Priyankashelke2411 commented on Roshni/html/Assignment5/Photo.html
> +
remove extra line

2021-05-05 05:35 UTC, roshnidurugwar commented on Roshni/html/Assignment5/Ass5-Q1.html
> +
done maam

2021-05-05 05:36 UTC, roshnidurugwar commented on Roshni/html/Assignment5/Photo.html
> +
done maam

2021-05-11 11:33 UTC, KomalShinde813 requested changes

2021-05-11 11:33 UTC, KomalShinde813 commented on Roshni/html/Assignment5/Ass5-Q1.html
> +            <table id="table1">
check spaces may be 8 spaces are there before table tag

2021-05-11 11:33 UTC, KomalShinde813 commented on Roshni/html/Assignment5/Ass5-Q1.html
> +                            background-size: cover;width:96%;padding:7px;">
space required after ; and : in style

2021-05-11 16:19 UTC, roshnidurugwar commented on Roshni/html/Assignment5/Ass5-Q1.html
> +            <table id="table1">
done maam

2021-05-11 16:19 UTC, roshnidurugwar commented on Roshni/html/Assignment5/Ass5-Q1.html
> +                            background-size: cover;width:96%;padding:7px;">
done maam

2021-05-11 16:37 UTC, KomalShinde813 requested changes

2021-05-11 16:37 UTC, KomalShinde813 commented on Roshni/html/Assignment5/Ass5-Q1.html
> +                        <div>
check indentation here

2021-05-11 16:37 UTC, KomalShinde813 commented on Roshni/html/Assignment5/Ass5-Q1.html
> +                            <ul>
check indentation use prettier

2021-05-11 16:45 UTC, roshnidurugwar commented on Roshni/html/Assignment5/Ass5-Q1.html
> +                            <ul>
yes maam

2021-05-12 07:41 UTC, roshnidurugwar commented on Roshni/html/Assignment5/Ass5-Q1.html
> +                        <div>
Yes ma'am I did it

2021-05-12 12:08 UTC, KomalShinde813 approved these changes

2021-05-12 12:32 UTC, merged