File added : Assignment 5 and 6
Pawan1005/MI-11-MEAN pull request #281
Opened 2021-05-03 10:44 UTC by shivani-pawbake

2021-05-04 03:56 UTC, pooja-nagare commented on Shivani/HTML/assign6/first.html
> +            <input type="text" id="fname" name="fname" /><br /><br />
add value or placeholder for First Name

2021-05-04 03:57 UTC, pooja-nagare commented on Shivani/HTML/assign6/first.html
> +            <input type="text" id="lname" name="lname" /><br /><br />
add value or placeholder for Last Name

2021-05-04 07:37 UTC, shivnanda6272 requested changes
do changes.

2021-05-04 07:37 UTC, shivnanda6272 commented on Shivani/HTML/assign5/first.html
> +</html>
add new line.

2021-05-04 07:37 UTC, shivnanda6272 commented on Shivani/HTML/assign6/first.html
> +            ><br /><br />
correct the indentation

2021-05-04 07:37 UTC, shivnanda6272 commented on Shivani/HTML/assign6/first.html
> +</html>
add extra line

2021-05-05 04:41 UTC, pooja-nagare approved these changes

2021-05-05 05:20 UTC, shivnanda6272 requested changes
make changes.

2021-05-05 05:20 UTC, shivnanda6272 commented on Shivani/HTML/assign6/first.html
> +            <label for="skill set"></label><b>Skill Set:</b></label>
why you are closed <label > two time . do it proper...

2021-05-05 06:17 UTC, shivnanda6272 approved these changes

2021-05-05 07:17 UTC, pritikekan approved these changes

2021-05-05 09:35 UTC, SnehaMakade approved these changes

2021-05-05 11:36 UTC, merged