File Added : Assgn5 and Assgn6
Pawan1005/MI-11-MEAN pull request #282
Opened 2021-05-03 11:51 UTC by yogesh545

2021-05-03 13:27 UTC, Jestinxavier approved these changes

2021-05-04 09:53 UTC, Priyankashelke2411 approved these changes

2021-05-05 06:52 UTC, KomalShinde813 requested changes

2021-05-05 06:52 UTC, KomalShinde813 commented on yogesh_khande/html/assignment 5/website.html
> +            p {
duplicate style for p tag

2021-05-05 06:52 UTC, KomalShinde813 commented on yogesh_khande/html/assignment 5/website.html
> +            .solid {
duplicate style

2021-05-05 06:52 UTC, KomalShinde813 commented on yogesh_khande/html/assignment 5/website.html
> +                <a href="resume.html" target="_blank">My Resume</a><br/>
where is html files which are mentioned in href

2021-05-05 06:52 UTC, KomalShinde813 commented on yogesh_khande/html/assignment6/form.html
> +        <div>
why you use extra div here

2021-05-05 08:15 UTC, KomalShinde813 approved these changes

2021-05-05 08:54 UTC, vdongre304 approved these changes

2021-05-09 12:02 UTC, merged