New Files Added:Assingment5 and assingment6
Pawan1005/MI-11-MEAN pull request #283
Opened 2021-05-03 13:35 UTC by vinod2406

2021-05-03 16:09 UTC, Pranjali1999 requested changes

2021-05-03 16:09 UTC, Pranjali1999 commented on vinod/html/ASSIN6/style2.css
> +}
After closing this bracket, you should give space.

2021-05-04 09:15 UTC, shivling123 commented on vinod/html/ASSIN6/Assingment 6.html
> +
remove space

2021-05-04 09:15 UTC, shivling123 commented on vinod/html/ASSIN6/Assingment 6.html
> +
remove extra space

2021-05-04 09:16 UTC, shivling123 commented on vinod/html/ASSIN6/Assingment 6.html
> +
remove extra space

2021-05-04 09:16 UTC, shivling123 commented on vinod/html/ASSIN6/Assingment 6.html
> +
remove space

2021-05-04 16:41 UTC, vishnukopnar approved these changes

2021-05-05 06:16 UTC, Akash-ing approved these changes

2021-05-05 15:40 UTC, Pranjali1999 approved these changes

2021-05-05 16:14 UTC, akash19972306 approved these changes

2021-05-10 13:19 UTC, SnehaMakade commented on vinod/html/ASSIN5/style3.css
> +
remove extra line

2021-05-10 13:20 UTC, SnehaMakade commented on vinod/html/ASSIN5/style3.css
> +   border: 2px solid:black;
remove colon between solid and black

2021-05-10 13:21 UTC, SnehaMakade commented on vinod/html/ASSIN6/assingment6.q2.html
> +                <label for="Java"> Java</label>
remove extra space

2021-05-10 13:21 UTC, SnehaMakade commented on vinod/html/ASSIN6/assingment6.q2.html
> +                <label for="Oracal"> Oracal</label><br /><br />
remove all extra spaces

2021-05-10 13:22 UTC, SnehaMakade requested changes
do the cahnges as per comments given

2021-05-11 06:21 UTC, SnehaMakade approved these changes

2021-05-12 06:31 UTC, merged