files succesfully uploaded
Pawan1005/MI-11-MEAN pull request #287
Opened 2021-05-05 08:48 UTC by NikitaShivhare1

2021-05-05 09:01 UTC, shubhamdalal49 requested changes

2021-05-05 09:01 UTC, shubhamdalal49 commented on Nikita/Assignment_6/assignment_6.html
> +        <td>Last name <input type="text" placeholder="Last Name" /></td>
placeholder second word first letter should be small

2021-05-05 16:43 UTC, shubhamdalal49 approved these changes

2021-05-06 05:03 UTC, Ashwin2812 approved these changes

2021-05-06 05:04 UTC, Pawan1005 requested changes

2021-05-06 05:04 UTC, Pawan1005 commented on Nikita/Assignment_5/Assignment5.html
> +</html>
indentation missing

2021-05-06 05:04 UTC, Pawan1005 commented on Nikita/Assignment_6/Assignment_6.2.html
> +</html>
indentation missing

2021-05-06 05:04 UTC, Pawan1005 commented on Nikita/Assignment_6/assignment_6.html
> +</html>
indentation missing

2021-05-06 10:17 UTC, Priyankashelke2411 requested changes

2021-05-06 10:17 UTC, Priyankashelke2411 commented on Nikita/Assignment_6/assignment_6.html
> +</html>
give proper indentation

2021-05-07 06:01 UTC, Pawan1005 approved these changes

2021-05-07 13:15 UTC, merged