File Added : Uploaded Assignment 1,2,3,4,5,6
Pawan1005/MI-11-MEAN pull request #288
Opened 2021-05-05 09:24 UTC by SnehalAhir

2021-05-05 10:05 UTC, KomalShinde813 requested changes

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment1/assignment12.html
> +
remove extra line

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment1/assignment12.html
> +</html>
add extra line at the end of the file

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment1/assignment13.html
> +</html>
add extra line at the end of the file

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment3/<assignment_1. html>
> +
remove extra line

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment3/<assignment_1. html>
> +
remove this extra line space

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment3/<assignment_1. html>
> +
remove this extra line space

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment3/<assignment_1. html>
> +
remove extra line space

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment3/<assignment_1. html>
> +</html>
add extra line at the end of the file

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment3/<assignment_1. html>
> +
remove extra lines no need of extra lines here check everywhere

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment3/assinment_2.html
> +</html>
add extra line at the end of the file

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment3/assinment_3.html
> +</html>
add extra line at the end of the file

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment3/assinment_4.html
> +
remove extra lines

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment3/assinment_4.html
> +</html> |
add extra line at the end of the file

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Second.html
> +        table, th, td{
space required before curly bracket

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Second.html
> +        .a{
space required before curly bracket

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Second.html
> +        .b{
space required before curly bracket

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Second.html
> +        .c{
space required before curly bracket

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Second.html
> +<head>
check indentation

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Second.html
> +<body style="margin: 50px 50px;">
check indentation

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Third.html
> +<head>
check indentation

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Third.html
> +        table{
space required before curly bracket

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Third.html
> +
remove extra line

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Third.html
> +        th, td{
space required before curly bracket

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Third.html
> +        .a{
space required before curly bracket

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Third.html
> +            border-width:2px;
space required before :

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Third.html
> +        .b{
space required before curly bracket

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Third.html
> +            background-color:cornsilk;
space required before :

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Third.html
> +        .c{
space required before curly bracket

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Third.html
> +            background-color:lightgray
space required before :

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Third.html
> +        .d{
space required before curly bracket

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Third.html
> +            background-color:rgb(201, 245, 230);
space required before :

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Third.html
> +
remove extra line

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/Third.html
> +<body style="margin: 30px 300px;">
check indentation

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/first.html
> +<head>
check indentation

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/first.html
> +        caption{
space required before curly bracket

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/first.html
> +            background-color:grey;
space required before :

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/first.html
> +            background-color:grey;
space required before :

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/first.html
> +
remove extra lines

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment1to4/Assignment4/first.html
> +<body style="margin: 30px 300px;">
check indenattion

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment6/style.css
> +}
add extra line at the end

2021-05-05 10:05 UTC, KomalShinde813 commented on Snehal/HTML/Assignment6/form2.html
> +        <link rel="stylesheet" href="./question_2.css" />
where is question_2.css file

2021-05-06 05:28 UTC, jyoti-ing approved these changes

2021-05-06 12:23 UTC, SamikshaWani approved these changes

2021-05-07 15:27 UTC, SnehalAhir commented on Snehal/HTML/Assignment6/form2.html
> +        <link rel="stylesheet" href="./question_2.css" />
I have added it.

2021-05-25 06:49 UTC, closed without merging