File added : Assignment 6
Pawan1005/MI-11-MEAN pull request #289
Opened 2021-05-05 09:37 UTC by Akash-ing

2021-05-05 10:04 UTC, vinod2406 approved these changes

2021-05-05 16:14 UTC, akash19972306 approved these changes

2021-05-06 08:13 UTC, Pranjali1999 requested changes

2021-05-06 08:13 UTC, Pranjali1999 commented on Akash/html/assign 6/Assignment2.html
> +
Remove extra line

2021-05-06 08:13 UTC, Pranjali1999 commented on Akash/html/assign 6/Assignment1.html
> +                <b><i>Academic Detail</i></b>
b and i tag is out dated

2021-05-06 11:02 UTC, shivling123 commented on Akash/html/assign 3/Assign9.html
> +
remove extra space

2021-05-06 11:02 UTC, shivling123 commented on Akash/html/assign 3/assign10.html
> +
remove extra space

2021-05-06 11:02 UTC, shivling123 commented on Akash/html/assign 3/assign7.html
> +
remove extra space

2021-05-06 11:02 UTC, shivling123 commented on Akash/html/assign 3/assign7.html
> +
remove extra space

2021-05-06 11:02 UTC, shivling123 commented on Akash/html/assign 3/assign7.html
> +
remove extra space

2021-05-06 11:03 UTC, shivling123 commented on Akash/html/assign 3/assign7.html
> +
remove extra space

2021-05-06 11:03 UTC, shivling123 commented on Akash/html/assign 3/assign8.html
> +
remove extra space

2021-05-06 11:03 UTC, shivling123 commented on Akash/html/assign 3/assign7.html
> +
remove extra space

2021-05-06 11:03 UTC, shivling123 commented on Akash/html/assign 3/assign7.html
> +
remove extra space

2021-05-06 11:03 UTC, shivling123 commented on Akash/html/assign 3/assign7.html
> +
remove extra space

2021-05-06 11:04 UTC, shivling123 commented on Akash/html/assign 3/Assign9.html
> +
remove extra space

2021-05-06 11:04 UTC, shivling123 requested changes
do changes as soon  as and send push code agai

2021-05-06 13:42 UTC, vishnukopnar approved these changes

2021-05-13 06:44 UTC, Bhavika222 approved these changes

2021-05-13 07:00 UTC, Pranjali1999 approved these changes

2021-05-17 06:46 UTC, shivling123 commented on Akash/html/assign 4/assig2.html
> +
remove extra space

2021-05-17 06:46 UTC, shivling123 commented on Akash/html/assign 4/assig2.html
> +
remove extra space

2021-05-17 06:46 UTC, shivling123 commented on Akash/html/assign 4/assig2.html
> +
remove extra space

2021-05-17 06:47 UTC, shivling123 commented on Akash/html/assign 4/assig2.html
> +
remove extra space

2021-05-17 06:47 UTC, shivling123 commented on Akash/html/assign 4/assign1.html
> +
remove extra space

2021-05-17 06:47 UTC, shivling123 commented on Akash/html/assign 4/assign1.html
> +
remove extra space

2021-05-17 06:48 UTC, shivling123 commented on Akash/html/assign 4/assign3.html
> +            </tr>
remove extra space
all places
and format properly

2021-05-17 06:48 UTC, shivling123 commented on Akash/html/assign 4/assign3.html
> +
remove extra space

2021-05-17 06:49 UTC, shivling123 requested changes
do changes as per comment 
push filr again asap

2021-05-17 06:50 UTC, shivling123 commented on Akash/html/assign 2/assign2.html
> -
Kishanjbethur96

2021-05-17 06:51 UTC, shivling123 commented on Akash/html/assign 2/assign2.html
> -    <br>
format all code properly

2021-05-17 06:52 UTC, shivling123 commented on Akash/html/assign 3/Assign9.html
> -
format all code properly

2021-05-17 06:52 UTC, shivling123 commented on Akash/html/assign 3/assign7.html
> -
remove space

2021-05-17 06:52 UTC, shivling123 commented on Akash/html/assign 3/assign7.html
> -
remove space

2021-05-17 06:52 UTC, shivling123 commented on Akash/html/assign 3/assign7.html
> -
remove space

2021-05-17 06:53 UTC, shivling123 commented on Akash/html/assign 4/assign1.html
> -
remove space and format code

2021-05-17 06:54 UTC, shivling123 commented on Akash/html/assign 4/assign3.html
> -
remove space

2021-05-17 06:54 UTC, shivling123 commented on Akash/html/assign 5/assign1.html
> -
remove space

2021-05-17 06:55 UTC, shivling123 requested changes
format all files code properly and remove all extra spaces of files

2021-05-19 09:12 UTC, SnehaMakade commented on Akash/html/assign 6/assignment2.html
> +</html>
add new end line

2021-05-19 09:13 UTC, SnehaMakade commented on Akash/html/assign 6/Assignment1.html
> +            <input type="text" name="frist name" placeholder="frist name" /><br />
placeholder should be like First name do this change in each input box

2021-05-19 09:13 UTC, SnehaMakade requested changes
do changes as per comments given

2021-05-19 10:59 UTC, shivling123 commented on Akash/html/assign 3/Assign9.html
> +            h1{text-align: center;}
keep space between bracket and element

2021-05-19 10:59 UTC, shivling123 commented on Akash/html/assign 3/Assign9.html
> +            p{text-align: center;}
keep space between bracket and element

2021-05-19 10:59 UTC, shivling123 commented on Akash/html/assign 3/Assign9.html
> +
remove space

2021-05-19 10:59 UTC, shivling123 commented on Akash/html/assign 3/Assign9.html
> +
remove extra space

2021-05-19 11:00 UTC, shivling123 commented on Akash/html/assign 3/Assign9.html
> +
remove extra space

2021-05-19 11:00 UTC, shivling123 commented on Akash/html/assign 2/Assign2.html
> +
remove extra space

2021-05-19 11:00 UTC, shivling123 commented on Akash/html/assign 2/assign2.html
> +
remove extra space

2021-05-19 11:00 UTC, shivling123 commented on Akash/html/assign 2/assign2.html
> +years, unitl the year 2024.</P>
format code

2021-05-19 11:00 UTC, shivling123 commented on Akash/html/assign 2/assign2.html
> +
remove extra space

2021-05-20 10:40 UTC, shivling123 commented on Akash/html/assign 3/assign7.html
> +            }
give space between tag and braces

2021-05-20 10:42 UTC, shivling123 commented on Akash/html/assign 3/assign8.html
> +        <p id="link" style="text-align: center;"
close p tage 
<p >

2021-05-20 10:44 UTC, shivling123 commented on Akash/html/assign 6/Assignment1.html
> +            <input type="checkbox" />
give id to input field and for  to label 
both id and vattribute given tu label must be same
make this change in all code

2021-05-20 10:45 UTC, shivling123 requested changes
do changes as soon as and upload it again

2021-05-27 07:00 UTC, Pawan1005 approved these changes

2021-05-27 07:03 UTC, merged