Adding Assignment6 part 2
Pawan1005/MI-11-MEAN pull request #291
Opened 2021-05-06 08:39 UTC by somesh6797

2021-05-06 14:10 UTC, dayanandviveki commented on Somesh/HTML/Assignment6/que2Assign6.html
> +    </style>
close the head tag

2021-05-06 14:11 UTC, dayanandviveki requested changes
close the head tag

2021-05-06 14:13 UTC, dayanandviveki requested changes
take style tag inside the head tag

2021-05-07 08:27 UTC, Pawan1005 approved these changes

2021-05-10 13:59 UTC, merged