Uploaded In Assignment 7 & 8
Pawan1005/MI-11-MEAN pull request #297
Opened 2021-05-12 16:25 UTC by Ashwin2812

2021-05-17 03:49 UTC, shubhamdalal49 requested changes

2021-05-17 03:49 UTC, shubhamdalal49 commented on Ashwin/HTML/07_Assignment/Homepage.css
> +}
add extra line at the end

2021-05-17 03:49 UTC, shubhamdalal49 commented on Ashwin/HTML/07_Assignment/Personalstyle.css
> +}
add extra line at the end

2021-05-17 03:49 UTC, shubhamdalal49 commented on Ashwin/HTML/08_Assignment/08_Ass.css
> +}
add extra line at the end

2021-05-17 03:49 UTC, shubhamdalal49 commented on Ashwin/HTML/08_Assignment/08_Assign.html
> +</html>
add extra line at the end

2021-05-17 04:53 UTC, shubhamdalal49 approved these changes

2021-05-18 12:16 UTC, Priyankashelke2411 requested changes

2021-05-18 12:16 UTC, Priyankashelke2411 commented on Ashwin/HTML/07_Assignment/loginstyle.css
> +.box {
line required after every class end statement

2021-05-18 12:16 UTC, Priyankashelke2411 commented on Ashwin/HTML/07_Assignment/loginstyle.css
> +h2 {
check everywhere line required after every class

2021-05-18 12:16 UTC, Priyankashelke2411 commented on Ashwin/HTML/08_Assignment/08_Ass.css
> +    justify-content:stretch;
space required after :

2021-05-25 08:56 UTC, Pawan1005 approved these changes

2021-05-25 11:48 UTC, merged