Folder added:Assignment.6 Que-2
Pawan1005/MI-11-MEAN pull request #298
Opened 2021-05-13 05:49 UTC by pritikekan

2021-05-13 06:14 UTC, pooja-nagare approved these changes

2021-05-17 04:46 UTC, Amit727619 approved these changes

2021-05-17 09:55 UTC, jyoti-ing approved these changes

2021-05-18 04:48 UTC, Pawan1005 requested changes

2021-05-18 04:48 UTC, Pawan1005 commented on priti/HTML/Assign.6/Q2.css
> +fieldset input[list="universities"]{
one  space before {

2021-05-18 04:48 UTC, Pawan1005 commented on priti/HTML/Assign.6/Q2.html
> +            <h1>MI-11 Intern HTML Assesment</h1>
indentation missing

2021-05-18 04:48 UTC, Pawan1005 commented on priti/HTML/Assign.6/Q2.html
> +</html>
create proper indentation

2021-05-19 11:17 UTC, Pawan1005 approved these changes

2021-05-19 11:23 UTC, merged