Assignment7
Pawan1005/MI-11-MEAN pull request #299
Opened 2021-05-14 07:06 UTC by urmilagagare

2021-05-17 03:31 UTC, shubhamdalal49 requested changes

2021-05-17 03:31 UTC, shubhamdalal49 commented on urmila/HTML/Assignment7/Homepage.html
> +    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
link tag and title tag is missing add them first

2021-05-17 03:31 UTC, shubhamdalal49 commented on urmila/HTML/Assignment7/profile.html
> +    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
write meta in small letters , title , link , meta tags are missing add them

2021-05-19 17:37 UTC, shubhamdalal49 requested changes

2021-05-19 17:37 UTC, shubhamdalal49 commented on urmila/HTML/Assignment7/home.html
> +</html>
check indentation and make code clear

2021-05-19 17:37 UTC, shubhamdalal49 commented on urmila/HTML/Assignment7/home.html
> +				/>
input's all attributes should be in one line

2021-05-19 17:37 UTC, shubhamdalal49 commented on urmila/HTML/Assignment7/home.css
> +</style>
add extra line and there is not need of adding style tag in css file remove it

2021-05-20 14:09 UTC, nileshp1122 approved these changes

2021-05-23 13:59 UTC, shubhamdalal49 approved these changes

2021-05-24 10:10 UTC, Pawan1005 requested changes
check all files before pushing on git

2021-05-24 10:10 UTC, Pawan1005 commented on urmila/HTML/Assignment7/Homepage.html
> +<div>
body tag missing 
make proper indentation 
title is missing for this page

2021-05-24 10:10 UTC, Pawan1005 commented on urmila/HTML/Assignment7/Login.html
> +    </head>
title is missing

2021-05-24 10:10 UTC, Pawan1005 commented on urmila/HTML/Assignment7/Login.html
> +        </style>
this need to be in head tag

2021-05-24 10:10 UTC, Pawan1005 commented on urmila/HTML/Assignment7/Login.html
> +                <form action="http://profile.html" target="_blank" onsubmit='try {return window.confirm("This form may not function properly due to certain security constraints.\nContinue?");} catch
you know is this working or not

2021-05-24 10:10 UTC, Pawan1005 commented on urmila/HTML/Assignment7/home.css
> +    }
add 1 space before { this every where in this file

2021-05-24 10:10 UTC, Pawan1005 commented on urmila/HTML/Assignment7/home.html
> +        <title>Document</title>
give proper title for this page

2021-05-24 10:10 UTC, Pawan1005 commented on urmila/HTML/Assignment7/home.html
> +                ><br /><br />
make sure closing of tag

2021-05-24 10:10 UTC, Pawan1005 commented on urmila/HTML/Assignment7/home.html
> +</html>
give proper class and id

2021-05-24 10:10 UTC, Pawan1005 commented on urmila/HTML/Assignment7/profile.html
> +    <META http-equiv="Content-Type" content="text/html; charset=utf-8">
add title here

2021-05-24 10:10 UTC, Pawan1005 commented on urmila/HTML/Assignment7/profile.html
> +    </style>
use this in head tag

2021-05-24 10:10 UTC, Pawan1005 commented on urmila/HTML/Assignment7/profile.html
> +</html>
make proper indentation

2021-05-24 10:10 UTC, Pawan1005 commented on urmila/HTML/Assignment7/sign.html
> +    <div>
closing of head tag and opening of head tag is missing

2021-05-24 10:10 UTC, Pawan1005 commented on urmila/HTML/Assignment7/sign.html
> +</html>
make proper indentation 
make sure it before pushing and check that all diva have closing tag for them

2021-05-24 10:10 UTC, Pawan1005 commented on urmila/HTML/Assignment8/Assignment8.html
> +</html>
you have to use here float make correct and push again

2021-05-26 08:03 UTC, Pawan1005 approved these changes

2021-05-26 13:01 UTC, merged