Uploaded in Assignment_7
Pawan1005/MI-11-MEAN pull request #300
Opened 2021-05-16 03:24 UTC by NikitaShivhare1

2021-05-17 03:43 UTC, shubhamdalal49 requested changes

2021-05-17 03:43 UTC, shubhamdalal49 commented on Nikita/Assignment_7/academic.html
> +        Script <input type="checkbox" name="g" value="java" />Java
check indentation

2021-05-17 03:43 UTC, shubhamdalal49 commented on Nikita/Assignment_7/academic.html
> +            >
closing tag sign is inline make them changes

2021-05-17 03:43 UTC, shubhamdalal49 commented on Nikita/Assignment_7/academic.html
> +    <br />
add one line

2021-05-17 03:43 UTC, shubhamdalal49 commented on Nikita/Assignment_7/login.css 
> +}
add one line at the end

2021-05-17 03:43 UTC, shubhamdalal49 commented on Nikita/Assignment_7/login.html
> +</html>
add one line at the end

2021-05-17 03:43 UTC, shubhamdalal49 commented on Nikita/Assignment_7/persional.html
> +<body>
check indentation

2021-05-17 03:43 UTC, shubhamdalal49 commented on Nikita/Assignment_7/persional.html
> +        </div>
check indentation

2021-05-17 03:43 UTC, shubhamdalal49 commented on Nikita/Assignment_7/persional.html
> +</html>
add extra line at the end

2021-05-17 03:43 UTC, shubhamdalal49 commented on Nikita/Assignment_8/ass_8.css
> +
remove this space

2021-05-17 03:43 UTC, shubhamdalal49 commented on Nikita/Assignment_8/ass_8.css
> +}
add extra line at the end

2021-05-17 03:43 UTC, shubhamdalal49 commented on Nikita/Assignment_8/ass_8.html
> +            <img src="home.jpg" alt="Norway" style="width:20%; float: left;">
check indentation

2021-05-18 07:47 UTC, shubhamdalal49 approved these changes

2021-05-18 08:03 UTC, Ashwin2812 approved these changes

2021-05-24 12:04 UTC, Pawan1005 requested changes

2021-05-24 12:04 UTC, Pawan1005 commented on Nikita/Assignment_7/login.css 
> +}
some thing is wrong in this files make it correct

2021-05-24 12:04 UTC, Pawan1005 commented on Nikita/Assignment_7/persional.html
> +</html>
indentation in wrong

2021-05-24 12:04 UTC, Pawan1005 commented on Nikita/Assignment_8/ass_8.html
> +</html>
indentation is wrong

2021-05-27 07:43 UTC, Pawan1005 approved these changes

2021-05-27 07:43 UTC, merged