Adding Assignment 7 And 8
Pawan1005/MI-11-MEAN pull request #301
Opened 2021-05-17 04:10 UTC by somesh6797

2021-05-17 10:43 UTC, kalyani1942 requested changes

2021-05-17 10:43 UTC, kalyani1942 commented on Somesh/HTML/Assignment7/indexstyle.css
> +
Remove Space

2021-05-17 10:43 UTC, kalyani1942 commented on Somesh/HTML/Assignment7/login.css
> +
Remove Space

2021-05-17 10:43 UTC, kalyani1942 commented on Somesh/HTML/Assignment7/login.html
> +
Remove Space

2021-05-17 10:43 UTC, kalyani1942 commented on Somesh/HTML/Assignment7/personal-details.html
> +
remove Extra Line

2021-05-17 10:43 UTC, kalyani1942 commented on Somesh/HTML/Assignment7/style.css
> +
So much Extra Line

2021-05-19 11:42 UTC, kalyani1942 approved these changes

2021-05-24 11:12 UTC, Pawan1005 approved these changes

2021-05-24 11:13 UTC, merged