assignment 6.2
Pawan1005/MI-11-MEAN pull request #302
Opened 2021-05-17 04:42 UTC by mubeen2710

assignment 6.2

2021-05-18 18:54 UTC, vdongre304 approved these changes

2021-05-19 12:57 UTC, Jestinxavier approved these changes

2021-05-24 11:07 UTC, Pawan1005 requested changes

2021-05-24 11:07 UTC, Pawan1005 commented on mubeen/html/assign6/assign6.2.css
> +
remove extra lines

2021-05-24 11:07 UTC, Pawan1005 commented on mubeen/html/assign7/home.css
> +H1 {
make sure which tag is you using

2021-05-24 11:07 UTC, Pawan1005 commented on mubeen/html/assign7/login.html
> +
remove extra line

2021-05-24 11:07 UTC, Pawan1005 commented on mubeen/html/assign7/login.html
> +</html>
create proper indentation

2021-05-24 11:07 UTC, Pawan1005 commented on mubeen/html/assign7/personal.html
> +
remove extra line

2021-05-24 11:07 UTC, Pawan1005 commented on mubeen/html/assign7/personal.html
> +</html>
make proper indentation

2021-05-24 11:07 UTC, Pawan1005 commented on mubeen/html/assign7/professional.html
> +</html>
make proper indentation
remove extra line

2021-05-24 11:07 UTC, Pawan1005 commented on mubeen/html/assign7/profile.html
> +</html>
make proper indentation

2021-05-24 11:07 UTC, Pawan1005 commented on mubeen/html/assign8/assign9.css
> +}
r3move extra lines

2021-05-24 11:07 UTC, Pawan1005 commented on mubeen/html/assign8/assign9.html
> +    <div>
body tag is missing

2021-05-24 11:07 UTC, Pawan1005 commented on mubeen/html/assign8/assign9.html
> +</html>
make proper indentation
you have to use here float property here so do it and push again

2021-05-24 11:07 UTC, Pawan1005 commented on mubeen/html/assign8/assign9.html
> +</html>
and check file name also make it correct

2021-05-24 12:16 UTC, Pawan1005 approved these changes

2021-05-24 12:38 UTC, merged