New Files Added: Assingment7 and assingment8
Pawan1005/MI-11-MEAN pull request #305
Opened 2021-05-17 09:20 UTC by vinod2406

2021-05-17 09:36 UTC, shivling123 commented on vinod/html/ASSIN7/job.html
> +
remove space , extraline

2021-05-17 09:37 UTC, shivling123 commented on vinod/html/ASSIN7/login.html
> +
remove space , extraline

2021-05-18 08:09 UTC, akash19972306 approved these changes

2021-05-18 08:45 UTC, shivling123 requested changes
remove extra spaces in code and
push again asasp

2021-05-18 09:31 UTC, Pranjali1999 approved these changes

2021-05-19 09:05 UTC, Akash-ing approved these changes

2021-05-19 09:20 UTC, SnehaMakade commented on vinod/html/ASSIN7/job.html
> +                <img src="job2.jpeg"style="height:600px; width:1300px;alt="job">
there should be space after colon always

2021-05-19 09:21 UTC, SnehaMakade commented on vinod/html/ASSIN7/job1.css
> +   ul {
always add a space after colon

2021-05-19 09:21 UTC, SnehaMakade commented on vinod/html/ASSIN7/job1.css
> +   input[type=text],input[type=password] {
always add a space after comma and colon

2021-05-19 09:23 UTC, SnehaMakade commented on vinod/html/ASSIN7/presonal.html
> +</html>
add new end line in all files

2021-05-19 09:23 UTC, SnehaMakade commented on vinod/html/ASSIN7/professional.html
> +                <lable for="description">description:</lable>
label should start with capital letter

2021-05-19 09:24 UTC, SnehaMakade requested changes
do changes as per comments given in all files

2021-05-24 10:02 UTC, sourabh513 approved these changes

2021-05-24 10:05 UTC, merged