File added: Assignment 6 part2, 7 and 8
Pawan1005/MI-11-MEAN pull request #313
Opened 2021-05-17 17:20 UTC by shivani-pawbake

2021-05-18 08:19 UTC, pooja-nagare approved these changes

2021-05-19 09:45 UTC, SnehaMakade approved these changes

2021-05-19 11:22 UTC, shivling123 commented on Shivani/HTML/assign6/ques.css
> +.lk {
give proper name to all class
which can identify easly

2021-05-19 11:23 UTC, shivling123 requested changes
do changes and push asap on git

2021-05-19 11:23 UTC, shivling123 commented on Shivani/HTML/assign7/login.html
> +
remove space

2021-05-19 11:24 UTC, shivling123 commented on Shivani/HTML/assign7/login.html
> +                <input type="text" name="user" placeholder="User Name" /><br />
give id to input field

2021-05-19 11:25 UTC, shivling123 commented on Shivani/HTML/assign7/personal.html
> +                    <label>First Name:</label>
give id to input filed and for attribute to label it must be same both

2021-05-19 11:26 UTC, shivling123 commented on Shivani/HTML/assign7/personal.html
> +                    <label for="highest Qualification">Highest Qualification:</label>
give id to input filed and for attribute to label it must be same both

2021-05-19 11:27 UTC, shivling123 commented on Shivani/HTML/assign7/profession.html
> +                <hr />
give id to input field
in all code make this change

2021-05-19 11:28 UTC, shivling123 requested changes
do changes as per required and push file asap

2021-05-22 05:15 UTC, pritikekan approved these changes

2021-05-26 07:50 UTC, Pawan1005 approved these changes

2021-05-27 05:48 UTC, closed without merging