File Added : Uploading asignment7
Pawan1005/MI-11-MEAN pull request #314
Opened 2021-05-17 18:46 UTC by arshad05786

2021-05-18 05:29 UTC, roshnidurugwar approved these changes

2021-05-18 05:34 UTC, Oshin-250197 approved these changes

2021-05-18 07:34 UTC, yogesh141293 approved these changes

2021-05-18 08:33 UTC, shivling123 commented on arshad_khan/html/asignment7/home.html
> +                /* border: 2px solid green;
remove this comment

2021-05-18 08:34 UTC, shivling123 commented on arshad_khan/html/asignment7/newuserlogin.html
> +                /*background-color: aqua;
remove comment msg

2021-05-18 08:36 UTC, shivling123 commented on arshad_khan/html/asignment7/newuserlogin.html
> +                        <label><input type="radio" name="gender" value="male" /> Male</label>
put here option box 
remove input field

2021-05-18 08:37 UTC, shivling123 commented on arshad_khan/html/asignment7/newuserlogin.html
> +                        <label for=""><input type="email" /></label><br /><br />
remove this input no need here
all line before and after input tag no need label tag

2021-05-18 08:39 UTC, shivling123 commented on arshad_khan/html/asignment7/professionaldetails.html
> +                        <label><input type="text" /></label>
remove label tag
 <label><input type="text" /></label>

before and after input tag make this changes in all assesmment

2021-05-18 08:41 UTC, shivling123 requested changes
remove label tag
 <label><input type="text" /></label>

before and after input tag make this changes in all assesmment
same mistake in all assesment

2021-05-19 10:15 UTC, Pawan1005 approved these changes

2021-05-19 10:56 UTC, merged