File added: Assignment 7 & 8
Pawan1005/MI-11-MEAN pull request #317
Opened 2021-05-18 08:55 UTC by pooja-nagare

2021-05-18 11:51 UTC, Priyankashelke2411 requested changes

2021-05-18 11:51 UTC, Priyankashelke2411 commented on Pooja/HTML/Assignment7/home.css
> +   .nav a:hover{
space required after :

2021-05-18 11:51 UTC, Priyankashelke2411 commented on Pooja/HTML/Assignment7/home.css
> +       background-color:rgb(16, 16, 44);
space required after :

2021-05-18 11:51 UTC, Priyankashelke2411 commented on Pooja/HTML/Assignment7/home.css
> +        margin-left:40px;
check everywhere space required in style after :

2021-05-18 11:51 UTC, Priyankashelke2411 commented on Pooja/HTML/Assignment7/home.css
> +        }
extra line required after every class end statement

2021-05-18 11:51 UTC, Priyankashelke2411 commented on Pooja/HTML/Assignment7/home.css
> +        color:crimson;
space required after :

2021-05-18 11:51 UTC, Priyankashelke2411 commented on Pooja/HTML/Assignment7/home.css
> +        margin-right: 5%;
extra line required at end of class statements

2021-05-19 07:29 UTC, pritikekan approved these changes

2021-05-19 10:13 UTC, Pawan1005 requested changes

2021-05-19 10:13 UTC, Pawan1005 commented on Pooja/HTML/Assignment7/home.css
> +</style>
no need of style tag here

2021-05-19 10:13 UTC, Pawan1005 commented on Pooja/HTML/Assignment7/home.html
> +</html>
indentation missing

2021-05-19 10:13 UTC, Pawan1005 commented on Pooja/HTML/Assignment8/index.html
> +</html>
indentation missing

2021-05-20 08:28 UTC, Amit727619 approved these changes

2021-05-26 07:45 UTC, Pawan1005 requested changes

2021-05-26 07:45 UTC, Pawan1005 commented on Pooja/HTML/Assignment7/academic.html
> +</html>
check indentation

2021-05-27 05:55 UTC, Pawan1005 approved these changes

2021-05-27 06:26 UTC, merged