File Added : Assigmt6-2, Assigment 7&8
Pawan1005/MI-11-MEAN pull request #321
Opened 2021-05-19 04:56 UTC by Amit727619

2021-05-19 09:18 UTC, Pawan1005 requested changes

2021-05-19 09:18 UTC, Pawan1005 commented on amit/html/Assigment6/Amit6_2.html
> +                ><br /><br /><br />
> this need to be on same line

2021-05-19 09:18 UTC, Pawan1005 commented on amit/html/Assigment6/Amit6_2.html
> +                ><br /><br />
same here also > this need to be with same line

2021-05-19 09:18 UTC, Pawan1005 commented on amit/html/Assigment7/login.html
> +</head>
indentation missing

2021-05-19 09:18 UTC, Pawan1005 commented on amit/html/Assigment8/Amit8..html
> +            }
give proper class names

2021-05-19 09:18 UTC, Pawan1005 commented on amit/html/Assigment8/Amit8..html
> +</html>
add new line at the end of file

2021-05-19 11:12 UTC, shivling123 commented on amit/html/Assigment7/login.html
> +            <label for="uname"><b>Username</b></label>
give id to input filed which given to lable

2021-05-19 11:16 UTC, shivling123 commented on amit/html/Assigment7/personaldetails.html
> +                <input type="text" id="first name" name="first name" /><br /><br />
for attribute given to lable and id given to input filed must be same

make this changes in all assesment

2021-05-19 11:18 UTC, shivling123 requested changes
do required changes as per comment 

upload again asap

2021-05-22 05:13 UTC, pritikekan approved these changes

2021-05-26 07:42 UTC, Pawan1005 requested changes

2021-05-26 07:42 UTC, Pawan1005 commented on amit/html/Assigment7/login.html
> +    <meta charset="UTF-8">
head tag opening is missing

2021-05-26 07:42 UTC, Pawan1005 commented on amit/html/Assigment8/Amit8_1html
> +</html>
check extension of file

2021-05-26 07:57 UTC, Pawan1005 approved these changes

2021-05-26 07:59 UTC, merged