Folder Added : Assignment 9
Pawan1005/MI-11-MEAN pull request #324
Opened 2021-05-21 09:41 UTC by Phantom-Code

2021-05-21 12:15 UTC, somesh6797 requested changes
Please Remove Comments

2021-05-21 12:21 UTC, Phantom-Code commented
removed comments.

2021-05-24 10:10 UTC, sourabh513 commented on Sourabh_Kanwade/html/Assignment 9/css/styles.css
> +
remove extra line

2021-05-24 10:12 UTC, sourabh513 commented on Sourabh_Kanwade/html/Assignment 9/css/styles.css
> +
remove extra line

2021-05-24 10:17 UTC, sourabh513 commented on Sourabh_Kanwade/html/Assignment 9/home.html
> +                        src="https://static.timesjobs.com/images_cand/tj_images/personlisation/tj-logo-new.png"
remove extra spaces

2021-05-24 10:22 UTC, sourabh513 commented on Sourabh_Kanwade/html/Assignment 9/home.html
> +                    <input class="col-2" type="text" placeholder="Enter Skills, Designation, etc" />
remove / at the end of the line

2021-05-24 10:23 UTC, sourabh513 commented on Sourabh_Kanwade/html/Assignment 9/home.html
> +                    <input class="col-2" type="text" placeholder="Enter Location" />
remove / at the end of the line

2021-05-24 10:40 UTC, sourabh513 approved these changes

2021-05-24 10:46 UTC, somesh6797 approved these changes

2021-05-24 10:48 UTC, merged