File added: assigment 7 & 8 added
Pawan1005/MI-11-MEAN pull request #329
Opened 2021-05-26 07:13 UTC by dayanandviveki

2021-05-26 07:38 UTC, Pawan1005 requested changes
use float property in assignment 8

2021-05-26 07:38 UTC, Pawan1005 commented on Dayanand Viveki/HTML/Assignment8/flexdeirection.html
> +</html>
use float property here

2021-05-26 09:22 UTC, dayanandviveki commented on Dayanand Viveki/HTML/Assignment8/flexdeirection.html
> +</html>
done sir

2021-05-27 05:55 UTC, Pawan1005 approved these changes

2021-05-27 07:53 UTC, merged