uploadind Assignment_09
Pawan1005/MI-11-MEAN pull request #335
Opened 2021-05-27 09:24 UTC by NikitaShivhare1

2021-05-28 08:50 UTC, Priyankashelke2411 approved these changes

2021-05-28 12:05 UTC, sourabh513 commented on Nikita/Assignment_9/Ass_09.css
> +}
remove extra line

2021-05-28 12:08 UTC, sourabh513 commented on Nikita/Assignment_9/Ass_09.css
> +}
add extra new line at the end of programe

2021-05-28 12:14 UTC, sourabh513 commented on Nikita/Assignment_9/Ass_09.html
> +                <li><a href="#"><img src="a.png" alt="2"></li>
indentation wrong

2021-05-28 12:46 UTC, sourabh513 approved these changes

2021-05-28 14:26 UTC, Ashwin2812 approved these changes

2021-05-30 17:08 UTC, urmilagagare approved these changes

2021-05-31 11:38 UTC, sourabh513 approved these changes

2021-05-31 14:09 UTC, shubhamdalal49 requested changes

2021-05-31 14:09 UTC, shubhamdalal49 commented on Nikita/Assignment_9/Ass_09.html
> +</head>
check indentation after html tag

2021-05-31 14:09 UTC, shubhamdalal49 commented on Nikita/Assignment_9/Ass_09.html
> +    <div class="job"><img src="find.png" alt="find"></div>
check indentation

2021-06-01 05:38 UTC, Pawan1005 approved these changes

2021-06-01 05:38 UTC, Pawan1005 commented on Nikita/Assignment_9/Ass_09.css
> +}
add new line at the end of files

2021-06-01 05:38 UTC, Pawan1005 commented on Nikita/Assignment_9/Ass_09.html
> +</html>
indentation is wrong make it correct

2021-06-01 06:52 UTC, merged