File Added : Assignment-9
Pawan1005/MI-11-MEAN pull request #336
Opened 2021-05-27 09:42 UTC by Jestinxavier

2021-05-27 15:42 UTC, vdongre304 approved these changes

2021-05-28 11:01 UTC, Pawan1005 requested changes

2021-05-28 11:01 UTC, Pawan1005 commented on Jestin/HTML/Assignment9/assignment9.html
> +                    <li><a href="home.html"><img src="c.png" alt="c.png"></li>
indentation is wrong

2021-05-28 11:01 UTC, Pawan1005 commented on Jestin/HTML/Assignment9/assignment9.html
> +                    <li><a href="home.html"><img src="f.png" alt="f.png"></li>
indentation is wrong

2021-05-28 12:04 UTC, Pawan1005 approved these changes

2021-05-28 12:06 UTC, merged