Folder added:Assignment.9
Pawan1005/MI-11-MEAN pull request #338
Opened 2021-05-27 13:45 UTC by pritikekan

2021-05-27 13:48 UTC, Amit727619 approved these changes

2021-05-28 02:24 UTC, pooja-nagare approved these changes

2021-05-28 11:13 UTC, Pawan1005 requested changes

2021-05-28 11:13 UTC, Pawan1005 commented on priti/HTML/Assign.9/home.html
> +                        <button class="upload-res-btn"><strong>Upload Your Resume</strong></button>
indentation is wrong

2021-05-28 11:47 UTC, sourabh513 commented on priti/HTML/Assign.9/home.html
> +                        src="https://static.timesjobs.com/images_cand/tj_images/personlisation/tj-logo-new.png"
remove the extra line

2021-05-28 12:43 UTC, merged