File Added : Assignment9
Pawan1005/MI-11-MEAN pull request #342
Opened 2021-05-28 06:25 UTC by urmilagagare

2021-05-28 06:47 UTC, shubhamdalal49 requested changes

2021-05-28 06:47 UTC, shubhamdalal49 commented on urmila/HTML/Assignment9/Assignment9.html
> +</html>
remove unwanted extra tag from the end

2021-05-28 06:47 UTC, shubhamdalal49 commented on urmila/HTML/Assignment9/Assignment9.html
> +            <span class="inpu">
indentation error

2021-05-28 06:47 UTC, shubhamdalal49 commented on urmila/HTML/Assignment9/Assignment9.html
> +</html>
indentation error

2021-05-28 06:47 UTC, shubhamdalal49 commented on urmila/HTML/Assignment9/style.css
> +left: 0px;
add space before the curly braces

2021-05-28 06:47 UTC, shubhamdalal49 commented on urmila/HTML/Assignment9/style.css
> +h1{
add space before curly braces

2021-05-31 03:52 UTC, shubhamdalal49 approved these changes

2021-05-31 04:41 UTC, Ashwin2812 approved these changes

2021-06-01 06:17 UTC, Pawan1005 requested changes

2021-06-01 06:17 UTC, Pawan1005 commented on urmila/HTML/Assignment9/Assignment9.html
>  </html>
create proper indentation

2021-06-01 08:25 UTC, Pawan1005 approved these changes

2021-06-01 09:05 UTC, merged