File Added : Assignment-9
Pawan1005/MI-11-MEAN pull request #347
Opened 2021-05-28 08:06 UTC by roshnidurugwar

2021-05-28 08:41 UTC, Priyankashelke2411 requested changes

2021-05-28 08:41 UTC, Priyankashelke2411 commented on Roshni/html/Assignment9/Assignment9.html
> +                <li><span style="position: absolute;left: 500px;top: 20px;"><h4 style="background-color:orange;opacity: 60%;">Is your Career affected by covid-19?&nbsp;&nbsp;<input type="submit" valu
give space after :

2021-05-28 08:41 UTC, Priyankashelke2411 commented on Roshni/html/Assignment9/Assignment9.html
> +</html>
add extra line at the end

2021-05-28 08:43 UTC, roshnidurugwar commented on Roshni/html/Assignment9/Assignment9.html
> +                <li><span style="position: absolute;left: 500px;top: 20px;"><h4 style="background-color:orange;opacity: 60%;">Is your Career affected by covid-19?&nbsp;&nbsp;<input type="submit" valu
i have made changes maam

2021-05-28 08:43 UTC, roshnidurugwar commented on Roshni/html/Assignment9/Assignment9.html
> +</html>
yes maam

2021-05-28 08:59 UTC, Oshin-250197 approved these changes

2021-05-28 09:09 UTC, arshad05786 approved these changes

2021-06-01 05:52 UTC, Pawan1005 approved these changes

2021-06-01 05:55 UTC, merged