Folder added : Assignment 1 in sourabh_kanwade/bootstrap/
Pawan1005/MI-11-MEAN pull request #350
Opened 2021-05-28 09:38 UTC by Phantom-Code

2021-05-28 14:55 UTC, Prashant698 approved these changes

2021-05-31 12:52 UTC, somesh6797 approved these changes

2021-06-01 06:06 UTC, Pawan1005 requested changes
add newline in svg files

2021-06-01 06:06 UTC, Pawan1005 commented on Sourabh_Kanwade/bootstrap/Assignment 1/person_black.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1
add newline

2021-06-01 06:06 UTC, Pawan1005 commented on Sourabh_Kanwade/bootstrap/Assignment 1/more.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M12 8c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2z
add newline

2021-06-01 06:06 UTC, Pawan1005 commented on Sourabh_Kanwade/bootstrap/Assignment 1/help_outline.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M11 18h2v-2h-2v2zm1-16C6.48 2 2 6.48 2 12s4.48 10
add newline

2021-06-01 06:06 UTC, Pawan1005 commented on Sourabh_Kanwade/bootstrap/Assignment 1/description.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#ffffff"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M8 16h8v2H8zm0-4h8v2H8zm6-10H6c-1.1 0-2 .9-2 2v16
add newline

2021-06-01 06:15 UTC, Pawan1005 approved these changes

2021-06-01 06:17 UTC, merged