New Files Added: Assignment9
Pawan1005/MI-11-MEAN pull request #352
Opened 2021-05-28 18:26 UTC by vinod2406

2021-05-31 07:22 UTC, akash19972306 approved these changes

2021-05-31 11:18 UTC, sourabh513 commented on vinod/html/ASSIN9/Boostrap.html
> +        <!-- Bootstrap CSS -->
remove commend lines

2021-05-31 11:18 UTC, sourabh513 commented on vinod/html/ASSIN9/Boostrap.html
> +
remove extra line

2021-05-31 11:18 UTC, sourabh513 commented on vinod/html/ASSIN9/Boostrap.html
> +            /*.block {
remove command line

2021-05-31 11:22 UTC, sourabh513 commented on vinod/html/ASSIN9/Boostrap.html
> +        <!-- <div class="consultantzone">
remove command line

2021-05-31 11:22 UTC, sourabh513 commented on vinod/html/ASSIN9/assin9.html
> +
remove extra line

2021-05-31 11:23 UTC, sourabh513 commented on vinod/html/ASSIN9/assin9.html
> +                            <button class="btn">Login</button>
wrong indentation

2021-05-31 11:23 UTC, sourabh513 commented on vinod/html/ASSIN9/assin9.html
> +                    <div class="r">
wrong identtion

2021-05-31 11:24 UTC, sourabh513 commented on vinod/html/ASSIN9/assin9.html
> +
remove extra lines

2021-05-31 11:24 UTC, sourabh513 commented on vinod/html/ASSIN9/assin9.html
> +
remove extra line

2021-05-31 11:24 UTC, sourabh513 commented on vinod/html/ASSIN9/assin9.html
> +
remove extra line

2021-05-31 11:25 UTC, sourabh513 commented on vinod/html/ASSIN9/assin9.html
> +                        <!-- <div class="consultantzone">
remove command lines

2021-05-31 11:25 UTC, sourabh513 commented on vinod/html/ASSIN9/assin9.html
> +
remove extra lines

2021-05-31 11:25 UTC, sourabh513 commented on vinod/html/ASSIN9/assin9.html
> +</html>
add new line at the end of the program

2021-06-01 06:09 UTC, Pawan1005 requested changes

2021-06-01 06:09 UTC, Pawan1005 commented on vinod/html/ASSIN7/presonal.html
>      </body>
make correct indentation

2021-06-01 06:09 UTC, Pawan1005 commented on vinod/html/ASSIN9/assin9.html
> +                <div class="block2">
make correct indentation

2021-06-01 06:09 UTC, Pawan1005 commented on vinod/html/ASSIN9/assin9.html
> +               </div>
make correct indentation

2021-06-01 06:09 UTC, Pawan1005 commented on vinod/html/ASSIN9/assin9.html
> +</html>
make correct indentation

2021-06-02 03:49 UTC, Pranjali1999 approved these changes

2021-06-04 09:23 UTC, sourabh513 approved these changes

2021-06-04 17:00 UTC, merged