Bootstrap Assignment1 Completed
Pawan1005/MI-11-MEAN pull request #357
Opened 2021-06-01 07:20 UTC by Prashant698

2021-06-01 07:23 UTC, Phantom-Code commented on prashant/Bootstrap/Assignment1.html
> +
Remove Space

2021-06-01 07:25 UTC, Phantom-Code requested changes

2021-06-01 07:25 UTC, Phantom-Code commented on prashant/Bootstrap/Assignment1.html
> +</html>
Add new line after line 55

2021-06-01 07:30 UTC, Phantom-Code approved these changes

2021-06-01 07:44 UTC, somesh6797 approved these changes

2021-06-08 05:39 UTC, Pawan1005 requested changes

2021-06-08 05:39 UTC, Pawan1005 commented on prashant/Bootstrap/Assignment1.html
> +    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
make correct indentation

2021-06-08 05:40 UTC, Prashant698 commented on prashant/Bootstrap/Assignment1.html
> +
done

2021-06-08 05:40 UTC, Prashant698 commented on prashant/Bootstrap/Assignment1.html
> +</html>
done

2021-06-08 05:46 UTC, Prashant698 commented on prashant/Bootstrap/Assignment1.html
> +    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
done it sir.

2021-06-08 07:28 UTC, Pawan1005 approved these changes

2021-06-09 10:55 UTC, merged