File added
Pawan1005/MI-11-MEAN pull request #358
Opened 2021-06-01 07:21 UTC by shubhamdalal49

2021-06-02 03:59 UTC, Ashwin2812 requested changes

2021-06-02 03:59 UTC, Ashwin2812 commented on Shubham_Dalal/Bootstrap/ASSIGNMENT10/Shubham_assignment10.html
> +    </body>
Remove Extra Space

2021-06-02 03:59 UTC, Ashwin2812 commented on Shubham_Dalal/Bootstrap/ASSIGNMENT10/assignment10.css
> +}
Add extra line

2021-06-02 05:33 UTC, nileshp1122 requested changes

2021-06-02 05:33 UTC, nileshp1122 commented on Shubham_Dalal/Bootstrap/ASSIGNMENT10/Shubham_assignment10.html
> +        <title>Document</title>
change title name

2021-06-02 05:33 UTC, nileshp1122 commented on Shubham_Dalal/Bootstrap/ASSIGNMENT10/Shubham_assignment10.html
> +                        Snehal Ghodmare posted a new assignment: Evaluation 12Dec20<br><span style="color: grey;">Dec 12(Edited Dec 12)</span></p>
check indentation on p tag

2021-06-02 05:33 UTC, nileshp1122 commented on Shubham_Dalal/Bootstrap/ASSIGNMENT10/Shubham_assignment10.html
> +                            Announce something to your class</p>
check indentation on p tag

2021-06-02 05:33 UTC, nileshp1122 commented on Shubham_Dalal/Bootstrap/ASSIGNMENT10/Shubham_assignment10.html
> +                        Snehal Ghodmare posted a new material: Bootstrap-Document<br><span style="color: grey;">Dec 16</span></p>
indentation on p

2021-06-02 05:33 UTC, nileshp1122 commented on Shubham_Dalal/Bootstrap/ASSIGNMENT10/Shubham_assignment10.html
> +                        Snehal Ghodmare posted a new material: Updated Document for HTML, CSS Content<br><span style="color: grey;">Dec 10</span></p>
indentation on p

2021-06-02 05:33 UTC, nileshp1122 commented on Shubham_Dalal/Bootstrap/ASSIGNMENT10/Shubham_assignment10.html
> +
remove extra line or indentation

2021-06-02 05:33 UTC, nileshp1122 commented on Shubham_Dalal/Bootstrap/ASSIGNMENT10/assignment10.css
> +}
add extra line

2021-06-03 05:53 UTC, nileshp1122 approved these changes

2021-06-03 06:13 UTC, Ashwin2812 approved these changes

2021-06-03 06:32 UTC, nileshp1122 approved these changes

2021-06-08 05:37 UTC, Pawan1005 approved these changes

2021-06-08 07:32 UTC, merged