Assignment 9 Added
Pawan1005/MI-11-MEAN pull request #360
Opened 2021-06-01 11:54 UTC by Bhavika222

2021-06-02 08:13 UTC, Akash-ing approved these changes

2021-06-08 05:36 UTC, Pawan1005 requested changes

2021-06-08 05:36 UTC, Pawan1005 commented on Bhavika/html/Assignment 9/Assi9.style.css
> +}
remove commented code

2021-06-08 05:36 UTC, Pawan1005 commented on Bhavika/html/Assignment 9/Assi9.html
> +</html>
remove commented code

2021-06-08 05:36 UTC, Pawan1005 commented on Bhavika/html/Assignment 9/Assi9.html
> +                                    <h5>Information Technology</h5>
make correct indentation

2021-06-08 05:36 UTC, Pawan1005 commented on Bhavika/html/Assignment 9/Assi9.html
> +
remove extra lines

2021-06-08 05:36 UTC, Pawan1005 commented on Bhavika/Bootstrap/person.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="24px" viewBox="0 0 24 24" width="24px" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M12 12c2.21 0 4-1.79 4-4s-1.79-4-4-4-4 1.79-4 4 1
add new line to end of  every file

2021-06-08 05:36 UTC, Pawan1005 commented on Bhavika/Bootstrap/bootstrap.min.css.xml
> +  </g>
make correct indentation

2021-06-09 05:44 UTC, Pawan1005 approved these changes

2021-06-09 08:30 UTC, merged