Added in Bootstrap Assignment 01
Pawan1005/MI-11-MEAN pull request #363
Opened 2021-06-02 04:01 UTC by Ashwin2812

2021-06-02 06:18 UTC, nileshp1122 requested changes

2021-06-02 06:18 UTC, nileshp1122 commented on Ashwin/Bootstrap/01_Assignment/01_Assignment.html
> +                                    src="Images/1.png"
check indentation on img tag

2021-06-02 06:21 UTC, nileshp1122 commented on Ashwin/Bootstrap/01_Assignment/01_Assignment.html
> +                                    src="Images/1.png"
img  required in one line

2021-06-02 08:03 UTC, shubhamdalal49 approved these changes

2021-06-03 10:45 UTC, nileshp1122 approved these changes

2021-06-07 08:24 UTC, Pawan1005 approved these changes

2021-06-08 05:38 UTC, merged