file added boostrapassign1.html
Pawan1005/MI-11-MEAN pull request #370
Opened 2021-06-02 06:52 UTC by vijaya1811

2021-06-02 07:48 UTC, shubhamdalal49 requested changes

2021-06-02 07:48 UTC, shubhamdalal49 commented on PAWAN/BOOSTRAP/assignment1/boostrapassign1.html
> +        }
use style tag inside the head tag

2021-06-02 09:07 UTC, nileshp1122 requested changes

2021-06-02 09:07 UTC, nileshp1122 commented on PAWAN/BOOSTRAP/assignment1/boostrapassign1.html
> +    <style background-image: url (image/pexels.jpg width= "800" height= "500");>
style tag use in head

2021-06-02 10:08 UTC, vijaya1811 commented on PAWAN/BOOSTRAP/assignment1/boostrapassign1.html
> +        }
I done changes please kindly check

2021-06-03 05:04 UTC, nileshp1122 requested changes

2021-06-03 05:04 UTC, nileshp1122 commented on PAWAN/BOOSTRAP/assignment1/boostrapassign1.html
> +    <style>
style tag place in head tag

2021-06-03 06:01 UTC, vijaya1811 commented on PAWAN/BOOSTRAP/assignment1/boostrapassign1.html
> +    <style background-image: url (image/pexels.jpg width= "800" height= "500");>
yes I done changes please review

2021-06-03 06:04 UTC, vijaya1811 commented on PAWAN/BOOSTRAP/assignment1/boostrapassign1.html
> +    <style>
yes done

2021-06-03 06:34 UTC, nileshp1122 approved these changes

2021-06-04 04:15 UTC, shubhamdalal49 approved these changes

2021-06-04 06:04 UTC, Ashwin2812 approved these changes

2021-06-04 06:11 UTC, urmilagagare approved these changes

2021-06-04 11:22 UTC, Pawan1005 requested changes

2021-06-04 11:22 UTC, Pawan1005 commented on PAWAN/BOOSTRAP/assignment1/boostrapassign1.html
> +</html>
make indentation foe head tag

2021-06-07 05:38 UTC, closed without merging