File Added : Bootstrap Assignment 2
Pawan1005/MI-11-MEAN pull request #397
Opened 2021-06-11 06:14 UTC by shubhamdalal49

2021-06-11 14:06 UTC, nileshp1122 requested changes

2021-06-11 14:06 UTC, nileshp1122 commented on Shubham_Dalal/Bootstrap/ASSIGNMENT_2/Bootstrap_Assignment_2.html
> +                        ><br />
check span tag close

2021-06-12 08:09 UTC, Pawan1005 requested changes

2021-06-12 08:09 UTC, Pawan1005 commented on Shubham_Dalal/Bootstrap/ASSIGNMENT_2/Bootstrap_Assignment_2.html
> +</html>
image is missing

2021-06-12 10:59 UTC, nileshp1122 approved these changes

2021-06-13 03:32 UTC, Ashwin2812 approved these changes

2021-06-13 13:10 UTC, Pawan1005 approved these changes

2021-06-13 16:45 UTC, merged