Bootstrap Assignment_3
Pawan1005/MI-11-MEAN pull request #406
Opened 2021-06-13 15:43 UTC by NikitaShivhare1

2021-06-13 15:53 UTC, Ashwin2812 requested changes

2021-06-13 15:53 UTC, Ashwin2812 commented on Nikita/Bootstap/Bootstrap Assignment_3/assign.html
> +                                    <h5 class="card-title text-danerous text-right">NEHA SMITH</h5>
Check class name dangerous

2021-06-13 15:53 UTC, Ashwin2812 commented on Nikita/Bootstap/Bootstrap Assignment_3/assign.html
> +                                    src="img_2.png"
Correct intendation in all image tag

2021-06-13 16:26 UTC, Ashwin2812 approved these changes

2021-06-13 16:46 UTC, shubhamdalal49 approved these changes

2021-06-14 06:52 UTC, Pawan1005 approved these changes

2021-06-14 08:43 UTC, sourabh513 approved these changes

2021-06-14 08:46 UTC, merged