uploading assignment2
Pawan1005/MI-11-MEAN pull request #408
Opened 2021-06-14 03:04 UTC by vdongre304

2021-06-14 08:54 UTC, Jestinxavier approved these changes

2021-06-14 15:03 UTC, yogesh545 approved these changes

2021-06-15 08:13 UTC, Pawan1005 requested changes

2021-06-15 08:13 UTC, Pawan1005 commented on vinitD/bootstrap/assignment2/second.html
> +
remove extra lines

2021-06-15 08:13 UTC, Pawan1005 commented on vinitD/bootstrap/assignment2/second.html
> +</body>
create proper indentation

2021-06-15 08:13 UTC, Pawan1005 commented on vinitD/bootstrap/assignment3/third.html
> +</html>
create indentation

2021-06-15 12:22 UTC, Pawan1005 approved these changes

2021-06-15 12:32 UTC, merged