File Added : Assignment 3 & 4
Pawan1005/MI-11-MEAN pull request #418
Opened 2021-06-14 08:23 UTC by pooja-nagare

2021-06-14 09:21 UTC, pritikekan approved these changes

2021-06-14 13:58 UTC, Pawan1005 requested changes

2021-06-14 13:58 UTC, Pawan1005 commented on Pooja/Bootstrap/Assignment3/about.html
> +    </style>
put this inside head tag

2021-06-14 13:59 UTC, Pawan1005 requested changes

2021-06-14 13:59 UTC, Pawan1005 commented on Pooja/Bootstrap/Assignment4/index.html
> +    </style>
styles need to be in head tag 
body tag is missing

2021-06-15 08:14 UTC, Pawan1005 approved these changes

2021-06-15 09:18 UTC, merged