File Added : Bootstrap Assignment 3 & 4
Pawan1005/MI-11-MEAN pull request #420
Opened 2021-06-14 11:00 UTC by urmilagagare

2021-06-14 11:55 UTC, vijaya1811 approved these changes

2021-06-14 13:57 UTC, Pawan1005 requested changes

2021-06-14 13:57 UTC, Pawan1005 commented on urmila/BOOTSTRAP/Assignment3/Q1.html
> +</html>
create proper indentation

2021-06-14 14:08 UTC, shubhamdalal49 requested changes

2021-06-14 14:08 UTC, shubhamdalal49 commented on urmila/BOOTSTRAP/Assignment3/Q1.html
> +<head>
check indentation error

2021-06-14 14:08 UTC, shubhamdalal49 commented on urmila/BOOTSTRAP/Assignment4/Q1.html
> +                  }
give indentation properly

2021-06-14 14:08 UTC, shubhamdalal49 commented on urmila/BOOTSTRAP/Assignment4/Q1.html
> +        </div>
check indentation and do it properly

2021-06-15 08:09 UTC, shubhamdalal49 approved these changes

2021-06-15 08:15 UTC, Pawan1005 approved these changes

2021-06-15 09:05 UTC, Ashwin2812 approved these changes

2021-06-15 09:13 UTC, merged