New Files Added : Bootstarap assignment 5 & 6
Pawan1005/MI-11-MEAN pull request #432
Opened 2021-06-15 12:17 UTC by Pranjali1999

2021-06-15 13:34 UTC, akash19972306 requested changes

2021-06-15 13:34 UTC, akash19972306 commented on Pranjali/BOOTSTRAP/Assi5/Ass5.html
> +                <style></style>
remove those style...this is not you used

2021-06-15 14:16 UTC, akash19972306 approved these changes

2021-06-16 09:18 UTC, Pawan1005 approved these changes

2021-06-16 09:43 UTC, merged