Bootstrap Assignment 5 & 6
Pawan1005/MI-11-MEAN pull request #437
Opened 2021-06-15 15:12 UTC by NikitaShivhare1

2021-06-18 03:52 UTC, Pawan1005 reviewed
where is assignment 6

2021-06-21 05:53 UTC, shubhamdalal49 approved these changes

2021-06-21 06:33 UTC, Pawan1005 requested changes
create proper indentation

2021-06-21 06:33 UTC, Pawan1005 commented on Nikita/Bootstap/Bootstrap Assignment_6/academic.html
> +</html>
create proper indentation

2021-06-21 06:33 UTC, Pawan1005 commented on Nikita/Bootstap/Bootstrap Assignment_6/personal.html
> +</style>
this needs to be in head tag

2021-06-21 06:33 UTC, Pawan1005 commented on Nikita/Bootstap/Bootstrap Assignment_6/personal.html
> +</html>
create proper indentation

2021-06-21 06:33 UTC, Pawan1005 commented on Nikita/Bootstap/Bootstrap Assignment_6/login.html
> +</html>
create proper indentation

2021-06-21 13:42 UTC, Pawan1005 approved these changes

2021-06-21 13:58 UTC, merged