File Added : Bootstrap Assignment 5&6
Pawan1005/MI-11-MEAN pull request #444
Opened 2021-06-16 09:12 UTC by roshnidurugwar

2021-06-16 09:22 UTC, Oshin-250197 approved these changes

2021-06-17 03:52 UTC, arshad05786 approved these changes

2021-06-17 11:15 UTC, Pawan1005 requested changes

2021-06-17 11:15 UTC, Pawan1005 commented on Roshni/Bootstrap/Assignment6/Academic.html
> +
remove extra line

2021-06-17 11:15 UTC, Pawan1005 commented on Roshni/Bootstrap/Assignment6/Academic.html
> +          </div>
make correct indentation

2021-06-17 11:15 UTC, Pawan1005 commented on Roshni/Bootstrap/Assignment6/Academic.html
> +</html>
make correct indentation

2021-06-17 11:15 UTC, Pawan1005 commented on Roshni/Bootstrap/Assignment6/Login.html
> +      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
make correct indentation

2021-06-17 11:15 UTC, Pawan1005 commented on Roshni/Bootstrap/Assignment6/Login.html
> +    </head>
remove this closing tag

2021-06-17 11:15 UTC, Pawan1005 commented on Roshni/Bootstrap/Assignment6/Login.html
> +        <div class="container">
correct indentation

2021-06-17 11:15 UTC, Pawan1005 commented on Roshni/Bootstrap/Assignment6/Login.html
> +</html>
make correct indentation

2021-06-17 16:09 UTC, roshnidurugwar commented on Roshni/Bootstrap/Assignment6/Academic.html
> +
done

2021-06-17 16:10 UTC, roshnidurugwar commented on Roshni/Bootstrap/Assignment6/Academic.html
> +          </div>
done

2021-06-17 16:10 UTC, roshnidurugwar commented on Roshni/Bootstrap/Assignment6/Academic.html
> +</html>
done

2021-06-17 16:10 UTC, roshnidurugwar commented on Roshni/Bootstrap/Assignment6/Login.html
> +      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
done

2021-06-17 16:10 UTC, roshnidurugwar commented on Roshni/Bootstrap/Assignment6/Login.html
> +    </head>
done

2021-06-17 16:10 UTC, roshnidurugwar commented on Roshni/Bootstrap/Assignment6/Login.html
> +        <div class="container">
done

2021-06-17 16:10 UTC, roshnidurugwar commented on Roshni/Bootstrap/Assignment6/Login.html
> +</html>
done

2021-06-20 17:16 UTC, Pawan1005 approved these changes

2021-06-21 04:16 UTC, merged