File added:  Vijaya Boostrap assignments 5 and 6
Pawan1005/MI-11-MEAN pull request #457
Opened 2021-06-18 07:42 UTC by vijaya1811

2021-06-18 07:47 UTC, shubhamdalal49 approved these changes

2021-06-20 14:26 UTC, nileshp1122 requested changes

2021-06-20 14:26 UTC, nileshp1122 commented on vijaya/Boostrap/assignment6/assign6login.html
> +
remove extra line

2021-06-20 14:26 UTC, nileshp1122 commented on vijaya/Boostrap/assignment6/assign6login.html
> +    </div>
check indentation

2021-06-20 14:26 UTC, nileshp1122 commented on vijaya/Boostrap/assignment6/assign6login.html
> +
remove extra line

2021-06-20 14:26 UTC, nileshp1122 commented on vijaya/Boostrap/assignment6/assign6academic.html
> +    </div>
check indentation

2021-06-21 06:34 UTC, Pawan1005 requested changes
make changes asap

2021-06-21 06:56 UTC, vijaya1811 commented
> make changes asap

yes sir I done changes and pushed again please review

2021-06-21 06:56 UTC, vijaya1811 commented on vijaya/Boostrap/assignment6/assign6academic.html
> +    </div>
yes done please review

2021-06-21 07:14 UTC, nileshp1122 approved these changes

2021-06-21 15:46 UTC, shubhamdalal49 approved these changes

2021-06-22 06:39 UTC, Pawan1005 approved these changes

2021-06-22 07:24 UTC, merged