File Added : Javascript Assignment1
Pawan1005/MI-11-MEAN pull request #458
Opened 2021-06-18 08:15 UTC by urmilagagare

2021-06-18 08:43 UTC, shubhamdalal49 requested changes

2021-06-18 08:43 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment1/swap.html
> +</script>
put this script tag inside the head tag or before the end of body tag,

2021-06-20 14:30 UTC, nileshp1122 requested changes

2021-06-20 14:30 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment1/temprature.html
> +                <!-- <button  class="btn btn-pill btn-success  " onclick="show()">Swap using temporary variable</button>   -->
remove comment

2021-06-20 14:30 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment1/temprature.html
> +                ><br />
check indentation

2021-06-20 14:30 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment1/temprature.html
> +        ></script>
script tag proper close

2021-06-20 14:30 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment1/temprature.html
> +                <center>
center tag is outdated

2021-06-21 06:17 UTC, nileshp1122 approved these changes

2021-06-21 10:58 UTC, vijaya1811 approved these changes

2021-06-21 15:40 UTC, shubhamdalal49 approved these changes

2021-06-22 07:56 UTC, Pawan1005 requested changes

2021-06-22 07:56 UTC, Pawan1005 commented on urmila/JAVASCRIPT/Assignment1/swap.html
> +</html>
where is second method

2021-06-22 07:56 UTC, Pawan1005 commented on urmila/JAVASCRIPT/Assignment1/temprature.html
> +                <button class="btn btn-success" onclick="show()">
why you need to buttons

2021-06-22 07:59 UTC, Pawan1005 requested changes

2021-06-22 07:59 UTC, Pawan1005 commented on urmila/JAVASCRIPT/Assignment1/temprature.html
>                  ><br />
create proper indentation

2021-06-22 08:58 UTC, Pawan1005 reviewed
same code like jestin

2021-06-23 04:22 UTC, Pawan1005 approved these changes

2021-06-23 04:26 UTC, merged