Added in JavaScript Assignment 01 & 02
Pawan1005/MI-11-MEAN pull request #462
Opened 2021-06-20 03:31 UTC by Ashwin2812

2021-06-20 14:43 UTC, nileshp1122 requested changes

2021-06-20 14:43 UTC, nileshp1122 commented on Ashwin/JavaScript/02_Assignment/02_Assignment_1.html
> +
remove extra line

2021-06-20 14:43 UTC, nileshp1122 commented on Ashwin/JavaScript/02_Assignment/02_Assignment_2.html
> +
remove extra line

2021-06-20 14:43 UTC, nileshp1122 commented on Ashwin/JavaScript/02_Assignment/02_Assignment_2.html
> +
remove extra line

2021-06-20 14:43 UTC, nileshp1122 commented on Ashwin/JavaScript/02_Assignment/02_Assignment_2.html
> +
remove extra line

2021-06-20 14:43 UTC, nileshp1122 commented on Ashwin/JavaScript/02_Assignment/02_Assignment_2.html
> +
remove extra line

2021-06-23 04:23 UTC, Pawan1005 approved these changes

2021-06-23 04:46 UTC, nileshp1122 approved these changes

2021-06-23 07:23 UTC, shubhamdalal49 requested changes

2021-06-23 07:23 UTC, shubhamdalal49 commented on Ashwin/JavaScript/02_Assignment/02_Assignment_2.html
> +
remove this extra line

2021-06-23 07:23 UTC, shubhamdalal49 commented on Ashwin/JavaScript/02_Assignment/02_Assignment_2.html
> +
remove this extra line

2021-06-23 07:24 UTC, shubhamdalal49 approved these changes

2021-06-23 07:51 UTC, merged