First Assignment
Pawan1005/MI-11-MEAN pull request #47
Opened 2021-04-07 08:46 UTC by Oshin-250197

2021-04-07 09:09 UTC, SamikshaWani approved these changes

2021-04-07 16:34 UTC, Pawan1005 requested changes

2021-04-07 16:34 UTC, Pawan1005 commented on Oshin/html/firstassignment.html
> +    <b>HTML</b>
no need of b tag

2021-04-07 16:34 UTC, Pawan1005 commented on Oshin/html/firstassignment.html
> +    <b>Introduction</b>
same for this

2021-04-07 16:34 UTC, Pawan1005 commented on Oshin/html/firstassignment.html
> +<!DOCTYPE html>
create separate page for new question or don't use html tag for new question

2021-04-09 04:40 UTC, roshnidurugwar approved these changes

2021-04-09 04:43 UTC, merged