File Added: JavaScript Assignments 1 & 2
Pawan1005/MI-11-MEAN pull request #472
Opened 2021-06-22 07:42 UTC by vijaya1811

2021-06-23 07:18 UTC, shubhamdalal49 requested changes

2021-06-23 07:18 UTC, shubhamdalal49 commented on vijaya/JavaScript/assignment1/swap.html
> +    <style>
remove this extra line and check indentation error

2021-06-23 07:18 UTC, shubhamdalal49 commented on vijaya/JavaScript/assignment1/swap.html
> +<body>
check indentation

2021-06-23 07:18 UTC, shubhamdalal49 commented on vijaya/JavaScript/assignment2/student.html
> +                // document.write("<br>Your Grade : "+grade);
remove this unnecessary comments

2021-06-23 13:04 UTC, Pawan1005 requested changes
make changes asap

2021-06-24 13:11 UTC, nileshp1122 approved these changes

2021-06-24 15:58 UTC, Pawan1005 approved these changes

2021-06-25 03:55 UTC, Pawan1005 approved these changes

2021-06-25 10:33 UTC, shubhamdalal49 approved these changes

2021-06-25 18:25 UTC, urmilagagare approved these changes

2021-06-28 05:13 UTC, merged