New File Added:Assignment5 and assignment6
Pawan1005/MI-11-MEAN pull request #473
Opened 2021-06-22 18:16 UTC by vinod2406

2021-06-23 08:17 UTC, Pranjali1999 requested changes

2021-06-23 08:17 UTC, Pranjali1999 commented on vinod/Bootstrap/ASSIN6/boostrap assi6.html
> +            <center><h1>job portal</h1></center>
center tag is out dated.

2021-06-23 08:17 UTC, Pranjali1999 commented on vinod/Bootstrap/ASSIN6/bootstrap personal.html
> +                    <label class="form-check-label" >
Where is closing of this label.

2021-06-23 08:17 UTC, Pranjali1999 commented on vinod/Bootstrap/ASSIN6/bootstrap personal.html
> +                    </div><br>
Give indentation properly.

2021-06-23 13:03 UTC, Pawan1005 requested changes
make changes asap

2021-06-27 16:32 UTC, akash19972306 approved these changes

2021-06-29 02:25 UTC, Pawan1005 approved these changes

2021-06-29 03:13 UTC, merged