File Added:- Assignment 1 and Assignment 2
Pawan1005/MI-11-MEAN pull request #477
Opened 2021-06-23 06:58 UTC by shubhamdalal49

2021-06-23 13:00 UTC, Pawan1005 approved these changes

2021-06-23 13:26 UTC, nileshp1122 requested changes

2021-06-23 13:26 UTC, nileshp1122 commented on Shubham_Dalal/JavaScript/Assignment2/Assignment_two_Q2.html
> +
remove extra line

2021-06-23 13:26 UTC, nileshp1122 commented on Shubham_Dalal/JavaScript/Assignment2/Assignment_two_Q2.html
> +
remove extra line

2021-06-23 13:26 UTC, nileshp1122 commented on Shubham_Dalal/JavaScript/Assignment2/Assignment_two_Q2.html
> +                /* align-self: center; */
remove comment

2021-06-23 13:26 UTC, nileshp1122 commented on Shubham_Dalal/JavaScript/Assignment2/Assignment_two_Q2.html
> +                /* width: fit-content; */
remove comments

2021-06-23 13:26 UTC, nileshp1122 commented on Shubham_Dalal/JavaScript/Assignment2/Assignment2_Q1.css
> +.flexbox{
before parenthesis space required

2021-06-25 08:01 UTC, nileshp1122 approved these changes

2021-06-25 09:36 UTC, merged