Folder Added: JavaScript Assignment-3
Pawan1005/MI-11-MEAN pull request #481
Opened 2021-06-24 03:42 UTC by akash19972306

2021-06-24 09:44 UTC, Pawan1005 requested changes

2021-06-24 09:44 UTC, Pawan1005 commented on akash1/JavaScript/ASSIn3/Ass1.html
> +
remove extra line

2021-06-24 09:44 UTC, Pawan1005 commented on akash1/JavaScript/ASSIn3/Ass1.html
> +</html>
remove extra lines

2021-06-24 15:23 UTC, Pranjali1999 requested changes

2021-06-24 15:23 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn3/Assq2.html
> +           prime=parseInt(document.getElementById("input1").value);
Wrong Indentation.

2021-06-24 15:23 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn3/Assq2.html
> +            document.getElementById("p").innerHTML="It is not a prime nor composite number " +prime;
Wrong Indentation.

2021-06-24 15:23 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn3/Assq2.html
> +            document.getElementById("p").innerHTML="It is not a prime number " +prime;
Wrong Indentation.

2021-06-24 15:23 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn3/Assq2.html
> +                    document.getElementById("p").innerHTML="It is not a prime number " +prime;
Wrong Indentation.

2021-06-24 15:23 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn3/Assq2.html
> +                    document.getElementById("p").innerHTML="It is a prime number " +prime;
Wrong Indentation.

2021-06-24 15:23 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn3/Assq3.html
> +            document.getElementById("p").innerHTML="It is Even Number ";
Wrong Indentation.

2021-06-24 15:23 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn3/Assq4.html
> +           a=parseInt(document.getElementById("input1").value);
Wrong Indentation.

2021-06-24 15:23 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn3/Assq4.html
> +            alert("The factorial of -ve number is not possible")
Wrong Indentation.

2021-06-24 15:23 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn3/Assq5.html
> +           var row=parseInt(document.getElementById("input1").value);
Wrong Indentation.

2021-06-25 14:59 UTC, Pranjali1999 approved these changes

2021-06-25 15:58 UTC, Pawan1005 approved these changes

2021-06-25 16:05 UTC, merged