File Added :  Assignment 2 & 3
Pawan1005/MI-11-MEAN pull request #485
Opened 2021-06-24 07:25 UTC by urmilagagare

2021-06-24 08:45 UTC, nileshp1122 requested changes

2021-06-24 08:45 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment2/largest_number.html
> +
remove extra line

2021-06-24 08:45 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment2/largest_number.html
> +                    <button onclick="show()" type="button"
button tag proper indent

2021-06-24 08:45 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment2/largest_number.html
> +        crossorigin="anonymous"></script>
script tag proper indent

2021-06-24 08:45 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment2/largest_number.html
> +
remove extra line

2021-06-24 08:45 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment2/largest_number.html
> +</html>
add extra line at the end

2021-06-24 08:45 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment3/Ass3.html
> +        <!-- Prime Number -->
remove comment

2021-06-24 08:45 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment3/Ass3.html
> +        <!-- Leap Year -->
remove coment

2021-06-24 08:45 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment3/Ass3.html
> +        <!-- Factorial -->
remove all comments

2021-06-24 08:45 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment3/Ass3.js
> +
remove extra line

2021-06-24 08:45 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment3/Ass3.js
> +
remove extra line or comment

2021-06-24 08:45 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment3/Ass3.js
> +
remove extra line

2021-06-24 08:45 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment3/Ass3.js
> +
remove extra line

2021-06-24 08:45 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment3/Ass3.js
> +
remove extra line

2021-06-24 08:45 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment3/Ass3.js
> +
remove extra line

2021-06-24 08:45 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment3/Ass3.js
> +
remove extra line

2021-06-24 08:45 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment3/Ass3.js
> +
remove all extra lines

2021-06-24 08:45 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment3/style.css
> +/* Leap */
remove comment

2021-06-24 08:45 UTC, nileshp1122 commented on urmila/JAVASCRIPT/Assignment3/style.css
> +.prime-container input,
this code required in one line

2021-06-24 13:02 UTC, nileshp1122 approved these changes

2021-06-25 10:24 UTC, shubhamdalal49 requested changes

2021-06-25 10:24 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment2/grade_system.html
> +      <body>
check indentation

2021-06-25 10:24 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment2/largest_number.html
> +<head>
check indentation

2021-06-25 10:24 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment2/largest_number.html
> +    <body>
check indentation

2021-06-25 16:00 UTC, Pawan1005 approved these changes

2021-06-27 09:45 UTC, merged