File Added : Uploading asignment 2,3and4
Pawan1005/MI-11-MEAN pull request #492
Opened 2021-06-25 04:50 UTC by arshad05786

2021-06-25 07:28 UTC, roshnidurugwar approved these changes

2021-06-25 07:31 UTC, Oshin-250197 approved these changes

2021-06-25 16:24 UTC, Pawan1005 requested changes

2021-06-25 16:24 UTC, Pawan1005 commented on arshad_khan/Java_script/asignment2/findsecondlargestnumber.html
> +</html>
check indentation

2021-06-25 16:24 UTC, Pawan1005 commented on arshad_khan/Java_script/asignment2/marksgrade.html
> +                    <fieldset style="width: 500px;height: 500px;background-color: rgb(182, 35, 157);>
check indentation

2021-06-25 16:24 UTC, Pawan1005 commented on arshad_khan/Java_script/asignment2/marksgrade.html
> +</html>
check indentation

2021-06-25 16:24 UTC, Pawan1005 commented on arshad_khan/Java_script/asignment3/fact.html
> +                            <p id="pid"></p>
check indentation

2021-06-25 16:24 UTC, Pawan1005 commented on arshad_khan/Java_script/asignment3/leapyear.html
> +                            <p id="pid"></p>
check indentation

2021-06-25 16:24 UTC, Pawan1005 commented on arshad_khan/Java_script/asignment3/pattern.html
> +                            <p id="pid"></p>
check indentation

2021-06-25 16:24 UTC, Pawan1005 commented on arshad_khan/Java_script/asignment4/automophic.html
> +                            <p id="pid"></p>
check indentation

2021-06-29 02:26 UTC, Pawan1005 approved these changes

2021-06-29 10:11 UTC, merged