Folders Added: Assignment 4 & 5
Pawan1005/MI-11-MEAN pull request #500
Opened 2021-06-26 15:09 UTC by akash19972306

2021-06-27 13:40 UTC, Pranjali1999 requested changes

2021-06-27 13:40 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn4/Ass4.1.html
> +             top: 149px;
wrong Indentation.

2021-06-27 13:40 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn4/Ass4.1.html
> +             position: relative;
wrong Indentation.

2021-06-27 13:40 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn4/Ass4.1.html
> +        .container{
wrong Indentation.

2021-06-27 13:40 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn4/Ass4.2.html
> +        .container{
wrong Indentation.

2021-06-27 13:40 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn4/Ass4.3.html
> +        .container{
wrong Indentation.

2021-06-27 13:40 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn4/Ass4.4.html
> +        .container{
wrong Indentation.

2021-06-27 13:40 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn4/Ass4.5.html
> +        .container{
wrong Indentation.

2021-06-27 13:40 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn5/Ass5.1.html
> +        .container{
wrong Indentation.

2021-06-27 13:40 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn5/Ass5.2.html
> +        .container{
wrong Indentation.

2021-06-27 13:40 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn5/Ass5.3.html
> +        .container{
wrong Indentation.

2021-06-27 13:40 UTC, Pranjali1999 commented on akash1/JavaScript/ASSIn5/Ass5.4.html
> +        .container{
wrong Indentation.

2021-06-27 16:53 UTC, vinod2406 approved these changes

2021-06-28 03:56 UTC, Pranjali1999 approved these changes

2021-06-29 03:10 UTC, Pawan1005 approved these changes

2021-06-29 08:41 UTC, merged