File Added : Assignment 4 & 5
Pawan1005/MI-11-MEAN pull request #503
Opened 2021-06-28 12:51 UTC by urmilagagare

2021-06-29 08:51 UTC, shubhamdalal49 requested changes

2021-06-29 08:51 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment4/Automorphic.html
> +<head>
check indentation

2021-06-29 08:51 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment4/Automorphic.html
> +        <div class="jumbotron bg-white bord" style="background-image: linear-gradient(120deg, #15d6ac, #c5dad4)">
body tag is missing

2021-06-29 08:51 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment4/Krishnamurthy.html
> +<head>
check indentation

2021-06-29 08:51 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment4/Krishnamurthy.html
> +        <br /><br />
missing body tag

2021-06-29 08:51 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment5/fibonaccies.html
> +
remove extra line

2021-06-29 08:51 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment5/fibonaccies.html
> +<body>
check indentation and remove extra line

2021-06-29 08:51 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment5/fibonaccies.html
> +</html>
add extra line at the end and check indentation

2021-06-29 08:51 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment5/prime.html
> +                transition-duration: 0.4s;
style tag should be in head tag

2021-06-29 08:51 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment5/prime.html
> +</html>
add extra line at the end

2021-06-29 08:51 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment5/sum_number.html
> +</html>
add extra line at the end

2021-06-29 08:51 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment5/triangle.html
> +<head>
check indentation

2021-06-29 08:51 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment5/triangle.html
> +</html>
add extra line at the end

2021-06-30 04:50 UTC, Pawan1005 requested changes

2021-06-30 04:50 UTC, Pawan1005 commented on urmila/JAVASCRIPT/Assignment4/Automorphic.html
> +</html>
check indentation

2021-06-30 04:50 UTC, Pawan1005 commented on urmila/JAVASCRIPT/Assignment4/Krishnamurthy.html
> +    <br /><br />
remove br tag

2021-06-30 04:50 UTC, Pawan1005 commented on urmila/JAVASCRIPT/Assignment4/upper_lower.html
> +         <script>
one extra space added

2021-06-30 04:50 UTC, Pawan1005 commented on urmila/JAVASCRIPT/Assignment5/fibonaccies.html
> +</html>
check indentation

2021-06-30 04:50 UTC, Pawan1005 commented on urmila/JAVASCRIPT/Assignment5/sum.html
> +            <br><br>
body tag missing

2021-06-30 04:50 UTC, Pawan1005 commented on urmila/JAVASCRIPT/Assignment5/sum.html
> +
remove extra line

2021-06-30 04:50 UTC, Pawan1005 commented on urmila/JAVASCRIPT/Assignment5/triangle.html
> +</html>
check indentation

2021-06-30 10:54 UTC, Pawan1005 approved these changes

2021-07-01 05:26 UTC, merged