File Added : JavaScript Assignments: 3,4,5,6.
Pawan1005/MI-11-MEAN pull request #514
Opened 2021-07-01 07:42 UTC by vijaya1811

2021-07-01 15:26 UTC, shubhamdalal49 requested changes

2021-07-01 15:26 UTC, shubhamdalal49 commented on vijaya/JavaScript/assignment4/upper.html
> +            padding: 10px 0px 10px 0px;
give proper indentation

2021-07-01 15:26 UTC, shubhamdalal49 commented on vijaya/JavaScript/assignment4/upper.html
> +
check indentation and remove extra line from the end

2021-07-01 15:26 UTC, shubhamdalal49 commented on vijaya/JavaScript/assignment5/flyoid.html
> +        <body style="background-color: rgb(211, 173, 92);">
check indentation

2021-07-01 15:26 UTC, shubhamdalal49 commented on vijaya/JavaScript/assignment6/question2.html
> +
remove this extra line

2021-07-02 06:32 UTC, vijaya1811 commented
yes I modified and also push assignment9

2021-07-02 06:43 UTC, shubhamdalal49 approved these changes

2021-07-02 09:29 UTC, urmilagagare approved these changes

2021-07-02 10:33 UTC, Pawan1005 approved these changes

2021-07-04 17:22 UTC, nileshp1122 approved these changes

2021-07-05 06:31 UTC, merged