File Added : Assignment 6 & 9
Pawan1005/MI-11-MEAN pull request #515
Opened 2021-07-01 07:44 UTC by urmilagagare

2021-07-01 08:32 UTC, shubhamdalal49 requested changes

2021-07-01 08:32 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment9/palindrome.html
> +    <br><br>
why this br tags between head and body tag

2021-07-01 08:32 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment9/prime_number2.html
> +    <br>
Remove this br it is useless

2021-07-01 08:32 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment9/prime_palindrome3.html
> +    <br><br>
remove unused br tags

2021-07-01 08:32 UTC, shubhamdalal49 commented on urmila/JAVASCRIPT/Assignment9/string_palindrome.html
> +    <br>
Remove this br tag

2021-07-01 12:49 UTC, Ashwin2812 approved these changes

2021-07-01 15:20 UTC, shubhamdalal49 approved these changes

2021-07-02 06:41 UTC, vijaya1811 approved these changes

2021-07-02 10:34 UTC, Pawan1005 approved these changes

2021-07-02 13:20 UTC, merged