File Added : Assignment 5, 6 and 9
Pawan1005/MI-11-MEAN pull request #517
Opened 2021-07-01 08:19 UTC by shubhamdalal49

2021-07-01 12:43 UTC, Ashwin2812 requested changes

2021-07-01 12:43 UTC, Ashwin2812 commented on Shubham_Dalal/JavaScript/Assignment6/Question4.html
> +
Remove Extra Spaces

2021-07-01 12:43 UTC, Ashwin2812 commented on Shubham_Dalal/JavaScript/Assignment9/Count_whitespace.html
> +            function fun() {
Title should be related to assignment

2021-07-01 12:43 UTC, Ashwin2812 commented on Shubham_Dalal/JavaScript/Assignment6/Question5.html
> +       <script>
title should be related to assignment

2021-07-01 12:43 UTC, Ashwin2812 commented on Shubham_Dalal/JavaScript/Assignment6/Question3.html
> +                var array = [];
title

2021-07-01 12:43 UTC, Ashwin2812 commented on Shubham_Dalal/JavaScript/Assignment6/Question3.html
> +    </head>
remove extra spaces

2021-07-01 12:43 UTC, Ashwin2812 commented on Shubham_Dalal/JavaScript/Assignment6/Question2.html
> +
remove extra spaces

2021-07-01 12:43 UTC, Ashwin2812 commented on Shubham_Dalal/JavaScript/Assignment5/even_sum_odd_product.html
> +                var num,rem,sum = 0,product = 1;
title

2021-07-01 12:43 UTC, Ashwin2812 commented on Shubham_Dalal/JavaScript/Assignment5/comman_file.css
> +    border-color: burlywood;
add space before {

2021-07-01 12:43 UTC, Ashwin2812 commented on Shubham_Dalal/JavaScript/Assignment5/Floyd_number.html
> +            function fun() {
title

2021-07-03 12:36 UTC, Pawan1005 requested changes

2021-07-03 12:36 UTC, Pawan1005 commented on Shubham_Dalal/JavaScript/Assignment9/prime_palindrome.html
> +
html closing tag is missing
and remove extra lines

2021-07-06 03:40 UTC, Pawan1005 approved these changes

2021-07-06 04:38 UTC, Ashwin2812 approved these changes

2021-07-06 04:40 UTC, nileshp1122 approved these changes

2021-07-06 05:22 UTC, merged