File Added : JS Assignment 6 and 9
Pawan1005/MI-11-MEAN pull request #519
Opened 2021-07-01 11:11 UTC by Oshin-250197

2021-07-01 13:24 UTC, roshnidurugwar approved these changes

2021-07-03 12:49 UTC, Pawan1005 requested changes

2021-07-03 12:49 UTC, Pawan1005 commented on Oshin1/JavaScript/Assignment5/Fibonacci_series.html
> +.container {
make correct indentation

2021-07-03 12:49 UTC, Pawan1005 commented on Oshin1/JavaScript/Assignment5/Fibonacci_series.html
> +
remove extra space from body tag 
and remove extra line

2021-07-03 12:49 UTC, Pawan1005 commented on Oshin1/JavaScript/Assignment5/Fibonacci_series.html
> +</html>
body tag closing missing 
make proper indentation

2021-07-03 12:49 UTC, Pawan1005 commented on Oshin1/JavaScript/Assignment9/Prime_Palin.html
> +                            i;
put this on same line

2021-07-04 14:53 UTC, arshad05786 approved these changes

2021-07-06 03:40 UTC, Pawan1005 approved these changes

2021-07-06 06:23 UTC, merged