Added In Assignment 05 & 06
Pawan1005/MI-11-MEAN pull request #523
Opened 2021-07-01 13:43 UTC by Ashwin2812

2021-07-01 15:18 UTC, shubhamdalal49 approved these changes

2021-07-03 13:04 UTC, Pawan1005 requested changes

2021-07-03 13:04 UTC, Pawan1005 commented on Ashwin/JavaScript/09_Assignment/09_Assignment_3.html
> +</html>
make correct indentation 
add new line at the end of file

2021-07-04 17:40 UTC, nileshp1122 requested changes

2021-07-04 17:40 UTC, nileshp1122 commented on Ashwin/JavaScript/09_Assignment/09_Assignment_1.html
> +            height: 250px;
proper indent

2021-07-04 17:40 UTC, nileshp1122 commented on Ashwin/JavaScript/09_Assignment/09_Assignment_2.html
> +            height: 250px;
proper indent

2021-07-04 17:40 UTC, nileshp1122 commented on Ashwin/JavaScript/09_Assignment/09_Assignment_4.html
> +            height: 250px;
proper indent

2021-07-04 17:40 UTC, nileshp1122 commented on Ashwin/JavaScript/09_Assignment/09_Assignment_4.html
> +            height: 250px;
4 line space

2021-07-04 17:40 UTC, nileshp1122 commented on Ashwin/JavaScript/09_Assignment/09_Assignment_4.html
> +            function palindromeString() {
proper indent all JS code

2021-07-04 17:40 UTC, nileshp1122 commented on Ashwin/JavaScript/09_Assignment/09_Assignment_5.html
> +            height: 250px;
proper indent

2021-07-04 17:40 UTC, nileshp1122 commented on Ashwin/JavaScript/09_Assignment/09_Assignment_5.html
> +            function doubleLetters() {
proper indent all JS code

2021-07-04 17:40 UTC, nileshp1122 commented on Ashwin/JavaScript/09_Assignment/09_Assignment_6.html
> +        ></script>
proper indent script tag

2021-07-06 04:44 UTC, nileshp1122 approved these changes

2021-07-07 03:15 UTC, Pawan1005 approved these changes

2021-07-07 11:17 UTC, merged