New File Added: Assi5,assi6,assi9
Pawan1005/MI-11-MEAN pull request #534
Opened 2021-07-06 02:04 UTC by vinod2406

2021-07-06 10:40 UTC, Pranjali1999 requested changes

2021-07-06 10:40 UTC, Pranjali1999 commented on vinod/javascript/ASSIN5/ass5js1.html
> +
Remove extra line.

2021-07-06 10:40 UTC, Pranjali1999 commented on vinod/javascript/ASSIN5/ass5.html
> +        </style>
This style should be present within head. Make this changes everywhere.

2021-07-06 10:40 UTC, Pranjali1999 commented on vinod/javascript/ASSIN5/ass5js1.html
> +</html>
Closing body tag is always close before the closing HTML tag.

2021-07-06 10:40 UTC, Pranjali1999 commented on vinod/javascript/ASSIN5/ass5js3.html
> +        </style>
This style should be present within head

2021-07-06 10:40 UTC, Pranjali1999 commented on vinod/javascript/ASSIN5/ass5js4.html
> +        </style>
This style should be present within head

2021-07-06 10:40 UTC, Pranjali1999 commented on vinod/javascript/ASSIN5/ass5js4.html
> +
remove extra line.

2021-07-06 10:40 UTC, Pranjali1999 commented on vinod/javascript/ASSIN6/ass1q1.html
> +        </style>
This style should be present within head

2021-07-06 10:40 UTC, Pranjali1999 commented on vinod/javascript/ASSIN6/ass1q1.html
> +        </div>
give indentation properly.

2021-07-06 10:40 UTC, Pranjali1999 commented on vinod/javascript/ASSIN6/ass6.q2.html
> +        </style>
This style should be present within head

2021-07-06 10:40 UTC, Pranjali1999 commented on vinod/javascript/ASSIN6/ass6.q4.html
> +
remove extra line.

2021-07-06 10:40 UTC, Pranjali1999 commented on vinod/javascript/ASSIN6/ass6.q4.html
> +        </style>
This style should be present within head.

2021-07-06 10:40 UTC, Pranjali1999 commented on vinod/javascript/ASSIN6/ass6jsq3.html
> +        </style>
This style should be present within head.

2021-07-06 10:40 UTC, Pranjali1999 commented on vinod/javascript/ASSIN6/ass6jsq5.html
> +        </style>
This style should be present within head.

2021-07-06 10:40 UTC, Pranjali1999 commented on vinod/javascript/ASSIN9/ass9q3.html
> +        </style>
This style should be present within head.

2021-07-06 10:40 UTC, Pranjali1999 commented on vinod/javascript/ASSIN9/ass9q5.html
> +        </style>
This style should be present within head.

2021-07-06 10:40 UTC, Pranjali1999 commented on vinod/javascript/ASSIN9/ass9q6.html
> +        </div>
give indentation properly.

2021-07-08 14:51 UTC, Pranjali1999 approved these changes

2021-07-11 07:12 UTC, Pawan1005 requested changes

2021-07-11 07:12 UTC, Pawan1005 commented on vinod/javascript/ASSIN6/ass1q1.html
> +    </body>
indentation missing

2021-07-13 14:22 UTC, Pawan1005 approved these changes

2021-07-13 16:06 UTC, merged