New Files Added : JavaScript assignment 7 & 9
Pawan1005/MI-11-MEAN pull request #539
Opened 2021-07-06 11:43 UTC by Pranjali1999

2021-07-07 03:17 UTC, akash19972306 requested changes

2021-07-07 03:17 UTC, akash19972306 commented on Pranjali/JavaScript/Assi7/assi7_2.html
> +
remove extra line

2021-07-07 03:17 UTC, akash19972306 commented on Pranjali/JavaScript/Assi7/assi7_5.html
> +                    console.log(arr, n);
remove comment line

2021-07-07 03:17 UTC, akash19972306 commented on Pranjali/JavaScript/Assi9/assi9_1.html
> +
remove extra line

2021-07-07 03:17 UTC, akash19972306 commented on Pranjali/JavaScript/Assi9/assi9_1.html
> +                    //document.write("number is Palindrome");
remove comment line

2021-07-09 04:20 UTC, akash19972306 approved these changes

2021-07-11 16:19 UTC, Pawan1005 approved these changes

2021-07-12 03:27 UTC, merged