Added In Assignment 07 & 08
Pawan1005/MI-11-MEAN pull request #546
Opened 2021-07-07 12:44 UTC by Ashwin2812

2021-07-11 10:00 UTC, nileshp1122 requested changes

2021-07-11 10:00 UTC, nileshp1122 commented on Ashwin/JavaScript/08_Assignment/08_Assignment_1.html
> +        <title>Student Marks</title>
title required before script tag

2021-07-11 10:00 UTC, nileshp1122 commented on Ashwin/JavaScript/08_Assignment/08_Assignment_2.html
> +        <title>Q1</title>
proper title and title before script tag

2021-07-11 10:00 UTC, nileshp1122 commented on Ashwin/JavaScript/08_Assignment/08_Assignment_3.html
> +        <title>Marks Sorting Using Different Technique</title>
title before script, style, link tag

2021-07-11 10:00 UTC, nileshp1122 commented on Ashwin/JavaScript/08_Assignment/08_Assignment_4.html
> +        <title>Merge Sort</title>
title before script, style, link tag

2021-07-13 04:18 UTC, nileshp1122 approved these changes

2021-07-13 14:28 UTC, Pawan1005 approved these changes

2021-07-13 15:04 UTC, merged