File Added : Assignment 7 and 8
Pawan1005/MI-11-MEAN pull request #552
Opened 2021-07-08 05:53 UTC by Oshin-250197

2021-07-08 06:14 UTC, roshnidurugwar approved these changes

2021-07-08 16:35 UTC, arshad05786 approved these changes

2021-07-13 15:08 UTC, Pawan1005 requested changes

2021-07-13 15:08 UTC, Pawan1005 commented on Oshin1/JavaScript/Assignment7/Triangle.html
> +
remove extra line

2021-07-13 15:08 UTC, Pawan1005 commented on Oshin1/JavaScript/Assignment8/Quick_sort.html
> +</html>
add new line at the end of file

2021-07-13 15:08 UTC, Pawan1005 commented on Oshin1/JavaScript/Assignment8/Quick_sort.html
> +        </div>
closing these div at there potion not after script tag

2021-07-13 15:08 UTC, Pawan1005 commented on Oshin1/JavaScript/Assignment8/Sort1.html
> +        </div>
close these div at there position not after script tag

2021-07-13 15:08 UTC, Pawan1005 commented on Oshin1/JavaScript/Assignment8/Sort2.html
> +        </div>
close these div at there position not after script tag

2021-07-14 16:45 UTC, Pawan1005 approved these changes

2021-07-14 16:45 UTC, merged