File added javacsript assignment7
Pawan1005/MI-11-MEAN pull request #554
Opened 2021-07-08 09:49 UTC by vijaya1811

2021-07-11 10:51 UTC, nileshp1122 requested changes

2021-07-11 10:51 UTC, nileshp1122 commented on vijaya/JavaScript/assignment7/ques2.html
> +        h1 {
proper indent space required

2021-07-11 10:51 UTC, nileshp1122 commented on vijaya/JavaScript/assignment7/ques2.html
> +        var size,x = 1;
proper indent space required

2021-07-11 10:51 UTC, nileshp1122 commented on vijaya/JavaScript/assignment7/ques3.html
> +    <meta charset=utf-8 />
proper indent space required

2021-07-11 10:51 UTC, nileshp1122 commented on vijaya/JavaScript/assignment7/ques3.html
> +        var size, x = 1;
proper indent space required

2021-07-11 10:51 UTC, nileshp1122 commented on vijaya/JavaScript/assignment7/ques4.html
> +        <meta charset=utf-8 />
proper indent space required

2021-07-11 10:51 UTC, nileshp1122 commented on vijaya/JavaScript/assignment7/ques4.html
> +            var size, x = 1;
proper indent space required

2021-07-11 10:51 UTC, nileshp1122 commented on vijaya/JavaScript/assignment7/ques4.html
> +
add extra line at end

2021-07-11 10:51 UTC, nileshp1122 commented on vijaya/JavaScript/assignment7/ques5.html
> +    <meta charset=utf-8 />
proper indent space required

2021-07-11 10:51 UTC, nileshp1122 commented on vijaya/JavaScript/assignment7/ques5.html
> +        var size, x = 1;
proper indent space required

2021-07-11 10:51 UTC, nileshp1122 commented on vijaya/JavaScript/assignment7/triangle.html
> +        .name {
proper indent

2021-07-11 10:51 UTC, nileshp1122 commented on vijaya/JavaScript/assignment7/triangle.html
> +        .one{
before { space required

2021-07-13 13:42 UTC, nileshp1122 approved these changes

2021-07-13 15:40 UTC, Pawan1005 requested changes
make changes asap

2021-07-13 15:40 UTC, Pawan1005 commented on vijaya/JavaScript/assignment7/ques2.html
> +            <style>
remove 1 tab space

2021-07-13 15:40 UTC, Pawan1005 commented on vijaya/JavaScript/assignment7/ques2.html
> +            </style>
remove 1 tab space

2021-07-13 15:40 UTC, Pawan1005 commented on vijaya/JavaScript/assignment7/ques2.html
> +        <body>
make correct indentation

2021-07-13 15:40 UTC, Pawan1005 commented on vijaya/JavaScript/assignment7/ques2.html
> +        </body>
make correct indentation

2021-07-13 15:40 UTC, Pawan1005 commented on vijaya/JavaScript/assignment7/ques3.html
> +        h1 {
make correct indentation

2021-07-14 16:49 UTC, Pawan1005 requested changes

2021-07-14 16:49 UTC, Pawan1005 commented on vijaya/JavaScript/assignment7/ques5.html
> +    </style>
give proper indentation

2021-07-14 16:49 UTC, Pawan1005 commented on vijaya/JavaScript/assignment7/ques4.html
> +</html>
remove extra lines

2021-07-15 11:29 UTC, shubhamdalal49 approved these changes

2021-07-15 12:44 UTC, urmilagagare approved these changes

2021-07-15 15:48 UTC, Pawan1005 approved these changes

2021-07-15 15:48 UTC, merged