File Added : Assigment 7&8
Pawan1005/MI-11-MEAN pull request #557
Opened 2021-07-09 05:32 UTC by Amit727619

2021-07-12 15:23 UTC, pooja-nagare commented on amit/Javascript/Assigment7/Assigment7_2 .html
> +
Remove extra line

2021-07-12 15:23 UTC, pooja-nagare commented on amit/Javascript/Assigment7/Assigment7_2 .html
> +
Remove extra line

2021-07-12 15:25 UTC, pooja-nagare commented on amit/Javascript/Assigment7/Assigment7_4.html
> +
Remove extra line

2021-07-12 15:25 UTC, pooja-nagare commented on amit/Javascript/Assigment7/Assigment7_4.html
> +
Remove extra lines

2021-07-12 15:26 UTC, pooja-nagare commented on amit/Javascript/Assigment7/Assigment7_5.html
> +
Remove extra line

2021-07-12 15:26 UTC, pooja-nagare commented on amit/Javascript/Assigment7/Assigment7_5.html
> +
Remove all extra lines

2021-07-12 15:27 UTC, pooja-nagare commented on amit/Javascript/Assigment7/Assigment7_5.html
> +
Remove extra line

2021-07-13 16:14 UTC, Pawan1005 requested changes

2021-07-13 16:14 UTC, Pawan1005 commented on amit/Javascript/Assigment7/Assigment7_2 .html
> +
remove extra line

2021-07-13 16:14 UTC, Pawan1005 commented on amit/Javascript/Assigment7/Assigment7_2 .html
> +         <body>
create proper indentation

2021-07-13 16:14 UTC, Pawan1005 commented on amit/Javascript/Assigment7/Assigment7_2 .html
> +    </body>
remove extra body tag

2021-07-13 16:14 UTC, Pawan1005 commented on amit/Javascript/Assigment7/Assigment7_2 .html
> +</html>
add new line at the end of file

2021-07-13 16:14 UTC, Pawan1005 commented on amit/Javascript/Assigment8/Assigment8_1.html
> +        </style>
put style tag in head part

2021-07-13 16:14 UTC, Pawan1005 commented on amit/Javascript/Assigment8/Assigment8_2.html
> +
remove extra line

2021-07-13 16:14 UTC, Pawan1005 commented on amit/Javascript/Assigment8/Assigment8_2.html
> +
remove extra line

2021-07-13 16:14 UTC, Pawan1005 commented on amit/Javascript/Assigment8/Assigment8_3.html
> +        </style>
put style tag in head part

2021-07-13 16:14 UTC, Pawan1005 commented on amit/Javascript/Assigment8/Assigment8_4.html
> +        </style>
put style tag in head part

2021-07-14 16:53 UTC, Pawan1005 approved these changes

2021-07-14 16:53 UTC, merged