Folders added: Javascrit assignment 10,12,13,14.
Pawan1005/MI-11-MEAN pull request #594
Opened 2021-07-19 17:19 UTC by vijaya1811

2021-07-19 17:30 UTC, shubhamdalal49 approved these changes

2021-07-20 07:50 UTC, nileshp1122 approved these changes

2021-07-21 16:10 UTC, Pawan1005 requested changes
make changes asap

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment10/Q1.html
> +    </head>
make correct indentation for head tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment10/Q8.html
> +        </style>
make correct indentation for head tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment10/Q7.html
> +        </style>
make correct indentation for style tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment10/Q6.html
> +        </style>
make correct indentation for style tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment10/Q6.html
> +        </script>
make correct indentation for script tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment10/Q5.html
> +        </style>
make correct indentation for style tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment10/Q3.html
> +        </style>
make correct indentation for style tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment10/Q2.html
> +        </style>
make correct indentation for style tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment13/Q1.html
> +        </script>
make correct indentation for script tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment14/Q1.html
> +        </style>
head tag closing missing

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment14/Q2.html
> +    <body>
head tag closing missing

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment5/fibb.html
>          <style>
make correct indentation for style tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment7/ques3.html
> +        </script>
make correct indentation for script tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment7/ques4.html
> +</html>
remove extra lines

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment7/ques5.html
> +    </head>
make correct indentation for head tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment7/ques5.html
> +        </script>
make correct indentation for script tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment7/triangle.html
> +        </style>
make correct indentation for style tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment7/triangle.html
> +        </script>
make correct indentation for script tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment7/triangle.html
> +        <body style="background-color: rgb(102, 101, 101);">
make correct indentation for body tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment7/triangle.html
> +        </body>
make correct indentation for body tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment8/Que1.html
> +        </style>
make correct indentation for style tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment8/Que1.html
> +        </script>
make correct indentation for script tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment8/Que2.html
> +        </style>
make correct indentation for style tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment8/Que2.html
> +        </script>
make correct indentation for script tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment8/Que3.html
> +        </style>
make correct indentation for style tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment8/Que3.html
> +        }
make correct indentation for script tag

2021-07-21 16:10 UTC, Pawan1005 commented on vijaya/JavaScript/assignment8/Que4.html
> +</html>
add new line at the end of file

2021-07-22 10:01 UTC, Pawan1005 approved these changes

2021-07-22 10:01 UTC, merged